### ISSUE TITLE
 boosting relevance

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#108]
some ideas:

- Plug Google Analytics with Elasticsearch - the more a document is clicked is more is relevant
- Log the search queries to know which ones are the most common and focus the relevance on these searches
- Document with picture are more relevant
- Document containing more data are more relevant

**Comment by iteles** [comment]
2 days allocated to this in sprint 3, towards the end. Dependent on @jamieu providing details around what needs to be updated.

**Comment by Danwhy** [comment]
In progress as #213
