### ISSUE TITLE
Filtering - Display the list of filters depending on the results

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#109]
Filters should change based on the search query/ type of resource being searched for eg. objects should have makers, people shouldn't.

Get all possible filters for the query.

**Comment by SimonLab** [comment]
The facets are build dynamically depending on a first search. So for each kind of search (all, people, documents or objects) we need to
- [ ] check the mapping (type) of each values we are filter on. For most of them we want the value to not be analysed! You can check the mapping of a type in elasticsearch with a get request to host/index/type/_mapping. For the fields with 
- [ ] build a specific aggregation.
- [ ] use [post filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-post-filter.html) on the aggregation to filter the results without filtering the facets

A [good article](https://www.elastic.co/fr/blog/amelioration-de-la-navigation-utilisateur-sur-bricozor-avec-elasticsearch) which describe the process on how to build the Facets for a search engince. It's in French but let me know if you want an English translation!
