### ISSUE TITLE
Page number maximum value

### ISSUE THREAD

**Issue by philhardy** [TheScienceMuseum/collectionsonline#1102]
Hi

I'm receiving the following error when trying to get a page number greater than 10 from the API -

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "child \"query\" fails because [child \"page[number]\" fails because [\"page[number]\" must be less than or equal to 10]]"
}
```

also seen in the website [here](https://collection.sciencemuseum.org.uk/search?page[number]=11).

Is this intentional? I notice the links in successful responses refer to pages with a greater number, e.g. 
```
"links": {
        "self": "https://collection.sciencemuseum.org.uk/search/objects/museum/science-museum?page[number]=10&page[size]=5",
        "first": "https://collection.sciencemuseum.org.uk/search/objects/museum/science-museum?page[size]=5",
        "last": "https://collection.sciencemuseum.org.uk/search/objects/museum/science-museum?page[number]=390&page[size]=5",
        "prev": "https://collection.sciencemuseum.org.uk/search/objects/museum/science-museum?page[number]=9&page[size]=5",
        "next": "https://collection.sciencemuseum.org.uk/search/objects/museum/science-museum?page[number]=11&page[size]=5"
}
```

Many thanks in advance

Phil

**Comment by philhardy** [comment]
I've just noticed there was actually a closed issue/PR for this so I can close this. Do you have any ETA on that change being released?

**Comment by jamieu** [comment]
Hi @philhardy 

We removed the ability to page past ten pages of results as we were experiencing issues with crawlers requesting the higher pages of search results with sorting/ordering turned on, which was proving hugely inefficient and causing issue for everyday site users.

As you've spotted we looking at providing a better mechanism for retrieving large sets of results/data that doesn't put such a high load on our index (several solutions in the pipeline). But in the short term feel free to get in touch (jamie.unwin [at] sciencemusuem.ac.uk) as I may be able to provide you the whole set of data in a more convenient manner.

**Comment by philhardy** [comment]
Thanks Jamie

**Comment by iteles** [comment]
@jamieu Worth adding a line to our docs on this?
