### ISSUE TITLE
Branch tidy-up

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#1107]
@jamieu Are you happy for me to go through and delete any merged branches (both yours and ours)?
We can then see which ones exist without PRs and determine whether they can be deleted or should be revived 😊 

<img width="188" alt="screen shot 2018-01-12 at 16 29 23" src="https://user-images.githubusercontent.com/4185328/34884906-1e17dcd8-f7b6-11e7-82fa-c5df4086eab5.png">
<img width="925" alt="screen shot 2018-01-12 at 16 30 44" src="https://user-images.githubusercontent.com/4185328/34884909-1f5a3a14-f7b6-11e7-98d7-54af613da4e0.png">

**Comment by iteles** [comment]
Thanks Jamie!

Can you please confirm whether these two are to be deleted?
<img width="912" alt="screen shot 2018-01-12 at 18 10 22" src="https://user-images.githubusercontent.com/4185328/34888900-f2231116-f7c3-11e7-9426-c071e963cf8c.png">

**Comment by jamieu** [comment]
Both those can be deleted!

**Comment by iteles** [comment]
Thanks @jamieu! Done.

In that case, @SimonLab, I'm assuming this branch is no longer relevant and we can delete it and close this issue?
<img width="887" alt="screen shot 2018-01-12 at 20 33 39" src="https://user-images.githubusercontent.com/4185328/34894125-03d28ee6-f7d8-11e7-8fae-877617d5cc23.png">

**Comment by SimonLab** [comment]
@iteles I've just delete this branch 👍

**Comment by SimonLab** [comment]
The only active branch is "whatis":
![image](https://user-images.githubusercontent.com/6057298/34904893-6b4c2c76-f846-11e7-95c4-be71660b1bf3.png)

This branch is already merged in master so I think we can also delete it. We can create a new one from master for fixing the next bug. @jamieu do you mind to delete the branch or do you want to keep it?
