### ISSUE TITLE
Update to HAPI v17

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1111]

**Comment by Danwhy** [comment]
@jamieu I've just about finished with the Hapi upgrade, but just wanted to check which version of node the live site is running on, as hapi 17+ requires at least node v8.12.0

**Comment by jamieu** [comment]
@Danwhy I just upgraded the staging server to 8.15.0 and it seems to be running fine.

Let me know if you think we should make the jump to node 10 or leave it at 8 for now.
