### ISSUE TITLE
Investigate broken link in sitemap.xml

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1113]
http://collection.sciencemuseum.org.uk/objects/co8457862/parts-of-the-hartree-differential-analyser-washers

in

https://s3-eu-west-1.amazonaws.com/smgco-sitemaps/sitemap-1.xml

**Comment by SimonLab** [comment]
Searching on the sitemap and on the collection for any link/objects which contains one of the term of the url above (parts-of-the-hartree-differential-analyser-washers) doesn't return any result.
I think the item is not in Elasticsearch anymore (or has been renamed?) and the sitemap took a bit of time to update (this is done with a lambda, see https://github.com/TheScienceMuseum/collectionsonline-sitemap)
