### ISSUE TITLE
Investigate incorrect extraction of 'extent' field from archives

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1114]
In some Collections Online records this field is displayed correctly, pulling the information from the ‘Extent’ field in Adlib.
Examples: WKC; BAB, MS/0122; MOOR
 
In other records it pulls the information from the ‘Dimensions’ field, which is not correct and the way it is displayed meaningless to the users.
Examples: MSL/0358; MS/0201; MS/0206; MS/0211
 
In other records it is missing altogether.
Examples: MS/0222
 
In others it is recorded as ‘undefined’, sometimes twice.
Examples: MS/0124; MS/0124
 
This should always pull the information from the ‘Extent’ field in Adlib, there is always info there.

**Comment by Danwhy** [comment]
As we discussed yesterday, this seems to be an issue with the data; all of the records get their `extent` information from the `measurements` field, so there's no way to get the information for some and not others. 
@jamieu Is there anything you wanted us to do here? I guess the options are remove it for all documents or leave it as is.

**Comment by jamieu** [comment]
Thanks Daniel, I think leave it to me to sort out the index, not sure there
is much more you can do in this sprint.
