### ISSUE TITLE
Stop HTML/Category specific logic imposing on API calls

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1117]
https://github.com/TheScienceMuseum/collectionsonline/blob/master/routes/search.js

>              // match categories
>               if (value.query.q && (!value.categories['filter[categories]'])) {
>                 var q = value.query.q.toLowerCase();
>                 var qMatch;
> 
>                 if (keyCategories.some(el => {
>                   if (el.category === q || el.synonyms.indexOf(q) > -1) {
>                     qMatch = el.category;
>                     return true;
>                   } else {
>                     return false;
>                   }
>                 })) {
>                   return reply.redirect(request.path + '/categories/' + qMatch);
>                 }
>               }

**Comment by iteles** [comment]
Linked to #1115 .
