### ISSUE TITLE
Submit filter button

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#113]
If javascript is disabled we display a submit button which allow a user to filter the search results.
If javascript is enabled we just hide the submit button and the filter searches are managed with Page.js

**Comment by jamieu** [comment]
Have added @tobystokes as w'll probably need a button designed to sit at the bottom of the facet block.

**Comment by tobystokes** [comment]
![image](https://cloud.githubusercontent.com/assets/109024/16623495/2ba56e04-4396-11e6-89d6-f5d55c7f669f.png)

**Comment by jamieu** [comment]
Thanks Toby, that works for me.
