### ISSUE TITLE
Update global header to match other SMG sites

### ISSUE THREAD

**Issue by tobystokes** [TheScienceMuseum/collectionsonline#1147]
From previous discussions, Ideally global SMG nav elements to be introduced, but at minimum consolidate museum logos to something like

 ![smg-col-newhomebanner 2x](https://user-images.githubusercontent.com/109024/41672277-66aedbcc-74b1-11e8-9ea4-314f4f8224fb.png)

**Comment by johnstack** [comment]
Also, on mouse hover the menu underline should animate left-to-right rather from the centre out as in this example https://www.sciencemuseumgroup.org.uk

![ezgif-1-af3618abb648](https://user-images.githubusercontent.com/1881723/62831943-ae404880-bc1e-11e9-95f4-0729372366de.gif)
