### ISSUE TITLE
Title being omitted on paginated pages

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1175]
Search for this url in Google `https://collection.sciencemuseum.org.uk/search/categories/aeronautics`

https://collection.sciencemuseum.org.uk/search/categories/aeronautics?page[number]=3

<img width="974" alt="Screenshot 2019-03-18 at 16 46 42" src="https://user-images.githubusercontent.com/91365/54547357-70a40000-499d-11e9-9b9b-f3c7ae3c8e14.png">

<img width="791" alt="screen shot 2018-08-30 at 16 50 23" src="https://user-images.githubusercontent.com/91365/44877187-152d5180-ac9b-11e8-89a1-3b6627e9d507.png">

**Comment by SimonLab** [comment]
The title meta tag is defined as `Search our collection | Science Museum Group Collection` on the search result pages.
From https://support.google.com/webmasters/answer/35624?hl=en Goggle doesn't seem to like repeated titles (the title is the same when a search result returns multiple pages):
![image](https://user-images.githubusercontent.com/6057298/55011559-f4816c00-4fdd-11e9-976e-ee4141c9f7d1.png)

In this case Google generate a slightly different title by adding the page number:
![image](https://user-images.githubusercontent.com/6057298/55011637-0fec7700-4fde-11e9-851e-953dead3a85c.png)

**Comment by jamieu** [comment]
Well spotted :-)

Can we make it more specific ie. Category, Object Type, Gallery/Museum
name, Search query etc. -- In fact  thought we were already doing that (on
my mobile so can't see the current titles)

Might also be nice/better to append " | Page 2" etc. rather than letting
Google simply append a number, but not sure if that is tricky?

**Comment by jamieu** [comment]
Might be most sensible to copy the pattern in there URL structure ie.

ie. 

- https://collection.sciencemuseum.org.uk/search/museum/national-railway-museum/gallery/warehouse/places/leeds

- `Search our collection | National Railway Museum, Warehouse | Science Museum Group Collection`

- https://collection.sciencemuseum.org.uk/search/categories/motive-power
- `Search our collection | Motive Power | Science Museum Group Collection`

(and append `Page 2, 3` to the end on any pages (after the first. ie. don't display `Page 1` in the title)

**Comment by evancp87** [comment]
@jamieu now that i've fixed and closed this (page title ticket)[https://github.com/TheScienceMuseum/collectionsonline/issues/1356] i'm wondering how to approach this one?

I did have a brief look and i'm not seeing pagination numbers in google, not sure if that's something i've introduced with my changes in the above ticket. I could look into appending the page number onto the title if on page 2 onwards.

![image](https://github.com/TheScienceMuseum/collectionsonline/assets/65721884/a76a760f-16f5-47bf-aab5-1bc61b84b493)

**Comment by jamieu** [comment]
I think that's probably the correct behavior 

We **DON'T** want pagination numbers in our title tags (..despite what I may have said in my comment above from 2019!!)

But we do want the filters to appear in the <title> tags.

But I think there is a probably limit here and after 3 (?) filters, we want want to prioritise what the most important ones to display are, otherwise the <title> tag will be too long for Google. But it starts to get tricky.  [This is the latest (2024) guidance from Google](https://developers.google.com/search/docs/appearance/title-link).

Here's a 'starter for 10' but not weeded to it (so don't feel you have to follow this pattern exactly). There probably a sensible tradeoff here between overtly complex logic and titles that are 'good enough' for Google and bookmarking. So maybe tackle it in two passes.

But I think getting good titles for our 'landing pages' is probably crucial in terms of SEO so this is hopefully well worth the effort.

###Top level type
Objects, People, Document and (soon) Groups.

- **objects** -> `Objects | Science Museum Group Collection`
- **documents** ->`Documents and Archives | Science Museum Group Collection`
- **people** ->`People and Companies | Science Museum Group Collection`
- **groups** ->`Explore objects by Group | Science Museum Group Collection` (need to think about wording on this one)

###1st class object filters (on their own)

These apply only to **objects** so we can exclude the 'Object' label if these filters are selected. 
- Category filter -> `Motive Power  | Science Museum Group Collection`  
- Museum (On Display) filter -> `On display at the National Railway Museum, Warehouse | Science Museum Group Collection` ie. _(`<museum>`, `<gallery>`)_
- Named Collection (Collection) filter -> `Kodak Collection | Science Museum Group Collection` 
- SubGroup (Group) filter -> `COVID 19 | Science Museum Group Collection` 

These apply only to **documents** so we can exclude the 'Document' label if these filters are selected. 
- Archive filter -> `Documents in the Babbage Archive | Science Museum Group Collection` 

###2nd class filters 

##Use long form if these are the only filters (other than top level type)
- **maker**  (object)-> `Objects by John Smith | Science Museum Group Collection`  
- **maker** (document) -> 'Documents by John Smith | Science Museum Group Collection` 
- **place** (object) -> `Objects from Manchester | Science Museum Group Collection` 
- **place** (document) -> `Documents from Manchester | Science Museum Group Collection`

##Use shorter form if multiple filters
- **place**  + **named collection**  -> `Kodak Collection : Manchester | Science Museum Group Collection`  
- **place**  + **sub-group**  -> `COVID 19 : Manchester | Science Museum Group Collection`  
- **maker**  + **named collection**  -> `Kodak Collection : John Smith | Science Museum Group Collection`  
- *maker**  + **sub-group -> `COVID 19 : John Smith | Science Museum Group Collection`  
- **place**  + ** maker**  -> `Manchester : John Smith | Science Museum Group Collection` 

###3rd class filters
Append these these using a colon ie. `<as above> : <3rd class filter> :  <3rd class filter> | Science Museum Group Collection`.

- material 
- object type  
- date

_(we maybe should treat dates differently, esp. if it's the **only** filter ie. 'Objects made in 1982' but for now let's just append it to the end of the other filters)._

**Comment by evancp87** [comment]
Complete
