### ISSUE TITLE
Add animated gradients 

### ISSUE THREAD

**Issue by johnstack** [TheScienceMuseum/collectionsonline#1191]
Where SMG brand gradients are implemented in the header and footer to make animated as with brand websites.

**Comment by tobystokes** [comment]
We can't really re-use Numiko's implementation here, too much of a different javascript stack.
(I followed the require()'s until I hit a jquery, and figured that was a dead end!)

Though i'm not really sure why they are using javascript for this animation anyway, except that it looks like it uses the accelerometer if available on mobile devices to orient it. In any case, if the main aim is to just have a subtle movement, that could be done in just css - though it wouldn't match other websites exactly. on the plus side, might be retro-fittable to all the wordpress sites too.

**Comment by jamieu** [comment]
I think that's probably good enough; just writing up some notes re. the
home page.

**Comment by johnstack** [comment]
Yes. Jamie's right that's good enough and it'd be good to add into the Wordpress sites too. Shall I open a ticket there too or can I just leave with you? Cheers!

**Comment by tobystokes** [comment]
leave it with me and i'll liaise with @argenteum when done
