### ISSUE TITLE
Missing values on object page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#120]
Linked to #106 
Duchess of Hamilton
Accession No. #1976-7000
/objects/smgc-objects-205752

Note: category, materials, terms, taxonomy terms, makers, locations, places etc. should all be linkable (back to the search resulst page wi the relevent fiter set)

1) Makers (top of page)

We should list all of these at the top of the page on seperate lines, prefixed by their relationship/role. 
(prior to launch we will need to supress all but a defined/limited set of relationships (maker, designer, inventor etc; which will be supplied), but for now it would be useful to allow testers to see all the values)

``````
"maker": [{
    "@link": {
        "role": [{
            "value": "designer"
        }],
        "type": "reference"
    },
    "admin": {
        "id": "agent-1015",
        "uid": "smgc-agent-1015"
    },
    "summary_title": "Stanier, Sir William Arthur"
}, {
    "@link": {
        "role": [{
            "value": "maker"
        }],
        "type": "reference"
    },
    "admin": {
        "id": "agent-3891",
        "uid": "smgc-agent-3891"
    },
    "summary_title": "London, Midland & Scottish Railway"
}],
``````
2) CREDIT (tombstone block)

credit_line

``````
"legal": {
    "credit_line": "Butlins",
    "legal_status": "permanent collection"
},

``````

3) MEASUREMENTS (tombstone block)

component.measurements[].display

Need to display multiple measurements on seperate lines ie.

length over buffers: 22511 mm,
driving wheel diameter: 2057 mm

``````
    "component": [{
        "measurements": {
            "dimensions": [{
                "dimension": "depth",
                "units": "in",
                "value": "886 1/4"
            }, {
                "dimension": "depth",
                "units": "mm",
                "value": "22511"
            }],
            "display": "length over buffers: 22511 mm,"
        },
        "name": "length over buffers"
    },
    {
        "measurements": {
            "dimensions": [{
                "dimension": "diameter",
                "units": "in",
                "value": "81"
            }, {
                "dimension": "diameter",
                "units": "mm",
                "value": "2057"
            }],
            "display": "driving wheel diameter: 2057 mm,"
        },
        "name": "driving wheel diameter"
    }
``````

4) Type (tombstone block)

``````
"name": [
  {
    "primary": true,
    "type": "object name",
    "value": "steam locomotive"
  }
]
``````

5) Taxonomy (tombstone block)

In addition to the above name.value (which is a free text field) an object can have multiple 'terms' associated with it. 

The plan is to de-normalise the index so that the parent/broader terms for each individual term is stored on the object document itself. Once that index work is complete we should then be able to construct a hierarchy for each term (which we will display side by side; three wide).

However, in the interim can we just display a comma seperated list of 'terms' where the value is equal to "Object Name". 

``````
"terms": [
      {
        "@link": {
          "role": [
            {
              "value": "Object Name"
            }
          ],
          "type": "reference"
        },
        "admin": {
          "id": "term-262150",
          "uid": "smgc-term-262150"
        },
        "summary_title": "photograph"
      },
      {
        "@link": {
          "role": [
            {
              "value": "Object Name"
            }
          ],
          "type": "reference"
        },
        "admin": {
          "id": "term-267305",
          "uid": "smgc-term-267305"
        },
        "summary_title": "Photography"
      },
``````

**Comment by Danwhy** [comment]
linked to #106

**Comment by Danwhy** [comment]
@jamieu 
When you say the measurements should be displayed on separate lines, do you mean separately _within_ a measurements block ie:

```
measurements: length over buffers: 22511 mm
              driving wheel diameter: 2057 mm
```
or as a separate block for each measurement?:

```
length over buffers:       22511 mm
driving wheel diameter:    2057 mm
```

**Comment by jamieu** [comment]
For now just the display values (for the example above):

- "display": "length over buffers: 22511 mm,"
- "display": "driving wheel diameter: 2057 mm,"
