### ISSUE TITLE
Filter display order

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#121]
For each facets a list of filters is extracted depending on the result of the search. For example on the "Occupation" facet for the people a search can find the filters "mathematician", "aviator",... There is not a specific order at the moment for the list of filters. Should we order the list of filter alphabetically? @jamieu  @Danwhy what are your thoughts on this?

**Comment by jamieu** [comment]
Ordre should be numerical (but we need to retain existing/selected values so they can be deselected)

Have created a wiki page here with order and agreed logic (although do let me know if the logic seems odd once you start implementation!)
https://github.com/TheScienceMuseum/collectionsonline/wiki/Facet-display-and-functionality

**Comment by SimonLab** [comment]
see wiki page for the description of the filters order
