### ISSUE TITLE
360 uploader : XML files need to have content type set to text/xml 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1216]
Related to 360 repo but adding here so I can add it to a GitHub project
https://github.com/TheScienceMuseum/360-image-uploader/issues/19

<img width="590" alt="Screenshot 2019-03-18 at 15 27 08" src="https://user-images.githubusercontent.com/91365/54546962-b7452a80-499c-11e9-9b8c-ab6028d38ad3.png">

**Comment by Danwhy** [comment]
@jamieu Did you want us to just check that the content type is set to text/xml and return an error if it's not, or did you want us to actually edit/add the content type to the file?

**Comment by jamieu** [comment]
Can we get the Lamda function to set it (Content-type: text/xml I think)

It doesn’t seem to be set when the file is unzipped. But the 360 app
expects a mime type / content header.

I manually set all the current ones (post upload / expansion), but new ones
are left unset.
