### ISSUE TITLE
New 'box' icon for top level of archive

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#125]
Been thinking about the icons for archive / documents and have decided it would be better to use a 'box' or 'filing cabinet' icon to represent the very top level of an archive ('the fonds record').

For beta-launch any document or series - other than the very top level fonds record - will still use the existing document icon, regardless of where it sits in the hierarchy.

But by creating/using a new top level icon to represent the whole archive, it leaves us room to use the current 'folder icon' to represent the levels between the 'fonds' and a leaf node document at the bottom of the tree, if we need be.

Not sure if there is suitable icon in the same family as we are using for the folder/document, if not something like the ones below would work. We've ticked the ones we slightly prefer, the main concern is that is represents a filing box / doesn't get confused with the object icon. But more than open to your input :-)

<img width="708" alt="screen shot 2016-07-01 at 11 03 37" src="https://cloud.githubusercontent.com/assets/91365/16518616/b5713ad8-3f7b-11e6-855d-01ec3248e2dc.png">

**Comment by tobystokes** [comment]
![image](https://cloud.githubusercontent.com/assets/109024/16519838/c92f5728-3f83-11e6-916f-5d522d90b390.png)

think i prefer filing cabinet to box - better distinguished from generic cuby thing?

**Comment by jamieu** [comment]
Oh..nice..!!

Consensus here is the (2nd) filing cabinet stands out more at a small size too.

Jamie

**Comment by jamieu** [comment]
Happy to branch / switch it over / commit it, if you have a SVG of it? or an original I can convert.
https://github.com/TheScienceMuseum/collectionsonline/blob/master/public/assets/img/archive.svg

**Comment by tobystokes** [comment]
I need to test it in situ, so i can commit.
have also tweaked the objects icon, to be a bit less cuby.
Also included watch script to watch for svg changes.
n.b that path above, is the compiled, original is in clients/icons
