### ISSUE TITLE
Add a query param for auto generated AI/ML image tags 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1253]
We'd like to add a new query parameter to both the HTML and API queries for our new ML generated images tags (see below record and half a dozen other records with a `rekognition` tag to see the new block of JSON).

We don't need any new front end UI elements, just the query parameters.

Something like:
http://collection.sciencemuseum.org.uk/search/imgtag/poster

And maybe a cutoff point (_but don't kill yourself implementing this part if tricky_):
http://collection.sciencemuseum.org.uk/search/imgtag/poster?confidence=90

And may the ability to also search parent terms as well (_but again, don't kill yourself implementing this part if tricky_):
http://collection.sciencemuseum.org.uk/search/imgtag/poster?include_parents=true

It would also be useful to have a route/page that displayed a list of all the tags we have ie.
http://collection.sciencemuseum.org.uk/imgtags

https://collection.sciencemuseum.org.uk/api/objects/co8223508
https://collection.sciencemuseum.org.uk/objects/co8223508

```
         "enhancement": {
            "rekognition": {
              "label": [
                {
                  "confidence": 76.01893,
                  "instances": [
                    {
                      "confidence": 76.01893,
                      "region": {
                        "height": 0.20961826,
                        "left": 0.2979818,
                        "top": 0.7685999,
                        "type": "bounding box",
                        "width": 0.4004531
                      }
                    }
                  ],
                  "name": "Bench",
                  "parents": [
                    {
                      "name": "Furniture"
                    }
                  ]
                },
                {
                  "confidence": 76.01893,
                  "name": "Furniture"
                },
                {
                  "confidence": 95.04376,
                  "name": "Clinic"
                },
                {
                  "confidence": 98.75234,
                  "instances": [
                    {
                      "confidence": 98.75234,
                      "region": {
                        "height": 0.2838224,
                        "left": 0.33376923,
                        "top": 0.526551,
                        "type": "bounding box",
                        "width": 0.26681834
                      }
                    }
                  ],
                  "name": "Dog",
                  "parents": [
                    {
                      "name": "Animal"
                    },
                    {
                      "name": "Pet"
                    },
                    {
                      "name": "Canine"
                    },
                    {
                      "name": "Mammal"
                    }
                  ]
                },
                {
                  "confidence": 98.75234,
                  "name": "Animal"
                },
                {
                  "confidence": 98.75234,
                  "name": "Canine",
                  "parents": [
                    {
                      "name": "Animal"
                    },
                    {
                      "name": "Mammal"
                    }
                  ]
                },
                {
                  "confidence": 98.75234,
                  "name": "Mammal",
                  "parents": [
                    {
                      "name": "Animal"
                    }
                  ]
                },
                {
                  "confidence": 98.75234,
                  "name": "Pet",
                  "parents": [
                    {
                      "name": "Animal"
                    }
                  ]
                },
                {
                  "confidence": 99.428734,
                  "name": "Veterinarian",
                  "parents": [
                    {
                      "name": "Person"
                    },
                    {
                      "name": "Doctor"
                    }
                  ]
                },
                {
                  "confidence": 99.899155,
                  "instances": [
                    {
                      "confidence": 99.71886,
                      "region": {
                        "height": 0.6728183,
                        "left": 0.5197421,
                        "top": 0.309557,
                        "type": "bounding box",
                        "width": 0.32606694
                      }
                    },
                    {
                      "confidence": 98.87891,
                      "region": {
                        "height": 0.6872026,
                        "left": 0.25182652,
                        "top": 0.2538627,
                        "type": "bounding box",
                        "width": 0.1666054
                      }
                    }
                  ],
                  "name": "Person"
                },
                {
                  "confidence": 99.899155,
                  "name": "Doctor",
                  "parents": [
                    {
                      "name": "Person"
                    }
                  ]
                },
                {
                  "confidence": 99.899155,
                  "name": "Human"
                }
              ]
            }
          },
```

**Comment by SimonLab** [comment]
Attempting to aggregate the tag name return the elasticsearch error:
>[illegal_argument_exception] Fielddata is disabled on text fields by default. Set fielddata=true on [multimedia.enhancement.rekognition.label.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

If the tag is created automatically I'm wondering if it is properly indexed in Elasticsearch and if a mapping is defined for the field (see https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html). If not it might make the searches based on this field slog

**Comment by SimonLab** [comment]
I manage to extract all the tags by creating the aggregation on the `keyword` field of the tag name value. 
![image](https://user-images.githubusercontent.com/6057298/54537740-eeaadb80-498a-11e9-89ca-e76d863bb522.png)

I found in total 42 unique tags (from the fields `multimedia.enhancement.rekognition.label.name.keyword` and `multimedia.enhancement.rekognition.label.parents.name.keyword`). Does this total seems correct @jamieu ?

**Comment by jamieu** [comment]
Hi Simon,

No by no means all the tags, we still have another 20,000+ images to tag up
so this list will grow considerably!

I think currently there are only a dozen records/images with ML image tags.

btw. it would be preferable to not have to generate any lists (in advance)
as the list of possible tags/values will change whenever we add new images.

Jamie

Jamie

**Comment by SimonLab** [comment]
Thanks @jamieu 

> I think currently there are only a dozen records/images with ML image tags. 
Makes sense that only 42 tags are returned from Elasticsearch at the moment

> it would be preferable to not have to generate any lists (in advance)
At the moment I'm creating the list dynamically by searching all the existing tags in Elasticsearch, so when you add some more they should appears automatically in the list.

**Comment by SimonLab** [comment]
The update to Hapi 18 has broken the links for the image tags. I don't think it's directly linked to Hapi itself but to pagejs:
![image](https://user-images.githubusercontent.com/6057298/54681894-66047a80-4b05-11e9-960a-3e761c64c525.png)

It looks like when clicking on a link, pagejs try to redirect to the page directly on the front end instead of letting the backend loading the page

**Comment by SimonLab** [comment]
similar to what we have done here: https://github.com/TheScienceMuseum/collectionsonline/issues/1194#issuecomment-436588005
We can let `pagejs` know that we don't want it to be applied to the links in the image tags page.
