### ISSUE TITLE
Fix 'Search' page <title>

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1356]
**Update 4/9/2024:** 

Just noticed that we still seem to have the default <title> tag without any filters?

https://collection.sciencemuseumgroup.org.uk/search/places/england
https://collection.sciencemuseumgroup.org.uk/search/categories/art/places/england

--

Fix <title> on search home page site re. google (should show category / museum / object name etc.)

![unnamed](https://user-images.githubusercontent.com/91365/73437268-f1fd4a80-4343-11ea-80f7-cd24e720b820.png)

**Comment by jamieu** [comment]
https://collection.sciencemuseumgroup.org.uk/search/objects/object_type/photograph

Should have 'photograph' in title
<img width="532" alt="Screenshot 2023-12-11 at 15 47 59" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/366c5f4f-2161-42fc-a915-5c4b177303e7">

**Comment by evancp87** [comment]
Fixed and expanded, with more scope for further improvements outlined in [this ticket](https://github.com/TheScienceMuseum/collectionsonline/issues/1738)

**Comment by jamieu** [comment]
Just noticed that we still seem to have the default <title> tag without any filters?

https://collection.sciencemuseumgroup.org.uk/search/objects/categories/photographs
https://collection.sciencemuseumgroup.org.uk/search/places/england

**Comment by jamieu** [comment]
Also..
https://github.com/TheScienceMuseum/collectionsonline/issues/1175

**Comment by evancp87** [comment]
Fixed back in September. This ticket is linked to [this one](https://github.com/TheScienceMuseum/collectionsonline/issues/1738), which remains open for now
