### ISSUE TITLE
Add Facet filter based on content uploaded date.

### ISSUE THREAD

**Issue by kss682** [TheScienceMuseum/collectionsonline#1374]
Currently the filter date filter is based on date in the description , if a filter based on uploaded date can be integrated it would be easier get new contents .

**Comment by jamieu** [comment]
It may seems like an obvious and useful field and one we'd love to add, but we don't have this information available in a consistent form.

While we know the date a record is created or modified in our backend systems at a datable level, the creation date doesn't represent the date the object was acquired into the collection and we are worried this may confuse users. 

Additionally the modification date of a record can also be be altered for any number of reasons, many of which have nothing to do with the public record text or fields being updated.

We are continuing to look at ways to reliable add creation/modification dates, as we know allowing user to see new or updated record would be a useful feature.
