### ISSUE TITLE
Refactor property "place born" for the facet

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#138]
On a people type we have the Place born define on the property `lifecycle.birth.location.name.value` on the agent objects:
![placeborn](https://cloud.githubusercontent.com/assets/6057298/16566914/bf918008-4210-11e6-8264-74239916e669.png)

I think the list of multiple values separated by comma is too precise and doesn't offer a proper filter. Some values can also have some conflicts ("England, United Kingdom" and "United Kingdom"). Should we reindex or create a new property in elasticsearch to be able to build the filter based on single value?

@jamieu do you have an idea concerning this issue?

**Comment by jamieu** [comment]
I am very aware of this issue ;-)

The original plan was to ensure all source collection systems used the Getty Thesaurus of Geographic Names (GTGN), however the work needed to complete this is some way off and currently still only at the planning stage.

My interim solution was to use the Geonames API (or similar) to create a single level location (probably 'populated place' http://www.geonames.org/export/codes.html) plus a lat/long that we stored alongside the main location in the index. However even this is looking increasingly unlikely to happen for launch.

So it would be useful to look/think about what else we could do here, possibly we could just reduce the location down to the first value (for use in the facets).

**Comment by jamieu** [comment]
I think for now the best solution for now might be to limit the place born facet to a list of countries (built against a standard list of countries). 

At least that will keep the facet values consistent for end users.

We can then revisit (post launch) using a nested country -> inhabited place multi level style facet once we have all the source systems using the same GTGN Thesaurus (which is still some way off).
http://www.getty.edu/vow/TGNFullDisplay?find=south+kensington&place=&nation=&prev_page=1&english=Y&subjectid=1100833

**Comment by jamieu** [comment]
One to revisit once the dust had settled, closing for now.

(actually hoping I can get standardisation on a single 'place name thesaurus' in both collection system)
