### ISSUE TITLE
Zoom feature broken

### ISSUE THREAD

**Issue by johnstack** [TheScienceMuseum/collectionsonline#1389]
The zoom feature is not working. Clicking on the image returns either a blank screen or an error message. Clicking on the zoom icon reveals the fullscreen controls in the main page and these are not active.

![ezgif-4-411aadcf19de](https://user-images.githubusercontent.com/1881723/82988331-e1f33000-9ff0-11ea-91ea-273afc27b3bd.gif)

**Comment by jamieu** [comment]
Should be working again now 👍 

(just investigating what caused it to go down)
