### ISSUE TITLE
Number of filters per facets?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#139]
How many filters do we want to display for each facets? Be default elasticsearch will retreive 10 filters. Do we want to keep this number or do we want to display more or as much as possible filters on the page?

**Comment by jamieu** [comment]
Lets leave it at 10 for now for testing, but I think we'll probably want to reduce it down to 6 to 8 at launch.

**Comment by SimonLab** [comment]
ok let's keep to 10 for now
