### ISSUE TITLE
Babel compilation errors

### ISSUE THREAD

**Issue by tobystokes** [TheScienceMuseum/collectionsonline#1422]
I was getting compilation errors with Babel, and had to explicitly add the latest @babel packages:

https://github.com/TheScienceMuseum/collectionsonline/commit/3666491562eebdc7f7d4bc84b9369a827077f851

(Though i'm not sure how it ever transpiled before, if it wasn't a dependency at all... did you have it globally installed??)

If this still works for you, this could be Pr'ed ahead of the other changes for accessibility, which was the real reason for ths branch...

**Comment by jamieu** [comment]
Think this has been resolved, closing for now
