### ISSUE TITLE
unknown maker filter

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#147]
![unknownmaker](https://cloud.githubusercontent.com/assets/6057298/16600512/5cdc6bcc-42ff-11e6-9a9e-b854b123d1ef.png)

Should we delete this filter? We can either clean the elasticsearch database or filter this value on the server side. Any thoughts?

**Comment by jamieu** [comment]
It’s on the list of approved changes to the new index, just waiting for it to be implemented.

**Comment by SimonLab** [comment]
This issue will be resolved with the new elasticsearch index
