### ISSUE TITLE
Toggle Facets without javascript

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#149]
![togglemenu](https://cloud.githubusercontent.com/assets/6057298/16619803/98e52770-4387-11e6-99c2-8e440ff236b3.png)

The Facets are display only by using javascript. So if javascript is not activated the facets won't be displayed.
Should we display automatically the facets when the javascript is disable?

**Comment by jamieu** [comment]
I think that's probably the sensible approach (ie. displayed when JS disabled).

I can't think of any mobile platforms (where showing all the facets by default may cause an issue) where JS would be switched off. The non-JS version is mainly there for SEO reasons.

But do shout if this this looks problematic / causes undue complexity or if you can see a flaw in the above logic.
