### ISSUE TITLE
CO2.0 : Reinstate related articles from Museum sites and blogs

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1497]
Migrate 

Current these are pulled though on the client side (and disable due to performance issues), but we should probably look at loading these feeds into the CIIM overnight and then then adding them to the index/page as static content. 
https://github.com/TheScienceMuseum/collectionsonline/blob/1fef7ee66867d19f1338bbaa614f0a954e8a098b/routes/articles.js#L28

**Comment by evancp87** [comment]
The plan now is to use Redis/Catbox-Redis to cache the related articles, similar to what is done in lib/cached-document. I will look at caching blog endpoints vs individual articles to see which is more efficient, and potentially write a cron job to handle the caching at regular intervals

**Comment by evancp87** [comment]
Completed a while back, but needed some refining in terms of error handling and logs, so only closing off now
