### ISSUE TITLE
Text for citation copy/past widget

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#152]
For the block on the RHS...

Science Museum Group. "Page title.” Inventory number. Science Museum Group Collection Online. Accessed (today’s date). URL.”

* Page title:  object name / person name / document titke
* Inventory number: accession no.
* Today's date: July 06, 2016
* URL: the url of the page

All other text as above including full stops.

**Comment by Danwhy** [comment]
@jamieu 
So for example the cite text for Stephenson's Rocket would be: 
`Science Museum Group. Rocket. 1862-5. Science Museum Group Collection Online. Accessed 12 July 2016. http://localhost:8000/objects/smgc-objects-26704.`?

Also, do we still want the 'Science Museum Group' text and 'Accessed' date above/below the cite text, or should that be deleted? 
<img width="377" alt="screen shot 2016-07-12 at 11 30 31" src="https://cloud.githubusercontent.com/assets/8939909/16764135/57b35154-4824-11e6-996e-f6e00757e15f.png">

**Comment by jamieu** [comment]
1) yes, just like that..

2) yes, delete the 'Science Museum Group' text and 'Accessed' date
above/below the cite text
