### ISSUE TITLE
Make the 'filter open' button disappear when javascript is disabled

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#155]
@Danwhy Could you please add a little screenshot of the button to this comment?

**Comment by Danwhy** [comment]
<img width="302" alt="screen shot 2016-07-12 at 10 27 12" src="https://cloud.githubusercontent.com/assets/8939909/16762165/3f5e8bc2-481b-11e6-9a10-0679b91634e7.png">

**Comment by Danwhy** [comment]
closed with 9d9016d
