### ISSUE TITLE
Filtering on the 'All' tab should cascade the filter to the other tabs

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#156]
As a user, when I filter on the 'all' tab, I expect that filter to carry through to the other tabs (People, Objects and Documents), so the number of total items there will change.

Note: If I filter on just a single tab (People, Objects or Documents), the filtering will be for just that tab and the total number of items in the other filters will not change.

**Comment by SimonLab** [comment]
resolved with #203
