### ISSUE TITLE
CO2.0: Carousel and image broken, when more than one image [critical]

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1574]
Seems to have recently crept in (12th Feb 2024), not where yet was is is related to.

@tobystokes could this be a change you made? (not pointing fingers, just wondering!)

Carousel and image broken, when more than one image, plus multiple zoom icons.
http://localhost:8000/objects/co8227862/eclean-next-generation-bedside-cabinet-cabinet
http://localhost:8000/objects/co409514/apple-newton-messagepad-with-case-pda

<img width="962" alt="Screenshot 2024-02-12 at 15 46 32" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/a81ac2da-07d6-4027-8551-9e6a8b366990">

**Comment by tobystokes** [comment]
thre's a js error `Error: ENOENT: no such file or directory, open './templates/partials/records/record-child-records.html' while parsing file: /Users/toby/Sites/scimus/collectionsonline/client/templates.js` which I think is stopping the js compilation with various side effects.
remove that unused import, and it seems all good. 
i suspect that will fix the other mentioned issues too

**Comment by jamieu** [comment]
Thanks @tobystokes yes that fixed it, and the other two issues ⭐ 

(just fixing a merge conflict and will shortly merge the parentID anchor link and childHasImages stuff into master)
