### ISSUE TITLE
CO2.0: New 'box' on objects page to display which group this record is part of [MG] [Design]

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1627]
Using these values
https://github.com/TheScienceMuseum/collectionsonline/issues/1626

Note: **Most objects WON'T be part of multiple groups** — so we ideally need the design to handle that scenario and not look silly in those cases.

![4776a0f4-05f3-4452-bb50-c7bd455917ed](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/5ec73545-4fa6-4f26-983a-0efc6c979fe4)

**Comment by evancp87** [comment]
New info box implemented. Could do with further styling
