### ISSUE TITLE
CO2.0: Add sub_group filters to RHS facets under 'groups' tab [MG]

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1630]
Needs pulling though and made available as a filter on any search results pages and a facet under the 'Groups' tab. 

(not sure it make sense showing sub-group as facet under main 'All' (search results) tab, but can leave in for now to test/see; probably real only make sense when you select the groups tab).

![fcaa20c4-7515-4958-ab6d-1d0ecdd2c427](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/12a59100-8ca2-448b-b3ca-54b5a249c801)

![14273772-fddd-4830-88d8-4e79b34fba44](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/17b6170b-97da-472f-93c3-d442e3c93447)

**Comment by evancp87** [comment]
This is almost finished, but needs the new sub_group field to be used to filter using a lowercase query. Currently it only works on certain records.

**Comment by jamieu** [comment]
This is now in the index, 

`subgroup.summary_title.lower` (if that doesn't work with an ES term query try `.keyword`).

You'll likely need to add it to (or rather rename `sub_group` in) `attribute.js`

![Unknown-1](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/4f8e84fe-0235-4c51-9249-02865c9f70dc)
![Unknown](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/8a51ffc0-0349-408f-9c67-cfb07fdb46dc)
<img width="530" alt="Screenshot 2024-04-11 at 16 35 53" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/c122035c-40cc-4325-94a0-a880ff681119">

**Comment by evancp87** [comment]
updated to use subgroup.summary.title.lower/keyword in a couple of places
