### ISSUE TITLE
CO2.0: Link to parent record from a DHA photo broken

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1651]
The link to the DHA root/parent record (co205344) from a [child record](http://localhost:8000/objects/co8223504) (co8223504) of the DHA is broken.

Child: http://localhost:8000/objects/co8223504
DHA (parent) http://localhost:8000/objects/co205344

This collection filter / path (which the top level DHA co205344 should redirect to) however does work
https://collection.sciencemuseumgroup.org.uk/search/collection/daily-herald-archive

This is **probably because** the parent record had a [hardcoded redirect (in the code)](https://github.com/TheScienceMuseum/collectionsonline/blob/e36931d3f99c8ba910504f8d5612315a54290024/routes/redirects.js#L23) to the search results page for DHA. 

This is because the DHA parent record is a SPH with thousands of children (and so will never render correctly). But I suspect the child page is failing because of this.

<img width="658" alt="Screenshot 2024-03-11 at 18 46 08" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/234efa3e-9b6b-48d2-8b92-20f693edc993">

<img width="520" alt="Screenshot 2024-03-11 at 18 41 57" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/726f5ca6-8af0-4c73-8ffc-df4d1b2b6edf">

https://github.com/TheScienceMuseum/collectionsonline/blob/e36931d3f99c8ba910504f8d5612315a54290024/routes/redirects.js#L23

**Comment by jamieu** [comment]
This is due to the redirect, Jamie knows...

```
~/projects/collectionsonline/routes/redirects.js:
   21      return {
   22        method: 'GET',
   23:       path: '/objects/co205344/{slug?}',
   24        handler: function (request, h) {
   25          return h.redirect(config.rootUrl + '/search/collection/daily-herald-archive').permanent();

```

**Comment by jamieu** [comment]
Add a rule (and  comment) into the MPH 'parent link code' to point to `/search/collection/daily-herald-archive` as well.

**Comment by evancp87** [comment]
Check added for DHA, with link to the search collections page reassigned if on child record of DHA
