### ISSUE TITLE
CO2.0: Enhancement block missing in new index

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1664]
And along with it the 360's and YouTube videos.

- https://collection.sciencemuseumgroup.org.uk/objects/co8084947/stephensons-rocket-steam-locomotive
- https://collection.sciencemuseumgroup.org.uk/objects/co56970/orrery-made-by-john-rowley-for-the-earl-of-orrery-demonstration-models-orreries-planetaria-models

```
      "enhancement": {
        "web": [
          {
            "id": "smgco-360/58208fbb-a84a-45f3-90d5-9b6f50a297be",
            "platform": "3D",
            "title": "Orrery or planetary model, c. 1712"
          }
        ]
      }
```

```
      "enhancement": {
        "web": [
          {
            "id": "XR4OVtjE3JU",
            "platform": "youtube",
            "title": "How Stephenson's Rocket Changed The World"
          },
          {
            "id": "09d73611eeda4aa7a4f3643766b340da",
            "platform": "sketchfab",
            "title": "Stephenson's Rocket"
          }
        ]
      }

```

<img width="1200" alt="Screenshot 2024-03-15 at 12 14 55" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/9490b8e3-5104-4406-b092-8adf63aa41bf">

<img width="1240" alt="Screenshot 2024-03-15 at 12 08 06" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/b836d312-438e-4b79-997b-ae593fbbc1e0">

**Comment by jamieu** [comment]
KI ticket #5276

**Comment by jamieu** [comment]
Resolved, but need to pull enhancement on child record back top to parent record, potentially in json-to-api.js

**Comment by evancp87** [comment]
This is now complete. If there is no enhancement block on the parent record, but on a child record, that becomes the enhancement block of the parent. If there is both an enhancement block on the parent and children, the child block is merged in with the parent.
