### ISSUE TITLE
CO2.0 : Add web_description to child records

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1665]
Not al record have a web description.

But when they do, display the web description, after the `primary` description with a  `hr`  between them.

On child records only, main record display of them is fine as is.

Like so

```
<div id="description">description</div>
<hr>
<div id="web_description">web description</div>
```

**Comment by jamieu** [comment]
![Unknown](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/58b1b9ad-f93f-4210-aa5b-2e2f640a91ad)

![Unknown-1](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/6e53e0b2-7646-42dd-8536-2a6dd5f6a7bc)

<img width="848" alt="Screenshot 2024-04-10 at 11 55 59" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/48c98093-fce6-4e9c-9e00-d32810026f24">

**Comment by evancp87** [comment]
Implemented, but will need to refined to improve the user experience, such as truncating the text, which there is a function for, but could do with being designed to look nice
