### ISSUE TITLE
Plug in Google Analytics

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#167]
A quick win for this sprint - just drop in the code into the templates (events will be dealt with separately).

**Comment by jamieu** [comment]
GTM code for collection.sciencemuseum.org.uk which is where the live site will live
_(note singular use of collection, not collections plural)_

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MTBKW2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MTBKW2');</script>
<!-- End Google Tag Manager -->
```

**Comment by iteles** [comment]
👍 Thanks @jamieu ! 
We'll have some discrepancies in figures when we work from outside Science Museum/dwyl offices, but shouldn't be too bad.

**Comment by alanshaw** [comment]
For your consideration: https://segment.com/

Allows you to plug in many different integrations (including google analytics). What I think might be useful for SMG would be the heatmaps and recordings, A/B testing and performance monitoring intergrations.

**Comment by SimonLab** [comment]
done with #353
