### ISSUE TITLE
Elasticsearch version upgrade?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#168]
It seems that the current version of Elasticsearch we are using is 1.7.1. 
The current version of Elasticsearch is 2.3. Read the improvement of the version 2 [here](https://www.elastic.co/blog/better-query-execution-coming-elasticsearch-2-0)

The filters queries seem to be more efficient with the recent version. The version also influence how we are going to write some queries as some syntax are only supported for the version 1.7.

@jamieu do you know if there are any plans to update the version?

**Comment by jamieu** [comment]
I see no reason we couldn't, let me investigate

**Comment by jamieu** [comment]
The CIIM platform doesn't support 2.0, it's going to to skip a version and move straight to ES5 once it's out of beta. Which likely rules out using it for the initial launch.

Have opened a ticket here as a reminder that the API and queries will need revisiting when we upgrade, likely not till next year.
https://github.com/TheScienceMuseum/collectionsonline/issues/174
