### ISSUE TITLE
Zooms (IIIF) seems to be loaded on page load (not just on click)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1682]
I spotted this as a result on a config error, but it seem that ass soon as the page load OSD  tries ot load a IIIF zoom. 

Obv we don't want to make calls to the zoom server until we need to.

<img width="747" alt="Screenshot 2024-03-27 at 16 31 14" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/015ba8fd-7b94-4730-9f37-6b2657180ffb">

**Comment by evancp87** [comment]
This seems to have been due to incorrect iif & media links
