### ISSUE TITLE
Priority card flag

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1762]
Set flag on child record, visible in handlebars if...

- CATALOGUE.FLAG8 (priority) is set on ES object record
- Description (primary) > 150 words (may need to tweak)
- If there only one child card 
- Has a 'web description' (but only if one one child has one)

So that we can display a slightly different / multi-column card for the records.

Note: there can be more than one priority card.

Example child record with boost and it's parent (group) record
https://collection.sciencemuseumgroup.org.uk/objects/co8184724
https://collection.sciencemuseumgroup.org.uk/objects/co209218

**Comment by evancp87** [comment]
This has now been implemented
