### ISSUE TITLE
Create an array of images for each group  

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1784]
Create an array of images for each group based on the 1st image of each vccidl record, for use by Toby when building 'group card'.

Always create an array of 9, if less than 9 then loop though and repeat images ie. 1,2,3,4,5,1,2,3,4,5 

<img width="475" alt="Screenshot 2024-06-25 at 14 12 10" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/c1839e2f-e784-4f09-ba0e-b3e943907cae">

**Comment by evancp87** [comment]
This is now complete
