### ISSUE TITLE
Test for related articles hangs tests when run locally

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1807]
<img width="608" alt="Screenshot 2024-08-15 at 14 44 11" src="https://github.com/user-attachments/assets/6d0eedbd-aa1d-43ea-8997-167c30d52cc4">

**Comment by evancp87** [comment]
Fixed - by wrapping the test in a try/catch block. It still takes a moment to finish, but does so in a fraction of the time it did before
