### ISSUE TITLE
Deselecting the last filter in a group cause the 'Refine Search' block to collapse.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#182]
When you deselect the last filter (ie. category below) the whole RHS 'Refine Search' block collapses back down.

1) Deselecting "Computing and data processing"..

<img width="388" alt="screen shot 2016-07-14 at 10 28 31" src="https://cloud.githubusercontent.com/assets/91365/16834911/df758348-49ad-11e6-9090-45163f8e8abb.png">

2) Causes the whole 'Refine Search' block to collapse back down..

<img width="362" alt="screen shot 2016-07-14 at 10 28 35" src="https://cloud.githubusercontent.com/assets/91365/16834913/e24b29e2-49ad-11e6-92a9-7c246faad77d.png">

**Comment by SimonLab** [comment]
resolved with #199
