### ISSUE TITLE
Remove jQuery altogether?

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#183]
We're using jQuery in very few places and the latest release ([version 3.0](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/)) has caused a few issues already #179. 

Given we're not using it much, we should consider whether we would be better off [dropping it altogether](https://browserdiet.com/#dont-use-jquery).

**Comment by tobystokes** [comment]
Are we still aiming for IE9 compatibility? ( @SimonLab / @jamieu  )
I think it was in the original spec, as sadly some 'internal stakeholders' still have it installed.
Only because $ was probably polyfilling a lot of js it doesn't support, though it could be polyfilled on a case-by-case basis.
