### ISSUE TITLE
Twitter cards

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#184]
For people, object and document pages.

https://dev.twitter.com/cards/overview

**Comment by iteles** [comment]
Re-opening this for another check within sprint 10 prior to public launch.

@SimonLab @Danwhy to co-ordinate removing the login wall for an hour with @jamieu in order to test this on Tuesday.

**Comment by jamieu** [comment]
Just need to test this once we have image

**Comment by jamieu** [comment]
Doesn't seem to be validating (even without auth off)
http://collection.sciencemuseum.org.uk/objects/co26704/rocket-locomotive-steam-locomotive

<img width="1064" alt="screen shot 2016-12-02 at 16 03 42" src="https://cloud.githubusercontent.com/assets/91365/20840696/0329fef8-b8a9-11e6-97b2-87c2fda598ca.png">

**Comment by jamieu** [comment]
Looks good 👍
