### ISSUE TITLE
Behaviour of part records in mgroups

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1848]
In the new mgroups we have several cases where a part (aka child) record has been assigned to the mgroup, rather than that part's parent SPHG record. 

Documentation are still discussing if this should be allowed process wise, but there are a number of use-cases where it could be useful. The logic is already 'nearly there' in that we allow part/child records to be member of the group, and the mgroups page displays them as expected using the part/child's thumbnail. 

See the Ford Cortina record on the Hawkin's Grid mgroup page...
https://collection.sciencemuseumgroup.org.uk/group/c83918

However [the link](https://collection.sciencemuseumgroup.org.uk/objects/co8352636/ford-cortina-automatic-car
) [co8352636] doesn't seem to work properly...instead of redirecting you to the parent page (form the group page) you first get an error (/client stuff kicking in?) and it's only the you refresh the URL manually do you get taken the to [parent SPH page](https://collection.sciencemuseumgroup.org.uk/objects/co24522. 
) [co24522].

**Comment by evancp87** [comment]
closing - as this particular one seems to be due to a cloudfront captcha challenge/405 error code. Not 100% sure why it's happening on this specific record at present
