### ISSUE TITLE
Why is part prioritised?

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1852]
Why is part 1990-5037/P80/8 prioritised?
https://collection.sciencemuseumgroup.org.uk/objects/co8399644/stewart-albums

If it's the length of description **that's fine** just need to know the length so we can feed back to documentation.

It doesn't seem to have the manual 'priority' flag set to Y

So why is it being prioritised....?

**Comment by evancp87** [comment]
Closing. Part 1990-5037/P80/8 is prioritised due to its primary description being greater than 100 (116), whereas no other record satisfies any of the criteria to be prioritised, such as being boosted, a single record, or only having a web description.
