### ISSUE TITLE
Only 38 records displayed on SPH page despite 22 direct decedents and 2089 indirect ones.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1853]
Only 38 records displayed on SPH page despite 22 direct decedents and 2089 indirect ones.
https://collection.sciencemuseumgroup.org.uk/objects/co8399644/stewart-albums

Maybe related to 2 level display of child record, but one to check one that is resolved...?
https://github.com/TheScienceMuseum/collectionsonline/issues/1845

<img width="641" alt="Screenshot 2024-10-21 at 12 47 56" src="https://github.com/user-attachments/assets/3041c25c-20c5-468d-994b-805ae88f3e45">

**Comment by evancp87** [comment]
complete - fixed logic error. Note that the CIIM limits child records to 100, which will need to be looked at
