### ISSUE TITLE
isFilter condition on render

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#186]
This [if condition](https://github.com/TheScienceMuseum/collectionsonline/blob/536014e44b762a0be70e277e490c4005994d9171/client/routes/search.js#L39-L42) is just here to define the property isFilterAll( or People/Objects/Documents). But I think this property is already defined in ctx.data. Did I miss an edge case where the property is not defined? Also 
```
var filter = 'isFilter' + ctx.params.type[0].toUpperCase() + ctx.params.type.slice(1);
if (filter !== 'All') ctx.state.data.isFilterAll = false;
```
this if condition doesn't seems to be always right as filter will be at least equal to "isFilter".

Can you confirm @Danwhy that we don't need this part of code, thanks

**Comment by Danwhy** [comment]
The property is defined initially, but it doesn't change on ajax requests, that's what this is for.

You're right about the second line though, it should be `if (filter !== 'isFilterAll') ctx.state.data.isFilterAll = false;`

**Comment by SimonLab** [comment]
I think there are a few issues with the context of the routes. First on the load function I think we are redefining each time the context and that's why I thought the property isFilterAll(peple...) is always defined:
```
  function load (ctx, next) {
    if (!ctx.state.data) {
      var url = ctx.path;
      var opts = {
        headers: { Accept: 'application/vnd.api+json' }
      };
      var qs = QueryString.parse(ctx.querystring);
      Object.keys(qs).forEach(el => {
        if (Array.isArray(qs[el])) {
          qs[el] = qs[el].join();
        }
      });
      var queryParams = createQueryParams('json', {query: qs, params: {}});

      getData(convertUrl(url, 'json'), opts, queryParams, function (data) {
        ctx.state.data = data;
        next();
      });
    } else {
      next();
    }
  }
```

the first condition ```if (!ctx.state.data)``` is always false. If I understand correctly you are doing this condition to not execute the ajax request if the user navigates the history. However to keep the context I think we need to use ctx.save().

**Comment by SimonLab** [comment]
#196 resolved this question and the code is now refactor
