### ISSUE TITLE
Fuzzy part images (where less than three parts)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1864]
Normally we show the parts with (large) [thumbnail sized images](https://coimages.sciencemuseumgroup.org.uk/232/53/large_thumbnail_d051097.jpg), but where we have only one or two images the part images are rendered larger and hence the thumbnail sized images are stretched to the point they become fuzzy.
https://collection.sciencemuseumgroup.org.uk/objects/co8064677

To fix we need to add logic to json-to-html (or the handlebars template itself) that uses the full size images for the part records, if there are less than three images.

**Comment by evancp87** [comment]
Complete
