### ISSUE TITLE
bakslash to forwardslash

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#190]
![backslash](https://cloud.githubusercontent.com/assets/6057298/16881885/2bb687f0-4ab4-11e6-9fc9-bb4e76bb6784.png)

Query parameters with backslash are converted to a forwardslash?!
This is an issue for our json api as we are encode commas inside a value with a backslash.

Do anyone as an idea why this is happening?

**Comment by SimonLab** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=748140

**Comment by SimonLab** [comment]
One solution is to encode the backslash for example "hello\, there" become "hello%5C%2C". To do that we can use encodeURIComponent but we need also need to escape the backslash:

```
encodeURIComponent('hello\\, there')
```

This means that people will need to be careful when they use the api with some comma in the values and they will need to encode the backslash which is a bit less user friendly but it will work

**Comment by nelsonic** [comment]
@SimonLab agreed, this would be un-user-friendly... when/why is backslash being used?

**Comment by SimonLab** [comment]
We are using a backslash to distinguish commas that separate values and value containing commas:
JSONAPI format build the request by separated values with comma ```/search?q=ada&filter[location]=London,Paris```. Here we are searching for the keyword ada with the values London and Paris in the filter location. However some values can contain some comma for example "London, UK". In this case we don't want to search for London and UK but London, UK. So to distinguish these two cases we are escaping the comma like this ```/search?q=ada&filter[location]=london\,UK``` and  we have a bunch of function to manage these cases on the backend.

**Comment by SimonLab** [comment]
#196 resolve this issue by encoding the url. By default page.js decode automatically the url but there is an option where you can precise how to handle the url. As we are manipulating the url for the facets we have disable the option.
