### ISSUE TITLE
Pagination is slightly broken

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#197]
1) First page is fine, second page has overly long, wrapping pagination.
`/search?q=John%20Dalton&page%5Bnumber%5D=1`

<img width="1210" alt="screen shot 2016-07-18 at 17 18 49" src="https://cloud.githubusercontent.com/assets/91365/16922021/dd96f4f6-4d0b-11e6-9df4-2a3bea96371f.png">

2) A single page of results doesn't need pagination,
`/search?q=Ada%20Lovelace`

<img width="307" alt="screen shot 2016-07-18 at 17 18 31" src="https://cloud.githubusercontent.com/assets/91365/16922025/e37d9a96-4d0b-11e6-82e9-e376804ed8f6.png">

**Comment by SimonLab** [comment]
on the ajax request we are building manually the queryParams object which represent the url. Without ajax Joi validates the values and convert them to the right type. One solution is to use Joi on the frontend  , the other solution is to convert manually the value to right type format

**Comment by SimonLab** [comment]
resolved with #201
