### ISSUE TITLE
Joi validation on front-end

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#198]
Should we use Joi to validate or parameters for our ajax request. Joi also convert some data to some specific type. For example it will convert a year to a date format. So before our ajax request we need to convert manually the year to the type date to keep a the same logic for all the requests.

@Danwhy @nelsonic do you see any inconvenience to use Joi on the front-end. It will add some weight, we just need to know how much and otherwise should we continue to do the type conversion manually?

**Comment by nelsonic** [comment]
@SimonLab can you write a small usage example or link to one? (_agree in principal_)

**Comment by SimonLab** [comment]
we keep the validation on the backend and make sure that our json requests have the right format.
