### ISSUE TITLE
Pretty format 'status' field.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#200]
Jamie to supply list

<img width="470" alt="screen shot 2016-07-20 at 11 07 19" src="https://cloud.githubusercontent.com/assets/91365/16982976/a19c9144-4e6a-11e6-8010-6ccda25c2789.png">

**Comment by jamieu** [comment]
We may need to implement some stop words for this field.

**Comment by jamieu** [comment]
@emilyfildes are you happy with these values 'as is' out should we prettify them?

**Comment by emilyfildes** [comment]
@jamieu I think we should prettyify them (not least because Wellcome Trust is an actual name).

How about:

permanent collection = Permanent collection
loan: wellcome trust = Loan: Wellcome Trust
loans: historic and loan = Loan (ie group both of these categories together)

Thanks!

**Comment by jamieu** [comment]
👍
