### ISSUE TITLE
Implement 'list' view

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#204]
Design for this should have been pulled over from codesign

<img width="413" alt="screen shot 2016-07-21 at 15 10 55" src="https://cloud.githubusercontent.com/assets/91365/17025805/77a4b45c-4f55-11e6-905c-d28f35a1796f.png">

**Comment by SimonLab** [comment]
see #214

**Comment by SimonLab** [comment]
resolved with #220
