### ISSUE TITLE
Decide on what related objects should be 

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#205]
@jamieu As per our catch up this morning, please let us know when you have decided what related objects at the bottom of a page should be.

Linked to #163.

**Comment by jamieu** [comment]
https://github.com/TheScienceMuseum/collectionsonline/issues/271

**Comment by jamieu** [comment]
Updated the logic on https://github.com/TheScienceMuseum/collectionsonline/issues/271
