### ISSUE TITLE
Implement links to SSPL

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#210]
For buy a 'print' and 'licence image' buttons

**Comment by Danwhy** [comment]
Is it just the [homepage](http://www.scienceandsociety.co.uk/) we want to link to for now? Will we link to the specific images when we have them available?

**Comment by jamieu** [comment]
It will link through via the 'use image' link on the object pages.

**Comment by jamieu** [comment]
via accession no.

Will work out the format of link for you.

**Comment by jamieu** [comment]
Will be similar to

http://www.scienceandsociety.co.uk/results.asp?image=10319096&itemw=4&itemf=0001&itemstep=1&itemx=11
