### ISSUE TITLE
Implement initial relevance methods

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#213]
https://github.com/TheScienceMuseum/collectionsonline/wiki/Ordering-and-relevance

* [ ] Synonyms #217 
* [ ] Ordering Importance #218 
* [ ] Boosting #215 
* [ ] Precision #216

**Comment by SimonLab** [comment]
feedback from Emily:
![relevance](https://cloud.githubusercontent.com/assets/6057298/17663048/8e01bf20-62e1-11e6-8763-b9419c1b0425.png)
