### ISSUE TITLE
Facets: [X] should clear filters for that facet

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#219]
We're probably going to tweak the design of these, but the ability to clear each set of filters will remain, so no harm in implementing it now. btw. its the [X] that should clear the filters.

<img width="344" alt="screen shot 2016-07-27 at 13 13 29" src="https://cloud.githubusercontent.com/assets/91365/17174810/fe42e808-53fb-11e6-8bc6-a88a92486edb.png">

**Comment by SimonLab** [comment]
resolved with #223
