### ISSUE TITLE
Not display page numbers on one page result

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#225]
![pagenumber](https://cloud.githubusercontent.com/assets/6057298/17291861/353e96c8-57de-11e6-9f45-ad91f8f8dc82.png)

**Comment by jamieu** [comment]
I can't actually find a search to test this with, but remember you showing it to be so going to close this off on the strength of that :-) Will re-open if I spot any issues.

**Comment by SimonLab** [comment]
@jamieu you can search for "ada" on the people category
