### ISSUE TITLE
Search Results : Add date/category to "list view" on a second line

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#233]
As per the main object / people / doc results view.

<img width="768" alt="screen shot 2016-08-02 at 13 56 52" src="https://cloud.githubusercontent.com/assets/91365/17329218/9228dbd8-58b9-11e6-9fc2-00fe90102145.png">

**Comment by SimonLab** [comment]
![info-list-view](https://cloud.githubusercontent.com/assets/6057298/17395825/3fe93302-5a28-11e6-8418-dd07938d8c78.png)
@jamieu is this version ok or more css need to be added?

**Comment by SimonLab** [comment]
@jamieu the PR for this issue is now merged and the new version should be online soon. Do you mind to test it and close this issue when you think it's resolved, thanks.

**Comment by jamieu** [comment]
Looks good 

I just opened a separate issue #279 as we have now decided that we need the description in there too
