### ISSUE TITLE
Facets : Add museum (if on display) and image licence (if an image) to facets

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#234]
Not sure if these are already in the code and just simply not displaying as we don't yet have images and correct locations in the index.

**Comment by SimonLab** [comment]
![info-list-view](https://cloud.githubusercontent.com/assets/6057298/17395792/1bc2317c-5a28-11e6-8879-db189ac25200.png)

@jamieu is this version good or more css need to be added?

**Comment by jamieu** [comment]
LGTM

**Comment by iteles** [comment]
@SimonLab To review in this sprint and see if any index changes are needed 👍

**Comment by jamieu** [comment]
Closing as I think this is covered elsewhere
