### ISSUE TITLE
Archive browser : Archive only expands one level deep

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#236]
The BAB archive should have more nested levels..

<img width="1122" alt="screen shot 2016-08-02 at 14 09 30" src="https://cloud.githubusercontent.com/assets/91365/17329609/5236fe36-58bb-11e6-9fb2-75d2fd54c45d.png">

**Comment by Danwhy** [comment]
At the moment, I'm fetching the children of any archive that has a level of 'fonds' or 'series'. Some of the archives in the babbage papers have children, but their level is 'item'. Is this a mistake in the data that's going to be fixed?

The only other way to know if archives have children is to search the database for any document that has it as a parent, which would be a lot of requests. I could only make the request when a user clicks to expand it, but that would mean showing a '+' for all archives, even if they have no children

**Comment by jamieu** [comment]
I think that makes sense - run the query when a user clicks the + button

re. items having children, the 'level' name should probably be displayed but ignored (for the purpose of logic). I imagine this is a error, but in a document archive the 'level name' has less meaning than it may do in other classification systems..

btw. do you have a good example where an item has children? If so I'll flag it up with the Archivists - as it's almost certainly wrong.

**Comment by Danwhy** [comment]
[smga-archive-110000105](http://localhost:8000/documents/smga-documents-110000105) is listed as as item but has four children
