### ISSUE TITLE
API links : be nice if we could make these return the actual API response for the page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#240]
Still deciding on the best way to handle these:
- One route might be to have a fairly basic 'proxy page' that routs the API call via a 'proxy page that showed the API URL being call, the header that is set (Accept: application/vnd.api+json) and the response (in a formatted code block/style).
- Another might be to allow an file extension ie. .json (that does the same as setting an accepts header), although that feels like it might introduce confusion (are we using a file extension or an accept header).
- I think we may be able to get some browsers to set the Accepts header when the user clicks the link (but that might be non-transparent and unhelpful voodoo).

The first seems like quite a nice route as it allows us to add more info about the API, but open to suggestions...

<img width="397" alt="screen shot 2016-08-02 at 14 32 24" src="https://cloud.githubusercontent.com/assets/91365/17330246/fd84d3e2-58bd-11e6-9fb8-b57e774ac7f6.png">

**Comment by SimonLab** [comment]
I see this feature linked to another endpoint for example /download/json/smgc-people-38764 which will trigger the api functions that we have already and convert the data if needed to the right format.
Maybe we should select some specific fields to return for the csv and rdf format otherwise I'm afraid the file will look a bit messy as the data contains a lot of fields, but we can try with all the fields first

**Comment by jamieu** [comment]
Just to clarify, I'm not suggesting we re-write the output of the current API - simply that we give (interested users) a way to quickly see the output without having to set a Accepts header (obv. when coding against the API that is far simpler).

The CSV (particularly) and RDF formats will almost certainly contain a sub-set of fields. But I think those probably need separate issues/tasks in GitHub (at least in terms of work) so that this issue remains about giving interested users browsing the site an easy way to see what the response of a real API call looks like.

I've got a couple of ideas here so maybe easier to discuss in person with a pad of paper and then put the outcome here.

**Comment by jamieu** [comment]
Working, bar the issue (https://github.com/TheScienceMuseum/collectionsonline/issues/562) of Safari downloading the response / taking your to a 404 page.
