### ISSUE TITLE
Design : re-visit home page design

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#245]
Functionally it's fine and design wise it's 'fine'.

But thinking that it would be good to divert some addition design effort here if we have time.

**Comment by tobystokes** [comment]
![artboard](https://cloud.githubusercontent.com/assets/109024/19360190/660098c6-9175-11e6-9beb-2c273dfb5880.jpg)

Whilst I am revisiting this, we might as well add in the actual images/copy for the linked collections and museums?

**Comment by jamieu** [comment]
💯 👍
