### ISSUE TITLE
Missing icon for related people?

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#250]
We did have this in codesign seems to have gone astray in the move...

<img width="370" alt="screen shot 2016-08-03 at 14 56 03" src="https://cloud.githubusercontent.com/assets/91365/17368055/6e3af338-598a-11e6-8f09-f5fc9ceb4ad0.png">

**Comment by SimonLab** [comment]
I try to find the icon on the previous design version but couldn't find it either. @tobystokes do you know if the icon was implemented before the we moved the templates? @jamieu do you know what was the icon?

**Comment by jamieu** [comment]
Let me see if I have a copy somewhere (maybe I am imagining that there was
one!)

**Comment by jamieu** [comment]
Seems to be appearing now? Did you change something?

<img width="225" alt="screen shot 2016-08-04 at 14 45 03" src="https://cloud.githubusercontent.com/assets/91365/17404019/3341f6c8-5a52-11e6-9c2f-fcb0353676e1.png">

**Comment by jamieu** [comment]
Ah the problem is on the people page, the object pages is fine.

(so basically use the same icon on the related people on the people page)

**Comment by jamieu** [comment]
Related people on People page: 👎 
Related people on Object page: 👍 

<img width="422" alt="screen shot 2016-08-04 at 14 48 08" src="https://cloud.githubusercontent.com/assets/91365/17404123/96e2fd80-5a52-11e6-9852-8e0f4d201158.png">

**Comment by SimonLab** [comment]
![relatedpeopleicon](https://cloud.githubusercontent.com/assets/6057298/17408813/94d29dd6-5a64-11e6-80b2-9284092d976b.png)

**Comment by SimonLab** [comment]
@jamieu the new version will be on the staging area soon, let us know your feedback, thanks.

**Comment by Danwhy** [comment]
@simonlab I think you've used the wrong icon, that's why it's grey. You should have used person.svg rather than people.svg

**Comment by SimonLab** [comment]
@Danwhy I'm not sure the person.svg file still exists, I have a 404 when I try to load it, maybe I delete the image by mistake. Do you manage to load this file?

**Comment by Danwhy** [comment]
@jamieu @simonlab It does load for me. In fact it was loading anyway, as the icon is provided in the css, so it doesn't need to be in the HTML. I think you both must just be missing the icons.

It looks like the images have been deleted from the client folder for some reason. I still have them locally so I'll make a PR to fix it.

**Comment by SimonLab** [comment]
Thanks @Danwhy well spotted!

**Comment by jamieu** [comment]
Looks good, closing issue
