### ISSUE TITLE
/undefined/ appearing in paths?

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#254]
This may be my local setup / a missing config or root param (so apologies in advance)

But when I run the site locally I am getting **/undefined/** in my paths to people (and hence a error page)
/objects/undefined/people/smgc-people-132685

I used this as a test...
/objects/smgc-objects-8232360

<img width="423" alt="screen shot 2016-08-04 at 14 50 59" src="https://cloud.githubusercontent.com/assets/91365/17404265/fdad0ede-5a52-11e6-9292-ff9dffb81d40.png">

**Comment by SimonLab** [comment]
@jamieu I'm on the page /objects/smgc-objects-8232360 but I don't have any related people displayed so I can't debug the issue at the moment. I'm not sure if I have the right page or it it's another bug. Can you confirm that the links of the related people are broken on the object page /objects/smgc-objects-8232360, thanks

**Comment by jamieu** [comment]
OK this is odd, if I search for "Next Cube" locally and click though I see a related person link.

<img width="1114" alt="screen shot 2016-08-04 at 15 23 50" src="https://cloud.githubusercontent.com/assets/91365/17405509/ac10f680-5a57-11e6-974a-6d9d6ade36e6.png">

But if I reload that page (locally) I don't see it..I don't see it either way on staging?

I can only imagine this is some odd caching (although I think the Next cube should have Next as a related person).

What is off is that object (smgc-object-8232360) does have NeXT as a maker..

`
{
    "query": {
        "match": { "identifier.value": "L2014-4158" }
    }
}
`


`
],
"maker": [{
    "@link": {
        "role": [{
            "value": "maker"
        }],
        "type": "reference"
    },
    "admin": {
        "id": "agent-132685",
        "uid": "smgc-agent-132685"
    },
    "summary_title": "NeXT"
}],
`
