### ISSUE TITLE
Archive tree: Plus sign

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#256]
All documents have a plus sign next to them, regardless of whether or not they have children. It would be nice to have a dot for those that have no children. 

Best way of doing this would be using the 'level' field in the database, if it displays the correct value of 'series' or 'fond' for those with children, and 'item' for those without. Will have to find another way if this doesn't happen though.

**Comment by jamieu** [comment]
> Best way of doing this would be using the 'level' field in the database, if it displays the correct value of 'series' or 'fond' 

Unfortunately that won't work as a series or folder can also be a final/leaf node.

**Comment by Danwhy** [comment]
Ok, will require a bit of thought to do this efficiently, but shouldn't be too much of a problem

**Comment by jamieu** [comment]
Although your right, we shouldn't have an item containing a folder or a series containing a fonds (the nesting / order should be consistent). That I can ask to be cleaned up.
