### ISSUE TITLE
update meta tags

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#260]
Update the values of the meta tags when an ajax requet is executed

**Comment by SimonLab** [comment]
The meta tags are used for twitter, the idea was to update these tags when an ajax request is  send but twitter is not using any ajax request so it will have the right data.

**Comment by jamieu** [comment]
@SimonLab Can I close this?

We only need the twitter cards for the actual node pages, not the SERPS page (that would be more of a 'nice to have' ie. show a Twitter card for a 'canned search').

**Comment by SimonLab** [comment]
@jamieu yes this issue can be close. We can create a new issue "feature idea" for having a twitter card for the search page
