### ISSUE TITLE
Need to be able to search for accession numbers (object numbers)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#264]
This will be what the curators look for, exact or substring (if poss.) ie. 8001-903 matches 8001-903/3 (with the the exact match turning up first).

**Comment by SimonLab** [comment]
@jamieu are accession numbers following a specific format? We could determine if a user is searching for an accession number if the term searched match a specific pattern but I'm not sure it's possible.
A first simple version is to search on the field "identifier.value" of the objects. This field is not analyzed in elasticsearch so to find the right object the user needs to search with the precise access number

**Comment by jamieu** [comment]
Yes and no, the majority do follow a pattern but there is no rule to say they have to. The top levels of the archive are particular problematic (ie. ROB and BAB) as they only contain chars.

- 1862-5
- 2008-5019
- 2008-5019/5
- POL/1/57 Pt2
- L2014-4158
- BAB/K/062
- BAB

In human language terms...
- A mix of digits (<5) and letters  (<5), with no spaces (fairly high likelihood)
- The above separated or containing slashes, dashes or underscores (high likelihood)
- Any of the above followed by PT1, Pt2, Pt 2 (ie. PT followed by a digit, with or without a single space) (high likelihood)

_Note: archives can contain a highly nested set of /letters/numbers/numbers/letters ie. - BAB/1/2/A/B/6/7/90/BB (not a real identifier)._

**In terms of the index, we can certainly get the analyser changed.**

**Comment by SimonLab** [comment]
first version done with #293
