### ISSUE TITLE
Odd counts being returned

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#265]
Some of the counts are coming back with unusual responses (e.g. Search “Rocket” and filter by poster, count increases from 16 to 17); (e.g. Search “Computer” and filter by analogue, count increases from 10 to 11).

Is this an issue with the logic or ES sharding?

**Comment by SimonLab** [comment]
I think it's an issue with ES sharding, I'm investigating if there are any logs or errors:
see #137

**Comment by jamieu** [comment]
Not seeing this anymore, so closing issue.
