### ISSUE TITLE
Date filter : People not being returned correctly on dates

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#269]
We should return someone if their lifespan (born <--> died) overlaps with the dates searched for.

```
         Born|------------|Died
                   SD|------------|ED
     SD|------------|ED
                   SD|----|ED
                      |ED (single)
                      |SD (single)
```

SD| start search date
ED| end search date

Also include the date they were born/died in the match.

![dates - people 2](https://cloud.githubusercontent.com/assets/91365/17436540/98ae6c2c-5b0f-11e6-92eb-1e6e19ab7546.png)
![dates - people 1](https://cloud.githubusercontent.com/assets/91365/17436539/98ab9fec-5b0f-11e6-99a4-643fd673720d.png)

**Comment by SimonLab** [comment]
resolved with #283
