### ISSUE TITLE
Filters: Add new filter for Image Licence

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#275]
This will be a list of "Creative Commons licenses" and an entry for "Commercial licence" which is everything else (owned by the science museum).

Obv. dependent on having this info in the index.

**Creative Commons license** are likely to be 'media records' where the 'usage' field contains:

- CC-BY-NC-SA 2.0
- CC BY-NC-SA 4.0

**SMG Commercial license**

- Will be any image where the 'copyright' field is "The Board of Trustees of the Science Museum" but the 'usage' field doesn't contain a Creative Commons licence.

**Commercial licence**

- Will be any image where the 'usage' field doesn't contain a Creative Commons licence and the image isn't copyright "The Board of Trustees of the Science Museum" 

---------

The above fields and values will all need to be re-checked and agreed once we have 'media records' in the index.

@jamieu to supply final text and rules for Commercial licence and SMG Commercially license (need to check with legal/photo desk re. the final decision here).

**Comment by SimonLab** [comment]
The index contains at the moment 6 items with the image licence property. The licence information is stored on the property "multimedia.source.legal.rights" and there are two values "detail" and "usage_terms": 
```
smgc-object-8362729
[ { details: 'Public domain; contact Science Society Picture Library for commercial usage.',
    usage_terms: 'Public domain; contact Science Society Picture Library for commercial usage.' } ]

smgc-object-18360
[ { details: 'National Media Museum',
    usage_terms: 'National Media Museum' } ]

smgc-object-8363630
[ { details: 'National Media Museum, Bradford',
    usage_terms: 'National Media Museum, Bradford' } ]

smgc-object-8206167
[ { details: 'Public domain; contact Science Society Picture Library for commercial usage.',
    usage_terms: 'Public domain; contact Science Society Picture Library for commercial usage.' } ]

smgc-object-8229027
[ { details: 'National Media Museum',
    usage_terms: 'National Media Museum' } ]

smgc-object-8428908
[ { details: 'National Media Museum',
    usage_terms: 'National Media Museum' } ]
```

So at the moment it doesn't seems that there are any Creative Commons license values. @jamieu do you know if the usage_terms wil contain the two values:
- CC-BY-NC-SA 2.0
- CC BY-NC-SA 4.0
or is there a new value which will determine if the image licence is create commons?

Also is the value "National Media Museum" match a Commercial licence or the SMG Commercial licence?

body of the search request used to get those values:

```
{
  query: {
    bool: {
      must: [
        {match_all: {}},
      ],
      filter: {
        exists: {field: 'multimedia.source.legal'}
      }
    }
  }
}
```

**Comment by iteles** [comment]
@SimonLab To review in this sprint and see if any index changes are needed 👍

**Comment by jamieu** [comment]
Need to check once images are in, but one thing to note is that we'll also want an 'Any option" ie.

**Image Licence**
[ ] - any
[ ] - commercial
[ ] - non-commercial (CC)
