### ISSUE TITLE
Image zoom : Add open sea-dragon buttons for +/- and full screen

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#278]
- [x] Need to pick icon ( @tobystokes )
- [x] Need to swap out standard OSD icons and place them under the new icons.
- [ ] True OSD full-screen needs icons too (need to find nice placement)
- [ ] Ensure they work on mobile viewports

Couple of points:

- true full screen icon needs to differentiate from "full to browser window" icon [should we enable the <> and >< icons with text?]
- extra icons should only display in zoom mode.
- mockup below is intentionally rough (need to pick good icons!)
- do we want to move the 'zoom' icons along so they separate from the open/close zoom icon?

<img width="845" alt="screen shot 2016-08-08 at 14 14 33" src="https://cloud.githubusercontent.com/assets/91365/17481129/38be3728-5d73-11e6-9a89-d09215647385.png">

**Comment by tobystokes** [comment]
template was already done, see
https://github.com/TheScienceMuseum/collectionsonline/blob/master/templates/partials/records/record-imgpanel__controlbar.html#L24-L31

(but I expect that old `{{if osd}}` needs replacing)

I would say that EITHER the fullscreen OSD zoom button OR our standard full browser-height zoom button be available, but not both. Though there is not a lot of height difference in it, so no strong opinions on which one, and the same icon could be used for either

**Comment by jamieu** [comment]
What's your thoughts on making it clear that there are effectively two
levels of zoom?

- zoom to browser window
- zoom to (true) full screen

**Comment by tobystokes** [comment]
Don't have two levels, it's confusing.
Either stick with the standard zoom and hide the OSD one, or vice versa. but they do the same thing, practically.

**Comment by jamieu** [comment]
Just to clarify I mean the really full-screen (outside the browser) full
screen.

But yes, maybe we should just jump straight to that and skip the
intermediate one. Maybe that's what you mean?
