### ISSUE TITLE
List view : add description text

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#279]
Decision made: let's show up to 2 lines of description text (2/3rd's of the way across page, so that it look neat). Truncated on a word boundary with three eclipses ... if longer.

<img width="798" alt="screen shot 2016-08-08 at 14 25 05" src="https://cloud.githubusercontent.com/assets/91365/17481246/f65c3bc2-5d73-11e6-8029-064867f6bbc2.png">

**Comment by SimonLab** [comment]
@jamieu do you also want to display the description on the mobile version or it will be too much information?

**Comment by jamieu** [comment]
Good point, maybe add it in and see how it looks.

(sorry I know that's not a very strong decision!)

Jamie

**Comment by alanshaw** [comment]
@SimonLab is complete now? Please close if true

**Comment by jamieu** [comment]
Looks good, closing
