### ISSUE TITLE
replace filtered query by a bool query

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#289]
The [search query](https://github.com/TheScienceMuseum/collectionsonline/blob/3a7d823865492a98d178327f2a42cbcb019181e7/lib/search.js#L25) use a filtered query which is [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html) on the version 2 of Elasticsearch:

 `Use the bool query instead with a must clause for the query and a filter clause for the filter.`

The query needs to be replaced by a [bool query]()

see #174

**Comment by alanshaw** [comment]
@SimonLab this looks to be done - can close?
