### ISSUE TITLE
Add sitemap.xml

### ISSUE THREAD

**Issue by alanshaw** [TheScienceMuseum/collectionsonline#299]
Context:

> Just an idea for your consideration. We only have so much time to refine and tweak the search to be as good as it can be. I think we'll do an awesome job of this, but it's only going to benefit the people who actually come to the Science Museum website and use the search. Ideally we want exposure to as many people as possible so that it is a massive success! If we can ensure that every single result is indexable by search engines then we're going to get many many more people using the service and as a side effect, leverage the power of huge companies search engines that tailor search for people as their main focus.
> 
> Right now, as far as search engines are concerned, the site is just a home page, and a few links to canned searches and their results. At a minimum we should be generating a `sitemap.xml` every day(?) to tell Google, Bing and Yahoo that there are other pages available on the site for them to index (https://en.wikipedia.org/wiki/Sitemaps).

Jamie also suggested adding an ["image sitemap.xml"](https://support.google.com/webmasters/answer/178636) with appropriate title, caption and licence info.

It would be nice if it was created as a separate process to the server (so that it doesn't affect response times). It sounds like something an AWS lambda running on a cron might be able to do. It could be saved to an S3 bucket and the web server would simply proxy `/sitemap.xml` to the bucket.

**Comment by nelsonic** [comment]
@alanshaw sounds like a good plan. 
to be clear the benefit to end-users is that pages/images will be indexed by Google and thus more "*discoverable*". or are we expecting people to *view* the sitemap and use it for site navigation?

**Comment by alanshaw** [comment]
Yes, the former. XML is not for users ;)

**Comment by jamieu** [comment]
All sounds good, related/unrelated but we should ensure we have Schema.org markup for Object and people (issue open here #185) so that when the pages are scraped they have some semantics (above just the HTML structure)
