### ISSUE TITLE
Archive: archive browser Leaf nodes (ie. the final pages) should not have a + 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#311]
Leaf nodes (ie. the final pages) should not have a + 

(might need @tobystokes to come back with a design tweak)

<img width="1162" alt="screen shot 2016-08-17 at 12 49 51" src="https://cloud.githubusercontent.com/assets/91365/17735259/1c2fba16-6479-11e6-9090-0ed69430f1fb.png">

**Comment by Danwhy** [comment]
linked to #256

**Comment by tobystokes** [comment]
Yep I think that's what @Danwhy means by #256
The original template changed icon with these selectors:
https://github.com/TheScienceMuseum/collectionsonline/blob/master/client/styles/components/_archive-tree.scss#L47-L55
i.e. it's hoping for `button[disabled]` for a non-expandable node. That selector could be changed though if it's not convenient to output.

**Comment by iteles** [comment]
Need an estimate on this before we decide which sprint it fits into please @Danwhy @SimonLab

**Comment by Danwhy** [comment]
So my proposed solution to this is to add `button[disabled]` to all of the documents that have a level value of `item` in the database.

The only problems are:
1. there are some documents marked as `items` when they do have children, which I'm pretty sure is an error with the data
2. there are some archives that have no children

For now I'm planning to add a list of exceptions, which will prevent/force the disabled class if needed, but ideally problem 1 will be corrected in future indexes. As for problem 2, maybe we could have a flag added to the data saying it has no children? Otherwise the exception list may have to do until we can come up with a better solution that doesn't require hundreds of requests.

@jamieu any thoughts/objections?

**Comment by nelsonic** [comment]
@Danwhy sounds like a sensible solution given the _interesting_ data you have identified. 👍 
(_plenty of code comments please and link to this issue in the first comment: https://git.io/vileu ..._)

@jamieu can you think of an _alternative_ approach?

**Comment by jamieu** [comment]
The problem is that a 'folder' or 'series' or 'sub-series' could also be a
final 'leaf' node without children. And although we don't do it in
our archive structure currently, in theory a 'item' could be split into
sub-items.

Be good to get some examples (I know you flagged up some previously) of
'items' with folders or series below them - as that IS bad data.

We could live with 'items' indicating a final node, based on how data is
currently catalogued. In other words if the alternative is running 100
queries every time the page loads that would seem like a sensible solution
/ optimisation (that we could revisit if items are split further in the
future).

But we absolutely do need to deal with archives (fonds), series,
sub-series, folders etc. without children.

Dies that a see the question / make sense?

**Comment by Danwhy** [comment]
Yeah that makes sense. I can write a script to find those folders, series and sub-series that have children and then maybe we could cache those results so we don't have to make the requests.

@jamieu what do you think about setting up an elasticache redis? We could then use that for https://github.com/TheScienceMuseum/collectionsonline/issues/339 as well

**Comment by jamieu** [comment]
Yes, it's looking like having a central (Redis) cache would prove useful
(both now and in the future).

More than happy to set that up, my only one (small) concern is that we
don't go down the rabbit hole of premature-optimisation too early and waste
days/weeks on it. On the other hand I'd rather we did things properly from
the outset (and a central cache is looking increasingly like something that
would be a useful tool in the arsenal). So in summary, happy to setup
Redis/Elasticache and for us to start using it, but lets try and keep the
focus on features over the 'worlds most beautifully designed caching
platform' ;-)

**Comment by jamieu** [comment]
Also, if we use Elasticache/Redis can we ensure that any code using it
fails graceful if for some reason it falls over or someone changes a
network setting.

I'm thinking about technical dept (or rather striving for architectural
simplicity) a year or so down the line when development may have slowed
down and people have moved on. Obviously documentation goes along way here,
but every extra piece of the puzzle (architecture wise) is another piece of
information we need to ensure is passed on. Some voodoo magic in the corner
(cool as it might be now) is likely to be the first to get overlooked until
it breaks and if it does break I'd rather it doesn't take the whole site
down with it. Which reminds me, we should probably look at setting up some
monitoring that can be easily passed on in future!

**Comment by jamieu** [comment]
Just though, actually I noted it down yesterday. Can we completely suppress the whole 'Archive browser' block on pages where there are no children, it serves no real purpose in those scenarios.

Thanks

Have opened a separate issue here...
https://github.com/TheScienceMuseum/collectionsonline/issues/363

**Comment by jamieu** [comment]
Also, and this may just be the data / bad cataloging, but these two parts of the same archive seem disconnected? My guess is this is all related to the stuff your working on, hence why I'm tacking it on here..
https://github.com/TheScienceMuseum/collectionsonline/issues/364
