### ISSUE TITLE
Swap out typeahead.js to remove jQuery

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#328]
typeahead.js is currently in use in the autocomplete functionality but it has a dependency on jQuery.

When we strip out jQuery, we should swap out typeahead.js for a non-jQuery solution. @alanshaw has suggested the small http://complete-ly.appspot.com/

**Comment by SimonLab** [comment]
complete.ly doesn't seem to be maintained anymore and the UI is very basic. We talked about using http://leaverou.github.io/awesomplete/ and I think we could manage to find a way to update the list of suggestions with some ajax request like with typeahead:

```

var input = document.getElementById("myinput");
var awesomplete = new Awesomplete(input);

/*ajax requrest to get the new list of suggestions */

awesomplete.list = ["Ada", "Java", "JavaScript", "Brainfuck", "LOLCODE", "Node.js", "Ruby on Rails"];
```
So I'm investigating awesomplete and will see if it matched our needs.

**Comment by SimonLab** [comment]
So awesomeplete is working quiet well and is currently [maintained](https://github.com/LeaVerou/awesomplete) and up to date. The only question was to know if it was possible to update the list of suggestion to update the autocomplete list dynamically when a user start searching. We manage to do this just by updating the property list of awsomplete with the result of the autocomplete ajax request: see [this code](https://github.com/TheScienceMuseum/collectionsonline/blob/263e8bace3c1e5c4e0c4ee47f768c62097b5c297/client/lib/search-box.js#L13-L33)

**Comment by SimonLab** [comment]
done with #347
