### ISSUE TITLE
SEO-friendly URLs

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#329]
Improving the slug by adding a `/name-of-thing-on-this-page` to the URLs.

**Comment by iteles** [comment]
Milestone cleared as time moved out of this sprint and into future sprints.

**Comment by SimonLab** [comment]
Need to change the urls of the [sitemap](https://github.com/TheScienceMuseum/collectionsonline-sitemap/blob/bd38a646682e8b48717dde7584838cfbad083cb3/lib/hit-to-sitemap-entry.js#L8) to add the slug

**Comment by jamieu** [comment]
Nice 👍
