### ISSUE TITLE
Related objects - See more link

### ISSUE THREAD

**Issue by tobystokes** [TheScienceMuseum/collectionsonline#331]
make it look nice.

**Comment by tobystokes** [comment]
I was thinking of something like this:

![image](https://cloud.githubusercontent.com/assets/109024/17893477/ca5f6f82-693d-11e6-91b1-5bee93a5f7e7.png)

But that probably means that instead of usually returning 6 or 12 related, that should be reduced to 5 or 11.

Any other opinions?

**Comment by jamieu** [comment]
We show only display the 'more items' block if more than two lines of results (ie. if there are more results than we can display on the page).

<img width="523" alt="screen shot 2016-09-08 at 13 01 09" src="https://cloud.githubusercontent.com/assets/91365/18348642/7b6b66e0-75c4-11e6-989d-45fcee3e5f86.png">

**Comment by tobystokes** [comment]
hmm, I can't see that in the code, it looks like it shows if there _any_ related objects, but never shows more than two lines worth. (and clamped to only show whole lines). But that's fine.
