### ISSUE TITLE
Provide list of synonyms

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#332]
@jamie and Emily to provide a final list of synonyms.

**Comment by jamieu** [comment]
@SimonLab what format do we want these in and has it been coded to deal with multiple synonyms pointing to one term?

I was thinking:
- "actual term to search for / what is already in the index" <-- "Search terms entered by user"
- "London and North Eastern Railway" <-- "LNER"
-  "Locomotive" <-- ["train", "steam engine"]

Could supply a list as JSON or CSV (with the first value being the canonical term)

**btw. this is low priority (for now) compared to the other issues, let's pick this back up once we've cleared off some of the more pressing issues / bugs**

**Comment by iteles** [comment]
Not a pre-launch blocker as agreed with @jamieu, particularly given the dependency on re-indexing.

**Comment by SimonLab** [comment]
After more research I think we can avoid re-indexing the database as we don't use phrase_match query but just a simple multi_match. The phrase_match query was the reason why I thought we have to reindex the database with the synonyms analyzer see https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-word-synonyms.html. I'm doing more test but I think we should just use a [simple expansion] (https://www.elastic.co/guide/en/elasticsearch/guide/current/synonyms-expand-or-contract.html#synonyms-expansion) ie just a list of synonyms "train", "steam engine, locomotive". The idea is at query time to convert the term to multiple query which match each synonyms.

If we use the one <- many we will need to reindex the database to get the common term for the query time and index time

**Comment by jamieu** [comment]
Yeah!!

**Comment by jamieu** [comment]
Will update the list of values, where in the codebase are we currently storing them?

**Comment by SimonLab** [comment]
@jamieu I'm thinking of creating a new repo specifically for the  synonyms to not add more maintenance features to the application itself. I think the list of synonyms will be stored in a json file.

**Comment by jamieu** [comment]
That sounds like a good idea.

**Comment by jamieu** [comment]
@emilyfildes we need to work out what should go in this list, assume existing analytics will help here.

**Comment by jamieu** [comment]
Need to chat about this prior to launch, if only to ensure we have the very basics handled ie.

train: locomotive
plane: aeroplane

**Comment by jamieu** [comment]
@SimonLab don't let us forget about this one, although probably best to pick up once the index stabilised (we have the images all processed).

**Comment by iteles** [comment]
@jamieu Confirmed on 18-Mar-2019  that what is required to close this issue is additional documentation.
