### ISSUE TITLE
Re-indexing of db changes for synonyms

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#333]
Re-indexing of database and clarifying the process with K-Int so that when they re-index, they know how to incorporate this rather than erase it.

Linked to https://github.com/TheScienceMuseum/collectionsonline/issues/332

**Comment by SimonLab** [comment]
I think we should be able to use the synonyms just at query time so the reindexing might not be necessary, see https://github.com/TheScienceMuseum/collectionsonline/issues/332#issuecomment-255118495

**Comment by jamieu** [comment]
Ah, that sounds like a positive direction!

**Comment by jamieu** [comment]
Might need some help here, re what to do, when we next have a fresh index.

(or better still do we have some docs anywhere?)

**Comment by SimonLab** [comment]
We might not need to change the database. If needed this issue can be recreated on the [synonyms repo](https://github.com/TheScienceMuseum/synonyms)
