### ISSUE TITLE
Consideration of where to store user-improved search data

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#339]
Currently being stored in leveldb, need to consider what to do when the app is distributed among multiple servers.

**Comment by Danwhy** [comment]
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Clusters.Create.Redis.CON.html

**Comment by nelsonic** [comment]
@Danwhy if you end up deciding to _use_ ElastiCache, please let me know. thanks! 👍

**Comment by jamieu** [comment]
Have setup ElasticCache but it's in a different VPC to the current stage server, need to test once moved.
