### ISSUE TITLE
Display filter search bar

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#341]
The filters on the search bar are overlapping on mobile:
![screenshot_2016-09-03-12-27-08](https://cloud.githubusercontent.com/assets/6057298/18242153/c7f6c056-734c-11e6-90ce-20e5ae444fb5.png)

**Comment by tobystokes** [comment]
Samsung Galaxy S5/S6 ?

**Comment by SimonLab** [comment]
the screenshot is from a [oneplus x](https://oneplus.net/uk/x) phone
