### ISSUE TITLE
Logic for filter search bar

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#343]
see #244 Build the logic of the filters under the search bar.

By default some filters will be already selected (for example the musuems). @jamieu the way we are thinking to be able to know when a person is searching from a specific museum is when the user click on a link to access the website from the museum website, is this the right way to do it?

**Comment by tobystokes** [comment]
Given the growing collection of referring URL's the museums use, I think it would be clearer for web editors and end users if there was a unique URL for each museum.
I think the likeliest use case is that an incoming link from a museum will be a 'canned search' including museum facet and probably another filter like search term, or 'on display'.

Perhaps for these cases, have a short form like /nrm -> /search?museum=NRM

**Comment by jamieu** [comment]
Yes, REST'like urls would be great.

/category/space
/museum/nrm

(the "on display @ X museum" is probably high enough we could just go with
/nrm or /sciencemuseum as an alias for /museum/nrm)

**Comment by iteles** [comment]
@tobystokes @jamieu I would suggest that these last 2 comments should be an entirely separate issue, linked to https://github.com/TheScienceMuseum/collectionsonline/issues/329.

@jamieu On the pillbox filters in the search bar, could you please take a look at @SimonLab's question in the first comment? 😊

**Comment by jamieu** [comment]
@Danwhy OK to clarify my thinking on the logic, the pill boxes are just another representation of the filters on the right hand side. The difference is that they should retain state between free text searches (ie. are 'sticky' and need to be cleared manually, either via the facet/filter or clicking the X on the pill box, running a new search won't automatically clear them like the other filters).

My thinking (and do feel free to tell be this is flawed) is that [on display at] Museums and possible Categories (I need to user test this as I expect it will divide users) are broad enough filters that a user might want to retain between free text searches in the main search box (ie. like 'Electrical good' in eBay).

In terms of REST'ful and 'short' urls, @iteles  is right we probably should conflate those two requirements with this one. But just to clarify we are expecting users to be able to arrive at the site via canned queries (effectively the state a user would be in and the url they would see after filtering a search). For common filters we would like the site to support a REST'ful style URL structure ie. /category/railways-and-locomotives or /on-display/science-musuem (which could itself be reduced to /science-musuem as a 'short url)'
