### ISSUE TITLE
Delete foundation-sites dependency?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#352]
@tobystokes I've delete all the dependencies of JQuery and converted the function to vanilla js, the only one I'm not sure 100% that we can delete without breaking anything is [foundation-sites](https://github.com/TheScienceMuseum/collectionsonline/blob/c53a7060e9dfa8e3862e7c3a0c21a86433aa9a14/client/main.js#L1-L6). I've done some tests without it and it seems that the website is working well but I just want your approval before I make a PR.

I think we are only using the css from foundation which is store on the css/base folder of the app so it's not anymore dependent of the package in node_modules, that's right?

**Comment by tobystokes** [comment]
I'm using foundation-sites as a base css framework for things like grid, so it needs to exist as a dependency package in node, but I don't think we are using any of the js plugins/events it includes, so I see no reason why all js references can't be deleted.

There is probably a `$(document).foundation();` still floating around? If it works without it, then get rid!

**Comment by SimonLab** [comment]
resolve with #347
