### ISSUE TITLE
REST'ful style urls / pretty routing for key filters

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#356]
Rather than ?queries=strings, it would be good if we could support more REST'ful style urls for the filters. This will allow for nice descriptive urls / landing pages for Google to index (_we should possibly think about adding these the sitemap.xml?_) and friendly urls for users to use when linking to say 'Locomotives on display at the National Railway Museum'.

/on-display/science-musuem
/on-display/national-railway-museum

/category/locomotives
/category/art

_or indeed_

/category/locomotives/on-display/national-railway-museum

The values can follow (and should follow) the same name/values as the filters themselves, albeit lowercased and separated/escaped with dashes.

**Comment by SimonLab** [comment]
@jamieu do you also want the possibility to have multiple value for the filters? For example:
/category/locomotives,art,..

**Comment by jamieu** [comment]
Good question, I think yes and comma delimited for as per your example.

**Comment by SimonLab** [comment]
@jamieu I had more thoughts on this and it feels strange for me to build restful API which act like filters. We are currently using the [JSONAPI](http://jsonapi.org/format/#fetching-resources) format to define our API and if we are mixing our /search endpoint with other new endpoints (/category, /on_display) I think it will break the logic of the JSONAPI and add more complexity to the urls.


We also have the optional type keyword which precise the type of the search (objects, people or documents). So the url might start to feel a bit long.

I guess we could maybe make it works  for one more keyword endpoint but I don't think mixing the category and on_display endpoint will work and I don't think anymore we should add multiple values too:

So I think we could maybe have something like this:

one keywords (category or on-display) with only one value:
/search/category/art/objects
or
/search/on-display/national-railway-museum/objects

But I don't think we should have

/search/on-display/national-railway-museum/category/art/objects

and with multiple values it looks complex and it brings the question on how to distinguish values containing commas and multiple values:

/search/on-display/national-railway-museum/category/art,locomotives/objects

If we decide to have the on_display and category on the url at the same time there is also the question on how to order them.

So to conclude I think we might just add more complexity compare to how much value it will give to the users, but maybe It's ok so please don't hesitate to contradict me!

@jamieu @nelsonic @iteles @Danwhy any thoughts?

**Comment by jamieu** [comment]
Still thinking/pondering, all good points you raise....

I agree overly long REST'ful urls have their own issues. Maybe we just do
this for the most important / top level facets like "on_display (museum)"
and "category" with the rest falling back to query based filters?

btw. there are far more noticeable  (in terms of a user using the site)
issues to resolve right now, some that we can't beta-launch with until
fixed. So rather get those addressed first as I fear this issue might
become a time / resource sink if we don't have a clear solution defined.
That said, it would be frustrating to launch and then decide to change our
url structure so we should keep thinking about it, if we could do something
here without spending to too much time on it, that would be fantastic.

Let's hold of fun it for now and discuss in person or set aside some time
to discuss on Slack.

**Comment by iteles** [comment]
Agreed with @jamieu that these would be left as-is for now as they would cause many issues for the Google Analytics set up by the SMG.

**Comment by jamieu** [comment]
Parking / closing this for now, maybe one to re-vist in future.
