### ISSUE TITLE
Short url's for museums

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#357]
This issue is an enhancement to #356 (we should tackle  #356 first)

These should simply be temporary redirects to the longer (REST'ful) paths ie. /nrm -> /on-display/national-railway-musuem.

/nrm
/scm
/msi
/nmem

**Comment by SimonLab** [comment]
- create a redirection which link to the filter on display
- keep the short url when we replace the redirection later on

**Comment by iteles** [comment]
Dependent on new index.

**Comment by jamieu** [comment]
👍
