### ISSUE TITLE
Archive browse: Ensure child records show parent

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#364]
I need to double check the index, but I would have expected LAV/2 to sit under LAV, yet they seem detached from each other?

(LAV) : /documents/smga-documents-110072201#archive-block
(LAV/2) /documents/smga-documents-110072222#archive-block

This may be how they are in the index, in which case that's a problem with the data :-)

<img width="1239" alt="screen shot 2016-09-08 at 13 38 19" src="https://cloud.githubusercontent.com/assets/91365/18349477/8ca11180-75c9-11e6-954b-bb1036a2cf1d.png">

<img width="1270" alt="screen shot 2016-09-08 at 13 39 33" src="https://cloud.githubusercontent.com/assets/91365/18349513/be5360de-75c9-11e6-9d30-733c2becb1a5.png">

**Comment by Danwhy** [comment]
That first picture isn't LAV/2, it's LAV/2/P1, so it's only showing it's direct parent (LAV/2). 

Should it be showing more than that?

**Comment by jamieu** [comment]
yes, we want to see the whole of the archive, from the top
(fonds/root/archive node) to the node your at (obviously the other paths of
the tree should be closed to begin with).
