### ISSUE TITLE
Use the right property (name) of the category object for the facet

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#368]
Use the right property (name) of the category object for the facet (category.name) to just show the category name (without the museum name).

~~This update should ideally be made to the index,which I will chase up.~~

~~But in the interim would it be possible to strip the Museum name from the front of Category field. Either at the point we extract it from the index, or before we display it (both in the facets and on the object page and ideally the API as well).~~

~~So basically strip everything before the first - (dash) to leave just the category name.~~

**Comment by SimonLab** [comment]
link to #274? We can display only the name of the category and trim out the name of the museum. I think most of the object contain the category property with the name of the museum so we could also build the filter of the museum based on this property but I think it's still worth to wait for the location property to be put back to the index as it tell us if it's on display or not

**Comment by jamieu** [comment]
Oh..no, very separate issues :-)

The 'on display at X museum' should come from the location/facilities - due
to be appearing in the index any day soon!

The museum code on the front of the category is more of an internal
cataloguing thing (based on who catalogued it) hence the reason for
stripping it off when displaying in the public realm.

[* ideally we'd do this in the index (in fact we will) so that 'NRM - Art'
and 'SCM - Art' both reduce to a single 'Art' category filter/facet value,
but for now - as long as it's not a huge effort - it would help to suppress
it on the front end so that when we're demoing the site to people they
don't immediately focus on it!]

**Comment by SimonLab** [comment]
Sounds good, thanks for confirming

**Comment by SimonLab** [comment]
The index has now three properties for the category:
```
"categories": [
{
"museum": "SCM",
"name": "Pharmacy",
"value": "SCM - Pharmacy-ware"
}
```
We can now use the name property instead of the value property of the category

**Comment by jamieu** [comment]
Yes, was just going to say...

We can now close this issue, or treat it simple as updating the front end to respect the new index.

**Comment by iteles** [comment]
@SimonLab Could you please link in the PR that changes this for the page itself as well as the facets?
