### ISSUE TITLE
Some odd alignment issues on the carousel

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#369]
Seeing some odd alignment issues on the carousel (the main focused image, which seems to have a duplicate/double white line and also the 'use this image' button reported here https://github.com/TheScienceMuseum/collectionsonline/issues/345). 

There's also strange 'ghosting' issue, see the engineering plan overlaps the other images, see below.

[This is on OSX / Safari]

Might be worth us all (including @tobystokes) getting on Slack to chat about the various states etc. and the route were going here, just to ensure we're all on the same page. Given it's such a key feature of the site and one of the few areas where we can shine with large images / user integration (like swipes / full screen). We need to ensure it works flawlessly on all platform incl. mobile. btw. not suggesting it doesn't, just pointing out how important that is!

<img width="1126" alt="screen shot 2016-09-09 at 10 28 24" src="https://cloud.githubusercontent.com/assets/91365/18382300/45f67630-7678-11e6-9a5b-6a6b814f9df7.png">

**Comment by tobystokes** [comment]
I can fix a few minor css issues, but not sure that the new plugin handles screen resizing as well, and it's definitely lacking touch/swipe support.

@Danwhy (sorry for not mentioning this earlier! but newly discovered) [Flickity](http://flickity.metafizzy.co/) is $(free) and £free for open source, might be worth a look.

**Comment by Danwhy** [comment]
@tobystokes Looks good, I'll definitely check it out

**Comment by jamieu** [comment]
Yes, Flickity <http://flickity.metafizzy.co/> feels very nice to use...but
then I'm a sucker for a bit of tactile feedback/bounce when you drag
something!

Would be more than happy to switch to it and then just toggle to
OpenSeadragon/Zooms for true full screen mode (if we can get it to handle
that toggle).

**Comment by iteles** [comment]
Includes snag in #210

**Comment by jamieu** [comment]
Fixed
