### ISSUE TITLE
Update sitemap with slug?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#374]
What is the best way to update the sitemap files with the slug, should we add one more route for each elements, or should we choose one url the canonical or the slug url?

**Comment by jamieu** [comment]
My guess is we have go with the short/canonical ones in the sitemap.xml if we want a never changing (if the title changes) base/canonical url.
https://support.google.com/webmasters/answer/139066?hl=en

But be great if we could get Google to display the url with a slug but treat the base URL as canonical, but **I can't think of a nice way to do that**. Any one else have any suggestions?

**Comment by jamieu** [comment]
Putting both in the sitemap.xml will def. confuse Google and get us penalised, lets **not** do that.

I was about to suggest using the slugged version in the sitemap.xml file but using a `[rel="canonical"]` tag in the header of the pages that points to the non slugged version, but Google warns against doing this, so maybe not....
> Don't specify different URLs as canonical for the same page (e.g. one URL in a sitemap and a different URL for that same page using rel="canonical").
https://support.google.com/webmasters/answer/139066?hl=en#6

btw. can I clarify what we are currently doing as things stand?

@nelsonic @iteles have either of you got any good thoughts here?

**Comment by jamieu** [comment]
Actually it's just occurred to me that it doesn't matter if the slug/title changes as the user will still get the same page / Google will reindex the new page (but the base part with the uid will remain the same)

So we should put the slugged version in the sitemap and treat the slugged version as canonical and use it through the the site.

(not sure why I was thinking of redirects and the short version being the canonical version. I blame it on today's hot weather).

**Comment by jamieu** [comment]
Just to be clear...

We should put the slugged version in the sitemap.xml and treat the slugged version of the path as the canonical one and use it throughout the site when creating links.

The non-slugged version should never be used when creating links / site maps.

**Comment by iteles** [comment]
Agreed with @jamieu that this was not a hard blocker for launch but will ideally be done in this sprint for SEO purposes.

**Comment by jamieu** [comment]
Is this issue resolved now? Do I just need to deploy the new zip?

**Comment by jamieu** [comment]
@SimonLab Need to make sure this is deployed to Lambda, grab me when you have a free moment to talk though that.
