### ISSUE TITLE
Investigate using parent terms (hierarchy) for taxonomy values

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#375]
So that we have "steam locomotive -> locomotive -> vehicle"

This info is now in the index although we might need to normalise or exclude values encased in < > angle brackets.

Needs further discussion / investigation before straying work on this.

`
{
    "@link": {
        "impact": true,
        "type": "reference"
    },
    "admin": {
        "available": true,
        "id": "term-501558",
        "status": "valid and published",
        "uid": "smgc-term-501558",
        "uuid": "e64c684d-bc30-3468-a5df-903d054c856c"
    },
    "name": [{
        "primary": true,
        "type": "preferred",
        "value": "locomotive"
    }],
    "sort": 1
}, {
    "@link": {
        "impact": true,
        "type": "reference"
    },
    "admin": {
        "available": true,
        "id": "term-503152",
        "status": "valid and published",
        "uid": "smgc-term-503152",
        "uuid": "c691e4f1-dc89-30b2-93cf-ce2294a7f714"
    },
    "name": [{
        "primary": true,
        "type": "preferred",
        "value": "vehicle"
    }],
    "sort": 2
}, {
    "@link": {
        "impact": true,
        "type": "reference"
    },
    "admin": {
        "available": true,
        "id": "term-503166",
        "status": "valid and published",
        "uid": "smgc-term-503166",
        "uuid": "9611e275-721b-38b5-b5f3-b69aa979b0a9"
    },
    "name": [{
        "primary": true,
        "type": "preferred",
        "value": "VEHICLES AND VEHICLE COMPONENTS"
    }],
    "sort": 3
}],
"summary_title": "steam locomotive"
}
`

**Comment by iteles** [comment]
Ties in with #361
