### ISSUE TITLE
We seem to have lost the full list of names/terms for the front end? 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#379]
We should be showing these as a **lower cased**, **linked to the SERPS page via the _type_ field**, **comma separated list** in the (_we may want to limit the types we show but for now let pull them all though and display them_).

smgc-object-129834

<img width="497" alt="screen shot 2016-09-14 at 10 31 16" src="https://cloud.githubusercontent.com/assets/91365/18507022/71e5fc42-7a66-11e6-8c86-aebe2586ff7f.png">

<img width="349" alt="screen shot 2016-09-14 at 10 25 10" src="https://cloud.githubusercontent.com/assets/91365/18506825/99f6ce9c-7a65-11e6-9adb-f57de0bdedb2.png">

**Comment by iteles** [comment]
Linked to #362
