### ISSUE TITLE
Pull all the taxonomy terms into the taxonomy block (hierarchically)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#380]
{"query":{"match":{"admin.uid":"smgc-object-137353"}}}

ie. [drug delivery device](url) / [medical instrument](url) (with the terms hyperlinked back to the SERPS page).

For now can we lowercase the name/values and skip any terms that are surrounded by <> angle brackets. Also might be worth adding a check to ensure we only go up three levels (for now).

<img width="725" alt="screen shot 2016-09-14 at 10 39 01" src="https://cloud.githubusercontent.com/assets/91365/18507258/89949604-7a67-11e6-9330-cb5302d03f24.png">

**Comment by iteles** [comment]
Linked to #362
