### ISSUE TITLE
Ensure all object types in facets and on object pages are lowercase

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#381]
ie. "Robot" (we should also do this on the object pages too).

<img width="346" alt="screen shot 2016-09-14 at 12 13 58" src="https://cloud.githubusercontent.com/assets/91365/18510214/baba4384-7a74-11e6-8dc8-af0dcae11d7c.png">

**Comment by SimonLab** [comment]
I will create a lowercase version from the server side but I think a better solution will be to do this on the elasticsearch index. I still need to keep a reference of the real value from elasticsearch as the search won't return the same results as the elasticsearch index is case sensitive. For example "Ar"t will return a list of results but searching for "art" will not return any results.

**Comment by jamieu** [comment]
OK let me see about getting that done in the index, agree that's the more
sensible place for it.

btw. can we not query in a case insensitive mode? Or do we need to set the
index to do that.

**Comment by SimonLab** [comment]
If I'm correct the values for the categories are indexed without being analysed, so no transformations are applied to the value. One solution is to apply a lowercase analyzer (or I think the default analyzer of elasticsearch do it automatically) but this implies to reindex the data with the new analyzer.

I'm searching if like you propose we can execute a search in insensitive mode, it might be a better solution.

**Comment by jamieu** [comment]
Yes the 'case' has no relevance for object names (or indeed any filters for
that matter).

**Comment by SimonLab** [comment]
Unfortunately after more research I don't think we can have a quick solution to search with case insensitive without applying an analyzer to the existing values in elasticsearch:

https://medium.com/@lefloh/elasticsearch-and-case-sensitive-term-queries-6f6c516aebed#.z9qc65ycv
http://stackoverflow.com/questions/17266830/case-insensitivity-does-not-work

If all the values in elasticsearch where lowercase we could have transform our category terms at query time without touching the database but it's not the case.

So I think we should apply an lowercase analyzer to all the values (we have now some changes on the mapping to apply to the index: english analyzer, lowercase analyzer, synonyms analyzer. I've started the documentation changes for the synonyms but it might be worth to create more issue for the other one and to try them on a localhost elasitcsearch database or on aws if we can have a test database).
If we want to avoid reindexing we could also use the multi-fields feature, this might resolve the issue but It might also add some complexity to the structure of the database by adding more fields.

**Comment by SimonLab** [comment]
see https://github.com/TheScienceMuseum/collectionsonline/wiki/Index-Changes-for-Relevance for future analyzed fields

**Comment by Danwhy** [comment]
For now we could just use css to lowercase the object names, however if the term is in the document twice (once uppercased and once lowercased), it will show up in the filters twice: 
<img width="247" alt="screen shot 2016-10-11 at 14 54 18" src="https://cloud.githubusercontent.com/assets/8939909/19273023/d96f392a-8fc2-11e6-8fa0-215142482d05.png">

But saying that, even if we don't lowercase it, it will still show up twice: 
<img width="270" alt="screen shot 2016-10-11 at 14 57 25" src="https://cloud.githubusercontent.com/assets/8939909/19273074/11913f7e-8fc3-11e6-8a74-7e918f0c5bc4.png">

Thoughts?

**Comment by jamieu** [comment]
Maybe leave as is for the moment,

The lowercased values should be in the next export/index - we're just
waiting on a fix before we can run it.

**Comment by jamieu** [comment]
Values should now all be lowercased in index, with nothing more to do on this issue - is that correct?
