### ISSUE TITLE
Set up Redis for the archive

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#387]
Linked to #311 and #364.

**Comment by jamieu** [comment]
This is now setup, but need to re-tested once we are in new AWS VPC

**Comment by jamieu** [comment]
This is now setup, need to test

**Comment by jamieu** [comment]
Would be good to know / document where this is set - in case it needs to be set it in future (although for now the site seems fine without it).

Then happy to close issue.
