### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#398]
We have a few dependencies that need a quick update (although the github release notes for these 3 are particularly unhelpful - read: non-existent):

https://david-dm.org/TheScienceMuseum/collectionsonline
<img width="980" alt="screen shot 2016-09-25 at 23 47 33" src="https://cloud.githubusercontent.com/assets/4185328/18818766/a261769a-837a-11e6-97fd-7b4597328739.png">

**Comment by SimonLab** [comment]
resoved with #563
