### ISSUE TITLE
Submitting an empty query

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#399]
Could we just show the whole collection in the search results (for users to filter down) if not query is entered. Looks like we can already do this in some paces?

Rather than just showing the error below?

<img width="301" alt="screen shot 2016-09-28 at 12 32 08" src="https://cloud.githubusercontent.com/assets/91365/18911987/f01e019c-8577-11e6-80af-c036c343ff2a.png">

**Comment by SimonLab** [comment]
This should have the same as doing a no search query

**Comment by SimonLab** [comment]
resolved with #440
