### ISSUE TITLE
Error when clicking in the last result in the paginations (for large result sets)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#400]
Clicking the last link in a large result set thaws an error?

/search/objects?page%5Bnumber%5D=5572

<img width="932" alt="screen shot 2016-09-28 at 12 29 43" src="https://cloud.githubusercontent.com/assets/91365/18912043/50ed1cc4-8578-11e6-9762-069510c50be3.png">

**Comment by SimonLab** [comment]
see http://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window can we add more memory or is there another solution?

**Comment by jamieu** [comment]
Thanks @SimonLab 

Have downgraded the priority on this for now, once we move to production we'll have a bigger ElasticSearch instance (with more memory) anyway.

**Comment by jamieu** [comment]
Haven't noticed this recently so closing for now, will revisit once we move to final production env.
