### ISSUE TITLE
Company names being incorrectly displayed in filters as object type.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#403]
See multiple entries for 'Turner Bros." in filters, these should a) not be appearing under 'Object type' b) ideally (just) one of them should be appearing under people. 

My guess is the are coming form that single archive record/document and this is due to the same field name being used in the index for Mimsy and AdLib records to  represent different things (ie. .name in Mimsy is the object 'type' name, whereas in AdLib records in refers to the name of a person). 

Need to investigate index / code and see what is causing this.

<img width="812" alt="screen shot 2016-09-28 at 12 46 54" src="https://cloud.githubusercontent.com/assets/91365/18912326/b01409a0-8579-11e6-9f2d-5452cd224262.png">

**Comment by SimonLab** [comment]
resolved with #406
