### ISSUE TITLE
Date not appearing (despite being in index)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#408]
The date seems to be in the same structure as others in the index, but it's not appearing and I can't figure out why. Any ideas?

/objects/smgc-objects-8035455 
accession # 2005-121

{"query":{"match":{"identifier.value":"2005-121"}}}
{"query":{"match":{"admin.uid":"smgc-object-8035455"}}}

``
"lifecycle": {
    "creation": [{
        "date": [{
            "latest": 1999,
            "role": [{
                "value": "made"
            }],
            "value": "1999"
        }]
    }]
},
``

<img width="642" alt="screen shot 2016-09-30 at 16 08 47" src="https://cloud.githubusercontent.com/assets/91365/18996419/328e4d96-8728-11e6-888a-5ac2fb56be94.png">

**Comment by Danwhy** [comment]
It looks like we're only displaying it if it has a date _and_ a place made. I'll fix this.

**Comment by jamieu** [comment]
Well spotted
