### ISSUE TITLE
Suppress the filter on the 'no results' page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#421]
Hopefully a small tweak, but on the 'no results' page could we:

- suppress the 'view icons' 
- suppress the 'refine search' block _(note: I can't think of a use-case where a filter would be selected and still display no results, but if you can, then maybe add in a check to "only suppress if nothing is checked")._

<img width="1188" alt="screen shot 2016-10-03 at 19 19 40" src="https://cloud.githubusercontent.com/assets/91365/19048561/c8470f4e-899e-11e6-8cca-1d8c5e2cb759.png">

**Comment by SimonLab** [comment]
The dates filter are input text so it's possible that the users filter with a range of dates which won't returns any results.

**Comment by jamieu** [comment]
Good point, lets suppress the filters only if nothing is selected (if that
isn't too tricky).
