### ISSUE TITLE
Ensure API exposes all images/media attached to an object or document

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#423]
Be good to go back over this and check that we're pulling though the same fields as we're diplsayign on the front end, particular WRT images and their metadata.
https://github.com/TheScienceMuseum/collectionsonline/wiki/Collections-Online-API

**Comment by Danwhy** [comment]
@jamie Do you mean to limit the fields in the API to only send what we're showing on the front end, or to make sure the API has everything we're displaying on the front end?  
If the latter, we definitely are, as we're using the api response to create the pages.

**Comment by jamieu** [comment]
Mmm and yes :-)

I guess the question is how much more are we exposing via the API as there
is data in the index we might not want to expose (i.e. we wouldn't want to
expose the whole ES record). If we are doing that it's not the end of the
world, but I would need to sanity check it.

You know what, let me eat my own dog food and make an API call ;-) That
should hopefully answer my own question!

My main thought was actually around images and ensuring that the API was
still reflective of the data in displayed on the front end.

**Comment by jamieu** [comment]
Mmm and yes :-)

I guess the question is how much more are we exposing via the API as there
is data in the index we might not want to expose (i.e. we wouldn't want to
expose the whole ES record). If we are doing that it's not the end of the
world, but I would need to sanity check it.

My main thought was actually around images and ensuring that the API was
still reflective of the data in displayed on the front end.

**Comment by jamieu** [comment]
Closing this issue off, as we're exposing all the fields we need.

(we're problem exposing a little more than we need to, in terms of past descriptions / dates etc. but nothing that would case a problem. We can always look at removing those from the index anyway).
