### ISSUE TITLE
Image Licence filter

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#429]
We should have everything we need to do this (albeit only for select objects such as 'Rocket' objects/smgc-objects-26704)

See last comment on https://github.com/TheScienceMuseum/collectionsonline/issues/244 which covers the on display filters 

**Images**
- [ ] Has image  <-- has an image (any image)
- [ ] Non-Commercial use <-- has a CC licensed image

For 'Image licence' I think we hard code the facet/filter to just have two values, the first 'Non-Commercial ' is any object with an image with a CC licence, the second is any object with an nn-CC image.

**Comment by Danwhy** [comment]
@jamieu Can I just check I'm understanding this correctly?

* Any image with a CC licence should have a filter value of 'Commercial'
* Any image without a CC licence, or with a non commercial CC licence should have a filter value of 'Non-Commercial'

Is that right?

**Comment by jamieu** [comment]
Opposite way round..

CC is non-commercial
Without CC (or commercial CC) is commercial

**Comment by Danwhy** [comment]
@jamieu So there's a bit of an issue with splitting the licenses into 'commercial' or 'non-commercial'. Displaying these values is fine, but when a user selects one of them as a filter, we're going to have trouble searching elasticsearch without having a list of all the commercial/non-commercial licenses that exist. 

We can do this by having a script to pull out all of the licenses that exist in the database, but keeping it up to date will be a little difficult. Unless there already is a list of all the values that could exist, I assume that's unlikely though, due to slight variations in the data that probably exist.

I've already pulled out the actual licenses to use as filters, would you like me to merge that into master, or keep it out until we have the commercial/non commercial grouping working?

**Comment by jamieu** [comment]
Ah of course,

We should have the licence as a separate field in the next iteration of the index (or rather a flag indicating when we have a CC licence in the usage field). Just waiting for an issue with one of our collections systems to be fixed, so we can run a new export. 

Hold off merging for now.

**Comment by iteles** [comment]
To finalise in sprint 10.

**Comment by iteles** [comment]
Moving to sprint 11 now that we have images.

**Comment by Danwhy** [comment]
@jamieu I've noticed a few new flags on the images we currently have (see below). Are any of these relevant to this issue? ("for_sale" for example)
<img width="185" alt="screen shot 2016-11-21 at 16 45 02" src="https://cloud.githubusercontent.com/assets/8939909/20491676/06a595e4-b00a-11e6-8cbb-d8523d6a8a43.png">

**Comment by jamieu** [comment]
Hi Dan,

No... TBH they shouldn't even be in the public index.

The CC licences should be in `usage_terms`

Other than that (these are the fields for displaying under the image; which I think your already pulling though):
- credit line = credit
- copyright = legal.rights.details
- caption = caption
 
Also there in there yet, but there should (soon) be a date_uploaded and a priority field (which we'd like to use for sorting) - see https://github.com/TheScienceMuseum/collectionsonline/issues/499

Jamie

**Comment by Danwhy** [comment]
So there's not going to be a flag that specifies whether it's a commercial or non commercial licence?

Should I just go back to my earlier solution?

**Comment by jamieu** [comment]
Exactly, if there is *any* licence in that field it's non-commercial (we
should oaky be extracting cc licences).

Does that make sense/work?

**Comment by Danwhy** [comment]
Ah ok. Yeah that shouldn't be a problem then.

**Comment by jamieu** [comment]
Hi Dan,

Not sure how far on with this you are but, being discussing this and we think it would be best to group these as follows:

**Images** <-- header
[] Has image <-- has an image (any image)
[] Non-commercial use <-- has a CC licensed image

Is that OK?

**Comment by Danwhy** [comment]
Yeah, should be fine :+1:

**Comment by jamieu** [comment]
perfect!
