### ISSUE TITLE
Images/Carousel missing for archive/document pages.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#432]
We seem not to be displaying the images on archive pages, these should work the same as the object pages (obv. only showing if there are images).

This document has images..
/documents/smga-documents-110000483

{"query":{"match":{"admin.uid":"smga-archive-110000483"}}}

```
"processed": {
    "large": {
        "format": "jpeg",
        "location": "Archive_6/jDMwMTTlK9AAAAFSfdzWcg_WINID_1453810572897/BAB_K_62v_Calculating_Machine_tif/large_BAB_K_62v_Calculating_Machine.jpg",
        "location_is_relative": true,
        "measurements": {
            "dimensions": [{
                "dimension": "height",
                "units": "pixels",
                "value": 576
            }, {
                "dimension": "width",
                "units": "pixels",
                "value": 384
            }]
        },
        "modified": 1453830751000,
        "resizable": true,
        "type": "image"

```

**Comment by Danwhy** [comment]
This should be fixed when #394 is merged into master

**Comment by jamieu** [comment]
Thanks @Danwhy ,

I thin now might also be the time to turn off the 'holding images' of the difference engine, as we have a few image records with real images and are hoping to have the remaining images imported/processed within the next week (or two).

**Comment by jamieu** [comment]
can see it now!
