### ISSUE TITLE
Assign museum links to the 'on display' widget

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#435]
My thought is for now it would simply be a mapping between museum (code ie. NRM) and four maps one per museum (which we already have).

@tobystokes will need your help styling this once we have some objects that are appearing on display.

**Comment by jamieu** [comment]
Just been informed that we don't have a consistent set of PDF maps to use here.

So let's just link to the relevant museum's visit page.

- http://www.sciencemuseum.org.uk/visitmuseum
- http://www.nrm.org.uk/planavisit/
- http://www.nationalmediamuseum.org.uk/planavisit
- http://msimanchester.org.uk/visit

**Comment by tobystokes** [comment]
styling is #54 - but on hold until example object is viewable

**Comment by jamieu** [comment]
Closing for now, might want to revisit once we have the new CMS / gallery pages.
