### ISSUE TITLE
Add labels to search filter pills

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#437]
![img_3145](https://cloud.githubusercontent.com/assets/91365/19117278/587e24ae-8b10-11e6-8082-2a6466abb62e.JPG)

**Comment by tobystokes** [comment]
To explain what e.g.'Science Museum' means as a value (of on display) and differentiate category & archive names. maybe different colours for each type?

**Comment by tobystokes** [comment]
like? 
![image](https://cloud.githubusercontent.com/assets/109024/19188775/ed67faa0-8c8b-11e6-8215-b368d8023855.png)

**Comment by tobystokes** [comment]
note, all pills can be max-width'ed to a % of the total searchbox width, so long text will get ellipses. Are we ok to abbreviate names of museums?

**Comment by jamieu** [comment]
Yep, like it

Just getting Emily's thought too

**Comment by jamieu** [comment]
I think we liked (preferred) the rounded ends of the old ones, bit worried these ones look too 'buttony' (says, waving hands!)

Also given that the common (_although not only_) use-case will be a single pill box, it might be nice if the "searching within" allowed the fist button to slot into the label a bit more (_rather than ending with an arrow, have a general backwards arrow/slot_). _Although I get the reasoning behind the arrow end._

**Comment by tobystokes** [comment]
They may wrap on narrower screens, and i can't determine when that has happened, so _slotting_ may look weird in those situations

**Comment by jamieu** [comment]
How about if we used "In" as the first prefix?

Given that 95% of the time it will be one label that could work quite nicely and allow them to butt together.

ie.

[In>>On Display>>NRM)

**Comment by tobystokes** [comment]
![image](https://cloud.githubusercontent.com/assets/109024/19264200/c0cf8512-8f97-11e6-880b-4f068d976165.png)
I think we discussed before, and it's worth keeping, the 'searching within' prefix to make wholly explicit what is happening. here's a few more variations - tbh the plain ol' colon does the job for me!

**Comment by jamieu** [comment]
Take your point (re. explicit label) but feeling here is that "In" is neater and clearer if we slot the pill boxes into the label. Like the images below, with a hairline above them, as before.

_This does mean we'll have to adjust / add some logic if the pill box is the first or subsequent, not sure how tricky that will be._

![pill-boxes-x1](https://cloud.githubusercontent.com/assets/91365/19266226/69dad2da-8fa0-11e6-98bc-e17f4cd14ad1.jpg)
![pillboxes-x2](https://cloud.githubusercontent.com/assets/91365/19266225/69da4572-8fa0-11e6-939c-7ce0e9680601.jpg)

**Comment by tobystokes** [comment]
worst case:
![image](https://cloud.githubusercontent.com/assets/109024/19278343/c3f97e0e-8fd4-11e6-879d-a3f1bdd4f26b.png)

![image](https://cloud.githubusercontent.com/assets/109024/19279073/9e49dde0-8fd7-11e6-9566-9b1527b0d3ef.png)

but hopefully usually:
![image](https://cloud.githubusercontent.com/assets/109024/19279093/b9488b50-8fd7-11e6-959f-77f691392efc.png)

_(No don't need more logic for first pill but..)_ there will need to be some work done to add the on display and archive filters in there.
But I expect they are separate tickets already?

**Comment by tobystokes** [comment]
https://github.com/TheScienceMuseum/collectionsonline/compare/filterbadge-437

I'm hoping for a `data-filter="Category | Museum | Archive"`
which matches the new keys as well.
If anything different, then just need to update the css map of names->colours.

Other related issues:

- #445
- #438

**Comment by jamieu** [comment]
Closing
