### ISSUE TITLE
Remove 'user' filter field 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#443]
Creates confusion with a Maker filter as well so this can be removed as a filter.

(just comment out for now as we may add it back)

![unknown](https://cloud.githubusercontent.com/assets/91365/19151810/b2e87488-8bc6-11e6-8af2-b8e134932d46.png)

**Comment by jamieu** [comment]
@emilyfildes is your thinking still that we should axe this? Would be nice if we could maybe rename and limit it to showing railway companies (as a first pass). Not sure we can do much for launch, but one to pick up with collections team.

**Comment by emilyfildes** [comment]
@jamieu @SimonLab hello - I think for launch this should be axed as it is confusing with the Maker field. Am I right in thinking that this could impact results shown on the person page and the search results?

**Comment by jamieu** [comment]
Let's just comment tout that 'user' section from the filter block by
default.

**Unless we are explicitly filtering by a user** (ie. we don't see it by
default, only if the url has user= as a filter / you are linking from
another page).

**Comment by jamieu** [comment]
Let's comment it out of the filter block for now / by default.

**Unless we are explicitly filtering by user=**

_(ie. we don't see it by
default, only if the url has user= as a filter / you are linking from
another page)._

**Comment by jamieu** [comment]
This is good 👍 

Although when linking back though to a SERP page (based on a related user) it would be good to see them.
