### ISSUE TITLE
Rights field is appearing as undefined

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#444]
/objects/smgc-objects-8363471

The rights field is appearing as undefined?

Assume this is where it is being pulled from:
<img width="511" alt="screen shot 2016-10-06 at 13 16 18" src="https://cloud.githubusercontent.com/assets/91365/19151887/227fed58-8bc7-11e6-8206-ecc2a4bcc228.png">

**Comment by Danwhy** [comment]
@jamie Looks like the rights.details field doesn't exist any more.  
How would you like us to display the rights field now?

**Comment by jamieu** [comment]
Looks likes it's still available on some records, although nested under `legal`.

```
"identifier": [{
    "primary": true,
    "type": "accession number",
    "value": "2000-7828"
}],
"legal": {
    "credit_line": "Brace, Chris",
    "legal_status": "permanent collection",
    "rights": [{
        "holder": "National Railway Museum",
        "statement": "Assigned by Chris Brace, 09-06-2000",
        "type": "copyright"
    }]
},
```

**Comment by Danwhy** [comment]
Ok, how should we go about displaying this?
`'type' : 'holder', 'statement'`?
So for this one that would be:
`Copyright: National Railway Museum, Assigned by Chris Brace, 09-06-2000`

**Comment by jamieu** [comment]
Just double checking this now, but on further investigation I think we just want to show `credit_line` a
and `legal_status` but not the `rights` info (_despite me opening this issue to the contrary_).

Lets leave `rights` suppressed for now, close the ticket and we can revisit (if need be) once I have firm clarification.

**Comment by jamieu** [comment]
OK your gonna hate me :-) But we do want to display it like this, under 'credit' and above 'status':

Copyright: National Railway Museum"
ie. Copyright: rights.holder [ if rights.type == "copyright" ]

**Comment by jamieu** [comment]
Looks good
