### ISSUE TITLE
Supress link on 'Unknown..." makers.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#446]
(we can simply patter match on makers [or variations of like designer] starting with 'unknown' case-insensitively)

![unknown-2](https://cloud.githubusercontent.com/assets/91365/19152024/da65195c-8bc7-11e6-9bf2-1895573628d4.png)

**Comment by Danwhy** [comment]
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/co16969/daguerreotype-portrait-of-military-officer-daguerreotype

**Comment by jamieu** [comment]
👍
