### ISSUE TITLE
Splitting on Occupation not matching (due to exact term query).

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#447]
This is more a reminder for me to revisit this once we have Occupations split in the index to check if it is still an issue.

Splitting on Occupation (I know I asked for it..) causes a problem in that there are no matches for the split occupation (as a term query).

![unknown-3](https://cloud.githubusercontent.com/assets/91365/19152083/261ad918-8bc8-11e6-9558-a6bac73edda1.png)

**Comment by SimonLab** [comment]
The occupations values are now split see #514 #518
