### ISSUE TITLE
Inconsistent display of 'filter submit button'

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#450]
The blue filter button (at the foot of the faces) sometimes seems to appear when you first load the page, but not for subsequent AJAX pages.

For any user with JS enabled it should never appear.

**Comment by SimonLab** [comment]
should be resolved with #474

**Comment by jamieu** [comment]
Looks to be fixed - @emilyfildes are you still seeing this issue?

**Comment by jamieu** [comment]
Closing now, seems good from my brief check
