### ISSUE TITLE
Error when hitting 'filter button' (at foot of facets) with no results options selected

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#451]
Not 100% sure how I arrived here, but thought I should report it in case it highlights an underlying bug.

![unknown-6](https://cloud.githubusercontent.com/assets/91365/19152350/80ca130a-8bc9-11e6-9e00-6f7d2c2ab65f.png)

**Comment by Danwhy** [comment]
This was because of #399. Should be fine now
