### ISSUE TITLE
Odd results based on date search

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#454]
Searches on the date field (e.g. 1844 as below) throws back irrelevant results:

/search?date[from]=1844&date[to]=1844

Those results are not related to 1844.

Is this just not working or confused by the multiple date field?

**Comment by SimonLab** [comment]
linked to #481

**Comment by jamieu** [comment]
Investigating with collections teams / seeing if we can use a different field, don't think there is much we can do on the front end.
