### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#457]
### Our Collection
- About the collection: https://group.sciencemuseum.org.uk/about-us/collection
- Contact us:   https://group.sciencemuseum.org.uk/about-us/collection/contact
### Library and archive
- Archive catalogue: http://archives.sciencemuseumgroup.ac.uk/
- Library catalogue: https://smg.koha-ptfs.co.uk/
### Collection data
- Using our API: https://group.sciencemuseum.org.uk/about-us/collection/api
- Our API: https://github.com/TheScienceMuseum/collectionsonline/wiki/Collections-Online-API
### Images
- Non-commercial use: https://group.sciencemuseum.org.uk/creative-commons/
- Commercial licensing: https://group.sciencemuseum.org.uk/business-services/brand-licensing/

<img width="1184" alt="unknown-10" src="https://cloud.githubusercontent.com/assets/91365/19152806/a73465e8-8bcb-11e6-8759-9e9f5ae1e94c.png">

**Comment by SimonLab** [comment]
@jamieu some urls of the pages return a 404, are these pages going to be created later on or do we need to change the urls?

404 pages:
- About the collection: https://group.sciencemuseum.org.uk/about-us/collection
- Contact us: https://group.sciencemuseum.org.uk/about-us/collection/contact
- Using our API: https://group.sciencemuseum.org.uk/about-us/collection/api

**Comment by jamieu** [comment]
Yes, fine they are, Emily's going to create these pages.
