### ISSUE TITLE
Text for rights box

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#458]
Rights  

We encourage the use and reuse of our collection data.               

[CC0 icon]
Data in the title, made, maker and details fields are released under Creative Commons Zero.     

[CC icon]
Descriptions and all other text content is released under a Creative Commons Attribution 4.0 licence     

Using our data   > [link to page about this]

Our records are constantly being enhanced and improved, but please note that we cannot guarantee the accuracy of any information shown on this website.

**Comment by Danwhy** [comment]
Where should 'Using our data' link to?

**Comment by jamieu** [comment]
https://group.sciencemuseum.org.uk/about-us/collection/api

**Comment by jamieu** [comment]
Looks good
