### ISSUE TITLE
Don't display 'Clear Filters' on the 'No Results' page if no filters are selected

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#468]
<img width="680" alt="screen shot 2016-10-07 at 15 57 10" src="https://cloud.githubusercontent.com/assets/8939909/19194814/e4b5304c-8ca6-11e6-9e09-084a9e455cb1.png">

**Comment by jamieu** [comment]
Still seeing the date filter?

<img width="1165" alt="screen shot 2016-10-31 at 16 01 17" src="https://cloud.githubusercontent.com/assets/91365/19861117/477ed1a8-9f83-11e6-85e2-04f9f98c53e5.png">

**Comment by jamieu** [comment]
Perfect!
