### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#479]
Zoom is not currently working

I think it's a problem with the s3 bucket, as I get a 404 from the deepzoom link, and if I follow it, I get the following message:

```
/s3-zooms/zoom/Photo_Studio/Archive/Inventory_Number/1860/1862/1862_0005__0001__tif/1862_0005__0001_.ptif is neither a file nor part of an image sequence
```

**Comment by jamieu** [comment]
Hopefully fixed, but awaiting images to test

**Comment by jamieu** [comment]
We should have new zooms now, index will be updated soon.
http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/1972_36_Neg_102.ptif.dzi
