### ISSUE TITLE
Move 'Dates' facet to the bottom of the filter list

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#481]
Currently dates are not working as intended because the data itself is quite mixed. 

@jamieu and Emily made the decision in our sprint planning session today that this should _not_ be removed in its entirety for now (as there are still _some_ relevant results coming from this when the data _is_ correct) but that it should be _moved to the bottom of the list of filters_*.

**Comment by jamieu** [comment]
Perfect
