### ISSUE TITLE
Spike: Performance testing 

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#482]
Prior to launching to the public, we need to carry out some performance testing.

@nelsonic It would be good to have some of your time on Monday to discuss what the most effective way of doing this for SMG's purposes is.

**Comment by Danwhy** [comment]
After speaking with Nelson last week, we decided to use apachebench for some benchmark load testing. I'm currently working on a small script to use ab to make a bunch of concurrent requests to different endpoints/searches, so we can get an idea of the performance of the site
