### ISSUE TITLE
Add links to the museum logos across the top of the page

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#483]
The current navigation to the various museums across the top of the page links to nowhere.

Links to each of the museums are to be provided by Emily and then added.

**Comment by emilyfildes** [comment]
The header links are:

Science Museum: http://www.sciencemuseum.org.uk/
National Railway Museum: http://www.nrm.org.uk/
National Media Museum: http://www.nationalmediamuseum.org.uk/
Museum of Science & Industry: http://msimanchester.org.uk/
