### ISSUE TITLE
Remove links from opening paragraph on homepage

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#484]
Currently the opening paragraph for the homepage includes a few links (`<a>`) which lead to nowhere (`/#`). 

If this is still in the next iteration of the homepage design (#245), these links should be removed and made into plain text as agreed with Emily.

**Comment by tobystokes** [comment]
They should go to the results filtered by on display at that museum.
I can add them in if we know the form they will take already? (but don't think the on display filter is available yet?)

**Comment by iteles** [comment]
@tobystokes Currently dependent on #357

**Comment by tobystokes** [comment]
Actually, i _have_ removed them from this para as per original instruction, because with the new home page design, the 4 collection links are repeated close by as the first collections block, so redundant. 

Committed as part of #245
