### ISSUE TITLE
Integrate new homepage design

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#485]
Created in #245, awaiting this from @tobystokes before we can provide a time estimation.

The main change seems to be the 4 `on-display` boxes at the bottom of the proposed new design for which we will need images from @jamieu .

**Comment by tobystokes** [comment]
I'm assuming that as part of #245 I will put in some new images, so there may not need to be too much integration required after that.

**Comment by jamieu** [comment]
Looks good, closing
