### ISSUE TITLE
Implement client side search results filtering/pagination

### ISSUE THREAD

**Issue by alanshaw** [TheScienceMuseum/collectionsonline#49]
* Changes in filter choices should cause AJAX request to sever to retrieve updated results set
* Clicking on pagination links should retrieve subsequent pages
* Clicking on page size selector should change (and remember) number of results to retrieve

Depends on #48

**Comment by SimonLab** [comment]
Steps

- [ ] Send the ajax filter request
- [ ] Validate with Joi the query parameters on the server side
- [ ] Build the elasticsearch options parameters for filtering the values using aggregations
- [ ] Update the results on the page with Page.js
- [ ] On click on a filter crate the url with the query parameters. Use Page.js

Questions: Should we build two ways for filtering:
  - [ ] filter the data on the front end with javascript
  - [ ] filter by using elasticsearch (when javascript is not enabled)

**Comment by Danwhy** [comment]
Updated priority for current sprint

**Comment by iteles** [comment]
Work complete apart from bug, opened separately on #154
