### ISSUE TITLE
uncomment test image 

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#491]
see #489 

need to update this [test](https://github.com/TheScienceMuseum/collectionsonline/blob/master/test/client/images.clienttest.js) and this [one](https://github.com/TheScienceMuseum/collectionsonline/blob/master/test/images.test.js) when the multimedia property is back in the index

**Comment by jamieu** [comment]
Can I close this or is it still WIP / a reminder?
