### ISSUE TITLE
robot.txt

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#493]
Create robot.txt file which refer to the sitemap.xml. This sitemap witll be generated automatically with a lamba and stored on s3. see https://github.com/TheScienceMuseum/collectionsonline-sitemap and #299

**Comment by jamieu** [comment]
@SimonLab Can this just live in the root of the site and pull the location/url of the sitemap.xml from the ENV values.

**Comment by SimonLab** [comment]
@jamieu I don't think we can pull the value from the ENV value as the robot.txt won't be served from the server (so we can't use a template engine to replace the value) but we can just create the file with the url of the sitemap. To be done as the same time as #496

**Comment by jamieu** [comment]
I'm obviously overlooking something :-) but doesn't the robots.txt file
just live it the root of the site and point to sitemap.xml

**Comment by SimonLab** [comment]
After reading in a bit more detail the [google doc](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt) it looks indeed that we can create an endpoint /robot.txt with the sitemap url. So we can render the sitemap url with an ENV variable.

**Comment by SimonLab** [comment]
resolved with #493
