### ISSUE TITLE
Page jumping when selecting a filter or tab

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#494]
I'm noticing quite a bit of jumping when I select filters or tabs.
Anything we could do to reduce this would be really good.

**Comment by SimonLab** [comment]
This might be resolved with #474

**Comment by iteles** [comment]
Not yet, requires more investigation.

**Comment by Danwhy** [comment]
This appears to just be a safari issue. 

We can resolve it by adding a setTimeout of about 200 milliseconds around the re-rendering of the page (only if the user-agent is safari), but it feels a little hacky.

We could also resolve this by only re-rendering the lower parts of the search page, where the data actually changes, but this would take a little longer to implement.

@jamieu @nelsonic @SimonLab @iteles Any ideas/preferences?

**Comment by jamieu** [comment]
Maybe take a two pronged approach,

Use the setTineout for now but revisit to just display bottom half / the
results in a final pre-launch sprint.

**Comment by Danwhy** [comment]
It was actually simpler than I thought to just render the changed parts of the search page, so I went ahead and implemented that #565

**Comment by jamieu** [comment]
Ah fantastic :-)

**Comment by jamieu** [comment]
Seems better already, have you actually deployed the change?

**Comment by Danwhy** [comment]
Yeah, this has been deployed

**Comment by jamieu** [comment]
Cool 👍 

Closing..
