### ISSUE TITLE
deploy sitemap

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#496]
deploy the new sitemap lambda version from the zip folder generated.

**Comment by jamieu** [comment]
I think this is working, but @SimonLab can you confirm? (you had some concerns it might not be)

**Comment by SimonLab** [comment]
As soon as #676 is merged the endpoint /robots.txt will redirect to the right sitemap url

**Comment by jamieu** [comment]
Cool!
