### ISSUE TITLE
Lamda function to create periodic data export as CSV

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#498]
While we are planning to host an export of the data set as TSV/CSV on GitHub, it would also be useful for this export to be periodically updated.

There are two parts to this task:
- [ ] create a function/query that exports the public CC0 record data as a TSV/CSV data dump
- [ ] host it in it's own GitHub repo or S3?
- [ ] create a Lamda function to periodically re-export and save the resultant export in the above Git repo or S3

**Comment by SimonLab** [comment]
@jamieu just to clarify this feature: Is public CC0 record data referring to Creative Commons data already in Elasticsearch (objects, people and documents)? If yes do we already have a field in the database which label an item as a public CC0 data?

**Comment by jamieu** [comment]
Yes, the data we already have (it's basically the title, date, place, maker
and the data in the grey box; or put another way everything bar the
description text).

I'll need to write out which fields we'd want in the CSV for you, as well
need to denormalise it a bit / loos some fields/relationships (that won't
flattery easily) etc. I don't think it's worth labling fields as CC0 in the
index as we won't want to export them all.

It's not the highest priority, but it did occur to me that this is very
similar to the site map generator. So might be good to make a first stab st
it if was have time.

It's basically so that people (artists, data viz folk, researchers) can
really easily do stuff with / play with our core data without getting too
involved with API calls.
