### ISSUE TITLE
Sorting of image order

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#499]
Ensure that images (assigned to single record) are sorted by:

-          PRIORITY (low/medium/high)
-          SORT_DATE_OF_UPLOAD

Will supply exact field names once latest index is updated

_(ideally we'd also have a pagination field, but this isn't yet available)._

**Comment by SimonLab** [comment]
@jamieu from our discussion this morning it seems that the priority property will be a value between 0 and 9 and from the database it looks like the sort property is a string which represent the date of the upload:
![sort-multimedia](https://cloud.githubusercontent.com/assets/6057298/20534989/226b7ab0-b0db-11e6-8a7e-803d2bb60ecb.png)
Is this right and will this format will always be the same?

**Comment by jamieu** [comment]
Exactly!

**Comment by jamieu** [comment]
Exactly that!

**Comment by jamieu** [comment]
👍
