### ISSUE TITLE
Minimum viable automatic search results improvement

### ISSUE THREAD

**Issue by alanshaw** [TheScienceMuseum/collectionsonline#50]
- In memory (or perhaps a levelDB?) keep list of object IDs -> click counts sharded by month
- An API call is made to register a click on search result
- Add query filter for object ID will boost results
  - > 10,000 clicks boost 1.025
  - > 100,000 clicks boost 1.1
  - > 1,000,000 clicks boost 1.2
- Click counts older than 6 months are purged

**Comment by iteles** [comment]
Lower priority for now as discussed with @jamieu .

**Comment by Danwhy** [comment]
On hold for now, as Jamie is going to look into using the google analytics as the data to boost results by. 

Work done so far is in https://github.com/TheScienceMuseum/collectionsonline/tree/improve-results

**Comment by jamieu** [comment]
closing for now
