### ISSUE TITLE
Nest Galleries and Museum Facets

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#500]
If possible, we should nest the museum and gallery facets, so galleries are shown under their respective museums. I'm not sure if there's an easy way to get both the museum and gallery names using aggregations with the way the data is currently structured: 
<img width="393" alt="screen shot 2016-10-20 at 11 45 29" src="https://cloud.githubusercontent.com/assets/8939909/19556796/be61ef0c-96ba-11e6-82e8-8030a67193cb.png">

But I could manually add the galleries to their museums in a json file and use this to sort them when displaying the facets.

ref:  
<img width="714" alt="screen shot 2016-10-21 at 10 23 25" src="https://cloud.githubusercontent.com/assets/8939909/19593600/517897aa-9779-11e6-9e9f-0cf7ab7b0d1e.png">

**Comment by Danwhy** [comment]
@jamieu Is this similar to what you had in mind?  
<img width="299" alt="screen shot 2016-10-21 at 13 34 37" src="https://cloud.githubusercontent.com/assets/8939909/19598549/4eabd4fa-9793-11e6-8a34-049123e0ad71.png">

**Comment by jamieu** [comment]
Yes, exactly!

Although @tobystokes did have some CSS classes / styling for making the sub-values nest slightly nicer (there was an example on an old ticket but I deleted it to avoid confusion).

@tobystokes do you remember what classes provided the nested styling (or was it just a mock up).

**Comment by tobystokes** [comment]
I think you're referring to the way of toggling other/more categories - whereas these will always be visible, so not sure it would apply.

fwiw, imho, i can't see anything I would do differently to Dan's pic above.

**Comment by emilyfildes** [comment]
Hello - just to agree with @jamieu , that is also what I expected to see for nested galleries (and checking / un-checking behaviour)

One note on the design is that gallery names could be quite long e.g. Mathematics: The Winton Gallery -- so may wrap across two lines? Or truncation?

**Comment by Danwhy** [comment]
Yeah, long names wrap across two lines:  
<img width="295" alt="screen shot 2016-10-21 at 15 05 01" src="https://cloud.githubusercontent.com/assets/8939909/19601115/c7e15a50-979f-11e6-8633-6c6b1d851656.png">

**Comment by jamieu** [comment]
OK I'll take @tobystokes line on the design, looks good as it is 👍

**Comment by emilyfildes** [comment]
That looks great!

**Comment by jamieu** [comment]
Perfect, works really well!
