### ISSUE TITLE
Remove link from "Unknown..."

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#502]
We still want to display these makers and users, as there is relevance in the fact that "we don't know who the maker is". But if the word **"Unknown", "Unidentified" or "Unattributed"** appears in the name we don't want to display it without a link (as it serves no purpose).

_\* It tends to indicate we have researched the maker and not been able to identify them as opposed to one just not being assigned_

<img width="737" alt="screen shot 2016-10-20 at 16 12 40" src="https://cloud.githubusercontent.com/assets/91365/19566231/6ada57d0-96e1-11e6-9573-ee94d24e3e83.png">
<img width="823" alt="screen shot 2016-10-20 at 16 20 43" src="https://cloud.githubusercontent.com/assets/91365/19566232/6afaed2e-96e1-11e6-976c-87d4c7ffe3bb.png">

**Comment by jamieu** [comment]
Oh yes, sorry I didn't see #501 and yes, I think we do now want to show it, just without the link (sorry!)

**Comment by Danwhy** [comment]
No problem, I think the old issue did specify that, I just didn't read it close enough

**Comment by jamieu** [comment]
If it's not to tricky could we replace / display:

"Unidentified maker" -> "Unidentified"
"Unattributed maker" -> "Unattributed"
"Unknown maker" -> "Unknown"

So it reads better on the page.

I need to get final agreement on whether we  can reduce these all down to one, but for now the above is probably safest.

**Comment by jamieu** [comment]
Nice
