### ISSUE TITLE
JSON appearing when using back button from external page

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#504]
If you use the back button to come onto a page after navigating somewhere else, if the last page you visited was formed by a json request, the page will just display the raw json instead of the html.  

After a bit of investigating I found that this was a Chrome issue, where it caches the requests, and gives you the most recent one when you use the back button.

Working on a fix now

**Comment by SimonLab** [comment]
reopen this issue link to #601
