### ISSUE TITLE
Errors due to new data structure of index

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#513]
The ids of items have completely changed format, from `smgc-object-209954` to `co209954`.
This has broken a few things where we expect the old format

New format:  
First letter:
smga -> a
smgc -> c  
Second Letter:
agent/people -> p
object/objects -> o
documents/archive -> a  
Numbers:
same id as before

so `smgc-object...` would become `co...`, `smga-agent...` would become `ap` etc

**Comment by SimonLab** [comment]
resolved with #517
