### ISSUE TITLE
Splitting out occupations

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#514]
Occupations are now split, be good to get the code to reflect this / link them individually.

_Although we still have the original in there, which I have flagged, of now we can just show it._

"occupation": [
" computer pioneer",
"mathematician",
"mathematician; computer pioneer"
],

**Comment by SimonLab** [comment]
Now that the occupations are split we need to display all the instances on the person page and not just the first one

**Comment by SimonLab** [comment]
resolved with #519

**Comment by jamieu** [comment]
Leaving this open to remind me to get the index changes and the short term fix reverted.

**Comment by jamieu** [comment]
Closing as the reminder is on https://github.com/TheScienceMuseum/collectionsonline/issues/532
