### ISSUE TITLE
autocomplete hidden on home page

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#521]
![autocomplete hidden](https://cloud.githubusercontent.com/assets/6057298/19735116/17850b78-9ba2-11e6-9f72-075e08d9c1f9.png)

@tobystokes do you think it's a problem with the images, or the autocomplete?

**Comment by tobystokes** [comment]
bah, its a z-index issue either way.

**Comment by SimonLab** [comment]
resolved with #520
