### ISSUE TITLE
Delete wrong occupation filter

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#524]
- [ ] The occupation values are now split so we don't won't to display the previous version of this value:
  ![occupation-filter](https://cloud.githubusercontent.com/assets/6057298/19766928/4ed3028c-9c48-11e6-9b00-8d9c5787ed6e.png)
- [ ] The new values of the occupation filter don't return any result, to investigate and to fix!

**Comment by SimonLab** [comment]
The second point is because the values in the database still have a space in from of the name but we are trimming the value to avoid unnecessary space so our term filters in elasticsearch can't match the two values see #518

**Comment by jamieu** [comment]
LGTM
