### ISSUE TITLE
Facets still selected when no filters selected

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#526]
When the last filter of a facets is unchecked the facet keep being active (blue color instead of white). It works fine when the facets is cleared with the clear facet link (name of the facet):
![selected-facet](https://cloud.githubusercontent.com/assets/6057298/19767186/86707b6a-9c49-11e6-8b72-cd4fbfa3ad7b.png)

**Comment by jamieu** [comment]
LGTM!
