### ISSUE TITLE
revert occupation filter format value

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#532]
When the data of the occupation is clean we need to revert the code from the PR #528 , linked to issue #524 
see also #518

**Comment by jamieu** [comment]
@SimonLab any reason I can't close this? I assume the index is now ok?

**Comment by SimonLab** [comment]
Yes I think the index should be ok now, @Danwhy can you confirm?

**Comment by Danwhy** [comment]
:+1: Yep, I think you're right
