### ISSUE TITLE
Add short musum url to client side

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#538]
Page.js should intercept the routes for the short url of the museum (/scm /msi /nmem /nrm) otherwise it will display the 404 error page before redirecting to the search page. The short url links are at the moment used on the home page:
![home-page-links-museum](https://cloud.githubusercontent.com/assets/6057298/19784039/214da544-9c8c-11e6-9f09-be9e683ac7d1.png)

**Comment by Danwhy** [comment]
I don't think this should happen. The redirect happens on the server, and changes to the expected url with filters, so the client never sees the short route

**Comment by SimonLab** [comment]
Page.js try to catch the urls but they are not define yet so it will display for a short period of time the error page and then it will redirect to the right search page.

**Comment by Danwhy** [comment]
No doesn't happen on either local or the live site for me

**Comment by SimonLab** [comment]
I'm pretty sure it redirect after displaying the 404, I just checked on the staging area and it does the same, your js is not disable? I think my connection is a bit slow and that might be why it doesn't appear on yours. But I'll check again all the logic to be sure.

**Comment by Danwhy** [comment]
Yeah I'm not seeing any flash at all. What url are you using?

**Comment by SimonLab** [comment]
from the home page I click on one of the 4 links from the section "See what’s on display". @jamieu @iteles @nelsonic can you see the error page or it's just me?

**Comment by Danwhy** [comment]
Ah ok, that makes sense. I didn't realise they were using those links. We can just change those links to use the longform url, I was thinking the short urls would only be used externally

**Comment by SimonLab** [comment]
yes we can use the long form. Also it might be worth to add a redirection (page.show('longformur')) in page.js just in case if the short url will be used more often later on.

**Comment by jamieu** [comment]
Perfect!
