### ISSUE TITLE
footer banner links

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#539]
Are there any existing links that we can add to the footer banner?
![footer-links](https://cloud.githubusercontent.com/assets/6057298/19782409/ab162140-9c85-11e6-9dc4-41a50e289017.png)

```
module.exports = {
  image: {
    url: '/assets/img/global/logo-smg.svg',
    alt: 'Science Museum Group',
    link: ''
  },
  links: [
    {
      name: 'About the Science Museum Group',
      url: ''
    },
    {
      name: 'Privacy and Cookies',
      url: ''
    },
    {
      name: 'Terms of use',
      url: ''
    },
    {
      name: 'Copyright and licensing',
      url: ''
    }
  ]
};
```

**Comment by jamieu** [comment]
Well spotted...here goes,

*About SMG*
https://group.sciencemuseum.org.uk/about-us/

*Privacy and Cookies*
https://group.sciencemuseum.org.uk/privacy-policy/

*Terms of use*
https://group.sciencemuseum.org.uk/terms-and-conditions/

*Copyright and licensing*
https://group.sciencemuseum.org.uk/business-services/picture-library/

**Comment by jamieu** [comment]
Looks good
