### ISSUE TITLE
Style the "visit museum" links in "on display" widget

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#54]
<img width="447" alt="screen shot 2016-06-20 at 12 57 34" src="https://cloud.githubusercontent.com/assets/91365/16193351/a06ef230-36e6-11e6-80c4-200c47115979.png">
- link to the relevant gallery page (this will be based on location/museum code and need to be mapped via a mapping file to the relevant link; high level galleries only, all others will link to the museum home page)
- link to the relevant museum's "visit us" page (this will be based on location/museum code and need to be mapped via a mapping file to the relevant link)
- link to the relevant museum's floor plan PDF (this will be based on location/museum code and need to be mapped via a mapping file to the relevant map; high level gallery floorpans only)

**Comment by jamieu** [comment]
@tobystokes I need to find an example of something on display (which we don't currently have), but did we ever do anything here? Might just be a case of tidying up the CSS.

**Comment by tobystokes** [comment]
I don't remember, so guess not - if you can find me an example or two, i'll take a look.

**Comment by iteles** [comment]
On hold until we have the information we need.

**Comment by jamieu** [comment]
Closing for now
