### ISSUE TITLE
link to home page?

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#540]
There are no links which can redirect to the home (the "/" endpoint) after a user start a search. Do we want to add a sort of a "home button/link" or this is not useful or good UX?

**Comment by jamieu** [comment]
I did think about that / discuss it with @tobystokes, but not sure where it
would go or if it would be really useful as users can run a search on any
page.

Maybe in future if the homepage offers more groupings and canned searches
it's something we can revisit post launch.

So for not, let's not worry.

**Comment by SimonLab** [comment]
sounds good, close for now and we can reopen if needed
