### ISSUE TITLE
Add label for pillbox

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#544]
- [x] OnDisplay
- [x] Archive

**Comment by jamieu** [comment]
<img width="403" alt="missing-on-display-prefix dupe issue" src="https://cloud.githubusercontent.com/assets/91365/19803220/6737290e-9cff-11e6-89b8-055d99b328c1.png">
<img width="682" alt="subsequent-pillbox-missing-prefix" src="https://cloud.githubusercontent.com/assets/91365/19803228/75887166-9cff-11e6-8b54-ab5fab808377.png">

**Comment by jamieu** [comment]
Yeah! Like it 👍
