### ISSUE TITLE
Autocomplete not displaying people/companies

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#545]
<img width="645" alt="auto-complete-missing-names" src="https://cloud.githubusercontent.com/assets/91365/19802843/78d001e2-9cfd-11e6-93d1-2115db2df2a4.png">

**Comment by SimonLab** [comment]
same issue describe [here](https://github.com/TheScienceMuseum/collectionsonline/issues/552#issuecomment-256893765)

**Comment by jamieu** [comment]
Looking good 👍
