### ISSUE TITLE
Design: make the 'clear all' box stand out more

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#546]
Do you think we can do anything here, to make it have a higher ranking than the individual car boxes?

<img width="401" alt="design-make-clear-all-stand-out-more-texture" src="https://cloud.githubusercontent.com/assets/91365/19802862/9ff15e06-9cfd-11e6-805b-2f95d8996ea7.png">

**Comment by tobystokes** [comment]
BTW, looks like a more common approach would be to say 'Reset all filters' rather than clear, agree?

**Comment by tobystokes** [comment]
![image](https://cloud.githubusercontent.com/assets/109024/20625048/9281c78a-b308-11e6-9d3d-35e355fdaff2.png)
 ?
