### ISSUE TITLE
Lose extraneous text from mobile version/viewport

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#550]
For now --> Lose the "etc." from mobile version (or both views if easier).

We can then close this ticket..

---

But ... @tobystokes and @emilyfildes how do you feel about losing the whole line "Search object and people" and the "Explore over 150,000..." on mobile? 

@tobystokes is it tricky to suppress the first paragraph of overlaid text on mobile devices and have the height collapse down?

<img width="476" alt="lose this text on mobile" src="https://cloud.githubusercontent.com/assets/91365/19803033/790adc9e-9cfe-11e6-8bce-777125ef82cf.png">

**Comment by tobystokes** [comment]
The top text is a mobile-only replacement for the standard placeholder text, see #95
(sadly i can't alter the placeholder attr text for screen size)
I think that is worth keeping as it's the only instruction about what you can search for.

The Explore.. ¶ could definitely go, and is a simple media query to hide for small.

**Comment by jamieu** [comment]
OK then, based on @tobystokes comment:

- [ ] lose the ".etc" at end (but leave the rest of the line)
- [ ] suppress the "Explore.. ¶" when on small screen sizes..
