### ISSUE TITLE
Some taxonomy terms have no results

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#551]
While I can see how this could occur on nested/parent taxonmoy terms (and that is a much longer term issue, that we can live with for now). But I'm not sure how it is happening on single terms.

Surely, if this record is tagged to `commercial records and equipment`
https://collection.sciencemuseum.org.uk/objects/co483996/the-silver-jubilee-poster

Then this results query should return it? But instead it returns a no-reulst page?
https://collection.sciencemuseum.org.uk/search/objects/object_type/commercial%20records%20and%20equipment

<img width="566" alt="screen shot 2017-07-10 at 16 23 44" src="https://user-images.githubusercontent.com/91365/28025773-307ec72c-658c-11e7-85d8-bd52d9bde9d5.png">
<img width="429" alt="screen shot 2017-07-10 at 16 23 48" src="https://user-images.githubusercontent.com/91365/28025772-307cd516-658c-11e7-977c-c42c1004943d.png">

**Comment by Danwhy** [comment]
Taxonomy and Object type are two separate fields in the index, and we're not pulling through any data from taxonomy for the filters on the search page. It _might_ be possible to combine object type and taxonomy on the serp page filters, but it would probably add a lot of complexity. It might be better to just remove the link to the serp from the taxonomy.

**Comment by jamieu** [comment]
For now let's just remove the links form the taxonomy (to save confusion).

But be good to open up a new issue for what is involved in combining object names and taxonomy terms - although they are separate in the index they are effectively the same from the users point of view (and to some extent at the point of the original data entry).
