### ISSUE TITLE
Weight on display items higher

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#552]
This works fine for the "objects" tab but in the "all" tab, the archive documents come before an on display object. The "on display" object should almost always come first (unless we have a near direct match on title or accession no.).

<img width="770" alt="weight-on-display-higher-1" src="https://cloud.githubusercontent.com/assets/91365/19803653/c4b6cdf8-9d01-11e6-9063-78f140aa90b8.png">
<img width="863" alt="weight-on-display-higher-2" src="https://cloud.githubusercontent.com/assets/91365/19803652/c4b67bb4-9d01-11e6-9820-e3777a83c50c.png">

**Comment by Danwhy** [comment]
This seems to be a problem with the summary_title_text field. I'm not sure exactly what the problem with it is, but some of the archives are being boosted by an excessive amount.

We can get around it for now by just using the summary_title field, or one of the others such as summary_title_stem.

It seems the summary_title_text field has a built in boost, but I'm not sure why it's only affecting archives. Needs more investigation.  
<img width="253" alt="screen shot 2016-10-28 at 12 01 30" src="https://cloud.githubusercontent.com/assets/8939909/19804450/516236ee-9d06-11e6-8845-e19d9c72f789.png">

**Comment by jamieu** [comment]
Are you still waiting to deploy the interim fix? (in the interim, till we find out why the archives are posted so much). Still seeing the archives/docs take precedence (even with a 'show all' query).

<img width="1172" alt="screen shot 2016-10-31 at 15 52 36" src="https://cloud.githubusercontent.com/assets/91365/19860794/18e4765a-9f82-11e6-9f3f-4819ca149b37.png">

**Comment by jamieu** [comment]
This still doesn't seem be working, Rocket is on display but still appearing half way down the SERP page?
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/search?q=rocket

http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/co8084947/stephensons-rocket-steam-locomotive

**Comment by jamieu** [comment]
Looking/working much better now.
