### ISSUE TITLE
Clicking JSON link takes me to 404 page (in addition to downloading data)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#562]
Might just be a Safari thing..

<img width="310" alt="screen shot 2016-10-28 at 16 36 07" src="https://cloud.githubusercontent.com/assets/91365/19812286/d4be467e-9d2c-11e6-8ecc-4b8698b145fa.png">

<img width="951" alt="screen shot 2016-10-28 at 16 36 13" src="https://cloud.githubusercontent.com/assets/91365/19812237/aab51038-9d2c-11e6-943a-5813dde3460b.png">

**Comment by iteles** [comment]
Confirmed that this *doesn't* happen in Chrome or Firefox.

**Comment by SimonLab** [comment]
This also happen very quickly on the other browsers before the page redirect to the json content. Just need to add the /api routes to page.js

**Comment by SimonLab** [comment]
The PR #564 should resolve this issue

**Comment by jamieu** [comment]
LGTM
