### ISSUE TITLE
Print style sheet (suppress thumbnails / only show key image) 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#567]
Given that may of our users still work in a dead tree world, would be great if we could ensure that the 'printed' version of our pages looks as nice as the desktop and mobile versions.

The bottom of the page actually looks pretty good, but if we could suppress the thumbnails, the carousel and it's buttons and all other images other than the key image/scan we'd be 95% the way there to having a perfect print version.

<img width="215" alt="screen shot 2016-10-31 at 13 19 48" src="https://cloud.githubusercontent.com/assets/91365/19855553/20e1ff22-9f6d-11e6-8a14-2ee275ba76b3.png">
<img width="213" alt="screen shot 2016-10-31 at 13 19 53" src="https://cloud.githubusercontent.com/assets/91365/19855552/20c5ac1e-9f6d-11e6-9e82-df464b22d065.png">

**Comment by tobystokes** [comment]
review how big image uncarousels.
and maybe page breaks ?

**Comment by jamieu** [comment]
Closing
