### ISSUE TITLE
Modifications and handover of Image Carousel / Zoom

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#57]
Clicking an image (or expand icon) in the carousel should:
- snap to full-browser window view
- toggle to a single deep zoom mode/viewer for the clicked (or currently focused) image 
- update icons/buttons, as below

In deep zoom mode:
- The thumbnails bar should allow navigating though the images (in the zoom viewer)
- A plus and minus magnifying glass icons shock appear (for use with deep zoom)
- A icon to toggle out of full-browser mode and back to the standard carousel view
- The addition of a 'TV set' style full screen icon (to expand deep zoom view to completely full screen) - need to test to see if users find this confusing.

Need to ensure any CSS/JS/ZoomFeatures (that is better implemented as part of the new templates) is documented and clearly handed over. With everyone clear what is left to do, so that we can schedule in time to do the final bits of integration work.

**Comment by iteles** [comment]
Newer thinking on this in #369
