### ISSUE TITLE
Images for twitter/facebook cards

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#570]
Reminder to add images to the facebook/twitter meta tags when images are back in the index.

**Comment by jamieu** [comment]
Looks good, need to make sure we test before launch (in fact let me know on Slack and we can take the auth off for an hour to test).

Here's are a couple of Twitter / OpenGraph validators
https://cards-dev.twitter.com/validator
http://validator.w3.org/#validate_by_input
http://opengraphcheck.com/
http://iframely.com/debug/

**Comment by jamieu** [comment]
Cards don't seem to be validating?
http://collection.sciencemuseum.org.uk/objects/co26704/rocket-locomotive-steam-locomotive

<img width="1064" alt="screen shot 2016-12-02 at 16 03 42" src="https://cloud.githubusercontent.com/assets/91365/20840784/4e0be558-b8a9-11e6-9fea-ccde905d87a0.png">

**Comment by jamieu** [comment]
Validating nicely for Twitter & OG - looks cool too :-)

But getting a `"No Character encoding declared at document level"` error from http://validator.w3.org/check.

And a 406 HTTP error from http://iframely.com/debug/ (not the end of the world - but be good to check why we're getting a [406](http://www.checkupdown.com/status/E406.html) back).

Not showstoppers, but be good to cast an eye over both of them.
