### ISSUE TITLE
site not working on Internet Explorer 11

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/collectionsonline#574]
After some investigation it seems Object.assign and Promises were throwing errors for ie11.

As we're already using babel for some transformations, we're going to add polyfills for these methods for now, we'll look into better solutions in the future.

**Comment by nelsonic** [comment]
@Danwhy 
+ https://www.npmjs.com/package/object-assign
+ https://github.com/then/promise

Prefer to be _specific_ instead of loading the _monster_ that is Babel Polyfill and force users to download a potentially _large_ bundle they won't need ... 😕

**Comment by Danwhy** [comment]
I agree it will be better to be specific. There are some more problems other than those two though. We're investigating some more now...

**Comment by SimonLab** [comment]
I'm currently doing more tests on a real IE 11, and it seems that document.activeElement that we use [here](https://github.com/TheScienceMuseum/collectionsonline/blob/b941963f371031e58604187a0bbd698c8d5ac65a/client/lib/hide-keyboard.js#L3) to hide the keyboard on IOS returns undefined so the function blur can't be applied and returns an error which break the application. A simple solution is to just check that the value is not undefined before applying blur

**Comment by jamieu** [comment]
LGTM
