### ISSUE TITLE
We seem to have lost relevance / ranking

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#578]
Puffing Billy [1862-2]
/objects/co26701/locomotive-puffing-billy-with-tender-10-fish-bellied-rails-12-chairs-6-sleepers-shovel-3-firing-irons-steam-locomotive

Is 'on display' and tagged with a category 'Locomotives and Rolling Stock' ([which is a boosted category](https://github.com/TheScienceMuseum/collectionsonline/wiki/Ordering-and-relevance)), but it's appearing at the bottom of the SERPS page. 

Any idea what has changed?

**Comment by iteles** [comment]
@danwhy was talking about this on Friday. One of the things we've noticed is that the relevance has been doing some odd things as the index has changed. I would suggest it's our highest priority for when the new index comes in and we do our final sprint. 

Or do we need to allocate some days to look into this sooner @jamieu?

**Comment by jamieu** [comment]
Agree, lets leave it till we have the (hopefully) final pre-launch /
launch index
in place.

**Comment by jamieu** [comment]
Priority for order:

- Location
- Image

**Comment by jamieu** [comment]
If I do a filer on gallery alone, I'm still seeing records with no images showing before those with records. ie. this search for objects in a gallery.
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/search?filter%5Bmuseum%5D=Science%20Museum&filter%5Bgallery%5D=Winton%20Mathematics%20Gallery&page%5Bsize%5D=50&page%5Btype%5D=search

**Comment by jamieu** [comment]
Much better - closing this ticket, but lets pick up default order (past the image and location).
