### ISSUE TITLE
Link the on display location (on object page) back to SERPS page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#581]
Can we change this so that museum/gallery links back to the SERP page (with the gallery and the parent museum selected).

The whole string "Museum: Gallery" should be a single link to a filter by gallery.

<img width="415" alt="screen shot 2016-11-03 at 17 31 45" src="https://cloud.githubusercontent.com/assets/91365/19977484/a4c26018-a1eb-11e6-9e6a-95d3605324f4.png">

**Comment by jamieu** [comment]
@SimonLab Not seeing this on staging, is it still in a specific branch?

**Comment by SimonLab** [comment]
I think it hasn't been deployed due to ab error during the tests on master branch,  it should be resolved on the next PR

**Comment by jamieu** [comment]
Perfect
