### ISSUE TITLE
Dates are behaving strangely

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#582]
- [ ] Date field not being populated from search query url
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/search?filter%5Bdate%5Bfrom%5D%5D=1892&page%5Bsize%5D=50&page%5Btype%5D=search
- [ ] Results of a date filter are returning results that don't match the date range (see second screenshot) - the first result has a single year which doesn't match the date range.
- [ ] Date box remains closed when a search is re-run.
- [ ] In some case the date is showing correctly for the 'from' but the 'to' is todays date see screenshot).
- [ ] Date related error message appearing

<img width="1125" alt="date-bug-nov-9th" src="https://cloud.githubusercontent.com/assets/91365/20148756/f5d72d94-a6a5-11e6-9dae-35aa1adf80df.png">

<img width="1145" alt="screen shot 2016-11-09 at 17 54 36" src="https://cloud.githubusercontent.com/assets/91365/20148670/a3c5e432-a6a5-11e6-8e22-42bc41ab145a.png">

<img width="427" alt="screen shot 2016-11-09 at 17 59 16" src="https://cloud.githubusercontent.com/assets/91365/20148808/44cbe93a-a6a6-11e6-8a5e-c65253bffb60.png">

**Comment by Danwhy** [comment]
I've managed to get the date filters to return the correct results, but I had a question about the exact logic we want to use.

For objects there's no problem, there is one date, the creation, and any item that was created in the specified date range is returned.

For people though, we need to decide what results to return:
 * anyone who was born in the date range
 * anyone who died in the date range 
 * anyone born and died in the date range
 * anyone that lived for any period in the date range
 * anyone who lived through the whole date range 

And what if only one date is entered?
 * first date box:
   * Anyone that was born in that particular year
   * Anyone who was born after that year
   * Anyone who was alive in that year
 * second date box:
   * Anyone who died in that year
   * Anyone who died before that year 
   * Anyone who was alive in that year

My opinion is that we should return anyone that lived for any period between the dates (so if a user enters 1900 - 1999, anyone who was alive at any time in the 20th century would be returned). I'm not so sure about what to do with only one date though, maybe return anyone that was alive in that year. @jamieu thoughts?

**Comment by jamieu** [comment]
Much better 👍 

@emilyfildes do you want to cast an eye on this before closing it?

**Comment by emilyfildes** [comment]
Hello - looks  massively improved!

There are still a couple of oddities (e.g. see /search?filter%5Bdate%5Bfrom%5D%5D=1970&filter%5Bdate%5Bto%5D%5D=1970&page%5Bsize%5D=50&page%5Btype%5D=search). 

This is a search from 1970 - 1970, but objects are showing outside of the dates. Is this because there are other dates in the JSON file still? e.g. /api/objects/co417328

**Comment by jamieu** [comment]
Ah yes, could well be - the new index has almost finished processing, so
remind me to re-check tomorrow (post updated index) to be sure.
