### ISSUE TITLE
Update URL when a filter is selected/results are refreshed on SERPS page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#587]
It would be good if the URL updated when the search results update, as many of our users bookmark or cut/paste urls for their current result set.

(tbh. I thought we had done this, but if we did it doesn't seem to be working)

**Comment by SimonLab** [comment]
@jamieu do you have some steps to reproduce this issue? I've tried to repoduce it but the url is updated on a new search or when the filters are used. Do I look at the right changes?

**Comment by jamieu** [comment]
@SimonLab it seems to be working fine for me again, closing - buy will key an eye out for an example if I spot it again.

(btw. thanks for investigating anyway)
