### ISSUE TITLE
Add gallery name to 'on display' pill box 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#589]
If a gallery is selected (will obviously be hugely truncated so we'd ideally display the full name if a user hovered over the pill box).

**Comment by SimonLab** [comment]
@jamieu were you thinking of something like this:
![truncate-pillbox](https://cloud.githubusercontent.com/assets/6057298/20604447/44292b5a-b25e-11e6-8f64-c2c689cb77a8.png)
(gallery: Search Engine Exhibition Area2)
We can decide when to truncate the name, at the moment the limit is 40 characters, does this sounds right?

**Comment by jamieu** [comment]
That look perfect, thanks :-)

**Comment by jamieu** [comment]
👍
