### ISSUE TITLE
Add stubs pages/routes for Locations and Places

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#59]
- Places = a geographical place
- Location = a location in the museum (in the backend collection systems and index this is known as a 'facility')

Currently work is in progress @ SMG on consolidating and cleaning up these objects, so that only the cleaned up public records are made public. 

For beta-launch it is highly likely we will bypass these templates and just send users back to the SERPS page. But having the routes/stubs in place now will ensure we can quickly enable pages for them when the data is ready.

_In terms of templates, both will be a minor variation on the Person template. With the page displaying a summary set of objects / documents / people related to the place/location; with a link back to the SERPS page for the full set of results. Given we don't yet have data to display, the focus for now should be on the routes/stubs, rather than perfecting the templates (which we can revisit once we have actual data to display on them)_

**Comment by iteles** [comment]
@jamieu to follow up on the work being done with the index at the moment and a decision to be made for sprint 6 on priority.
