### ISSUE TITLE
Add a 'beta' bar to top of site

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#599]
Something as simple as this, unless @tobystokes hates it and has a better idea :-)

![beta-bar](https://cloud.githubusercontent.com/assets/91365/20538300/80a0ea7c-b0e8-11e6-9cd6-86c3032cf667.jpg)

_URL to be supplied, just link it to the main site for now._

**Comment by tobystokes** [comment]
Yeah, except maybe explain what beta is:
"This new site is still being tested and improved"
(inspired by https://www.gov.uk/help/beta)

It might need to be dismissable if it takes up  lot of space on mobile?

**Comment by SimonLab** [comment]
I've created a first version which looks like this on mobile:
![beta-bar](https://cloud.githubusercontent.com/assets/6057298/20753253/5f080b78-b6fd-11e6-9755-e79ef92045de.png)

I will create a PR soon, @tobystokes please feel free to update the css if needed, you might have a better idea than me on this.

**Comment by jamieu** [comment]
Looks good, a little padding on the left so it light up with search would be great.

**Comment by tobystokes** [comment]
![image](https://cloud.githubusercontent.com/assets/109024/20764882/0d83b92a-b728-11e6-8054-cad4f44b0b4e.png)
I've lessened the difference between the 2 type sizes to make it feel more lined up, and padded as per other rows

**Comment by jamieu** [comment]
Perfect, thanks Toby!

**Comment by nelsonic** [comment]
@jamieu / @tobystokes looks good. 👍 
_related_ to this, what is the plan to _capture_ user-feedback while they are using the Beta?

**Comment by jamieu** [comment]
looks good
