### ISSUE TITLE
Archive pages : Uncaught error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#616]
Error loading archive page (with img?)
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/documents/aa110000176/

<img width="346" alt="screen shot 2016-11-28 at 10 14 12" src="https://cloud.githubusercontent.com/assets/91365/20664510/793c7c5a-b553-11e6-8062-02a07ac3a8c9.png">

**Comment by Danwhy** [comment]
This looks to be the same as #612, which should both be fixed in the PR for the license filters (#470)

**Comment by jamieu** [comment]
Ha...yes, I just noticed that...I'm going mad, will close this one!
