### ISSUE TITLE
People/Companies in Archive filters

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#621]
Was this coded as a feature? 

It would be be **far more useful** to list the people/companies related to the documents shown in the results blocks on the left (and call it People). Or is this simply a change in the index that is causing this?

<img width="317" alt="screen shot 2016-11-28 at 16 55 10" src="https://cloud.githubusercontent.com/assets/91365/20677617/79b3b760-b58b-11e6-8786-b058215bc5c1.png">

**Comment by SimonLab** [comment]
I couldn't find the issue which describe this filter, I think I implemented the feature based on the [wiki description](https://github.com/TheScienceMuseum/collectionsonline/wiki/Facets) but agree it will make more sense to have the list of organisations/people. I'll check the index to see which values we can extract

**Comment by Danwhy** [comment]
I think this filter is relevant/correct for the people tab, it's just appearing in the documents tab now, when it shouldn't be.  

I do seem to remember it working as Jamie described before, though I could be wrong. I can't find an organisation on any archive in the index at the moment, but I don't know if that's because the index has changed, or I'm just mistaken.

**Comment by SimonLab** [comment]
Thanks @Danwhy ! @jamieu can you confirm the logic of this filter, on people category we keep the logic of the filter as it is (split values between "organisation" and "person") and on the document category should we delete this facet as it seems no organiation is linked to any archive?

**Comment by jamieu** [comment]
Ah yes, on archive documents there is no distinction between people and companies (that I am aware of).

But we should list the people/companies relating to the documents in the result set (much like we do with objects). Feel free to split out into a separate ticket if that's easier.
