### ISSUE TITLE
Homepage text

### ISSUE THREAD

**Issue by emilyfildes** [TheScienceMuseum/collectionsonline#622]
Hello, 

@jamieu @tobystokes here are some text updates for the homepage:

_For the on display boxes:_
Science Museum
The home of human ingenuity, exploring stories of scientific achievement

Museum of Science and Industry
The story of Manchester’s scientific and industrial past, present and future

National Media Museum
The science and culture of light and sound technologies, and their impact on our lives

National Railway Museum
Home to the largest collection of railway objects in the world

_For the theme / collection_

Title: Themes from our collection

Art text: Artworks depicting the history of science, technology and medicine over time

**Comment by jamieu** [comment]
👍
