### ISSUE TITLE
Unknown maker - appearing in the filter field

### ISSUE THREAD

**Issue by emilyfildes** [TheScienceMuseum/collectionsonline#623]
Hello,

Unknown maker is appearing as a filter in the search - I think this should be removed, @jamieu ?
![unknown_maker](https://cloud.githubusercontent.com/assets/22834431/20708361/6c78cc7e-b627-11e6-98f7-637892683584.png)

I've assigned as a bug, but feel free to update if it is an index issue instead.

Thanks,
Emily

**Comment by jamieu** [comment]
Yes, agreed...

Can we get this supressed..ta!

**Comment by jamieu** [comment]
👍
