### ISSUE TITLE
Search within a gallery

### ISSUE THREAD

**Issue by emilyfildes** [TheScienceMuseum/collectionsonline#624]
Hello,

This might be related to Issue #589  - however if you:
1. Select a gallery in the search filter (e.g. Science Museum: Mathematics)
2. Search within that gallery (e.g. ACE)
3. You get results from objects which are on display within the whole museum, not that specific gallery

I think you should be searching within that gallery @jamieu ?

Thanks,
Emily

**Comment by jamieu** [comment]
👍
