### ISSUE TITLE
Add thumbnails to related blocks

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#626]
Can we add the thumbnails to the related objects/docs.

[@tobystokes sanity check - design wise, these should have images should't they?]

<img width="872" alt="screen shot 2016-11-29 at 13 32 33" src="https://cloud.githubusercontent.com/assets/91365/20712419/d8e6ebac-b63b-11e6-95c1-6b91efccea80.png">

**Comment by tobystokes** [comment]
They should, if we have images for them!

**Comment by jamieu** [comment]
👍
