### ISSUE TITLE
Odd rendering of arrows on homepage (IE11)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#627]
There might not be be a quick fix for this - but because it's our in-house corporate browser across a large part of the org fixing it kinda high prority.

It is fine if you keep the screen at a narrow viewport, but as soon as you open the page you get the white areas appearing.

@tobystokes any ideas?

![arrows rendering](https://cloud.githubusercontent.com/assets/91365/20718621/3cfc40d2-b651-11e6-8655-99077ed0c649.JPG)

**Comment by tobystokes** [comment]
`vector-effect="non-scaling-stroke"` not supported.
So setting natural svg size to nearer likely render size. this means that the stroke might be a bit thinner than 1 px, but hopefully a reasonable degradation

**Comment by jamieu** [comment]
Hi Toby,

Sounds good, haven't got IE name at me to test, but sounds like pragmatic
solution.

Thanks for jumping on this so quickly, appreciated!

**Comment by jamieu** [comment]
Looks good!
