### ISSUE TITLE
NRM panel is linked to NMeM and vice versa.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#632]
NRM panel is linked to NMeM and vice versa.

**Comment by SimonLab** [comment]
@jamieu do you have a screenshot or a bit more details, is the links are on the home page?

**Comment by jamieu** [comment]
Ah..that was more a reminder to self to investigate fourteen - I think it's
the logo/boxes at the top?

**Comment by SimonLab** [comment]
Yes sorry I wasn't looking properly, I find the links now, thanks.

**Comment by jamieu** [comment]
Cool!

(I was actually going to change them myself once located, but if your on it
already!)

**Comment by jamieu** [comment]
👍
