### ISSUE TITLE
Create page for links in footer

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#635]
On the home page we still have these links which redirect to a 404 page:

- About the collection: https://group.sciencemuseum.org.uk/about-us/collection
- Contact us: https://group.sciencemuseum.org.uk/about-us/collection/contact
- Using our API: https://group.sciencemuseum.org.uk/about-us/collection/api

It would be great if we can fix these pages to avoid some 404 errors

@jamieu @emilyfildes any thoughts on this?

**Comment by jamieu** [comment]
@emilyfildes copying you in as your the 'Webmaster' (or is it WebWizard) for  https://group.sciencemuseum.org.uk/ ;-)

**Comment by jamieu** [comment]
@emilyfildes creating the pages today / tomorrow, just finalising copy for them (will live at those locations).
