### ISSUE TITLE
Update to Dependencies to latest Hapi & Joi ?

### ISSUE THREAD

**Issue by nelsonic** [TheScienceMuseum/collectionsonline#654]
@jamieu a new version of Hapi and Joi have recently been released. From my reading of the release notes there should be a _smooth_ upgrade path for us. We will _have_ to update at some point, the question is:

> Should we consider doing this _before_ Monday's "soft launch"?

see: https://david-dm.org/TheScienceMuseum/collectionsonline

**Comment by jamieu** [comment]
Agree, that looks like a pretty smooth path and given next week we're still beta and very actively monitoring/testing the site it might actually be a good time to spot any issues with the upgrade. 

Assume we can back out of we noticed it really broke something major.

**Comment by SimonLab** [comment]
The only small update we need to do are linked to joi where joi.bolean and joi.date.format have change
