### ISSUE TITLE
Reduce font size for copyright line on mobile (or both?)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#657]
So that it doesn't wrap..

@emilyfildes / @tobystokes any thoughts on this?

![db3f4be2-b884-11e6-9525-8e2859d7ea24](https://cloud.githubusercontent.com/assets/91365/20971868/f57bd520-bc8a-11e6-874f-11a8f97d45de.png)

**Comment by emilyfildes** [comment]
Not crucial - if there is a font-size option that doesn't make it look like a mistake then can go for that. Or a hide / show on mobile so the whole thing is cleaner?

**Comment by jamieu** [comment]
I think just reduce the font on mobile-sized view-ports.

**Comment by tobystokes** [comment]
you'll need to separate out the copyright element from the main caption, but yes agree.
somethign like 
```
@include breakpoint(small only) {  font-size: 75% } //  = 12px
```

**Comment by tobystokes** [comment]
but it's wrapping because there are some hard `<br>`'s in there. That may be coming from the data...

**Comment by Danwhy** [comment]
I think those are just to separate the three lines - caption, copyright and usage

**Comment by tobystokes** [comment]
Ah right.

(A longer term improvement might be to move them both to the Use this image menu if that would be allowed)

**Comment by jamieu** [comment]
Closing for now, let's revisit once the zoom button is back
