### ISSUE TITLE
Question: Show "related by" - based on related_people<->object relationships

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#662]
@emilyfildes do you have thoughts on this?

ie. Florence is related to objects (from object page) but not in reverse.
http://collection.sciencemuseum.org.uk/people/cp85708/florence-nightingale
http://collection.sciencemuseum.org.uk/objects/co8538552/moonstone-seal-in-gold-setting-with-box-seal-artefact
 
Or the lack of back-linking on the 'Worshipful Company of Clockmakers' page
http://collection.sciencemuseum.org.uk/people/cp34315/worshipful-company-of-clockmakers
http://collection.sciencemuseum.org.uk/objects/co8384820/croll-testimonial-silver-gilt-fountain-1870-centrepiece

![unknown-4](https://cloud.githubusercontent.com/assets/91365/20833601/7e25a92a-b888-11e6-8d9a-f97fff677d38.png)

**Comment by emilyfildes** [comment]
@jamieu - presumably at the moment, objects are related as 'makers'?

The short answer is yes - it would be nice to show both 'maker' relationships and 'linked people' relationships e.g. (objects made by.... | object related to.... ) - and including archive once the people have been de-duped.

**Comment by Danwhy** [comment]
Moving this out of the February milestone for now until we come up with a good solution

**Comment by iteles** [comment]
Agreed to spend half a day on this tomorrow to see how far we can get

**Comment by Danwhy** [comment]
Something I had to add for this was a change to the `see more` link. Before, it linked to a search page with the person selected as the maker, but for these objects the person is just related to the objects, not the maker, so the search results would be empty.

I added a function to check if any of the roles for the related object was maker-like, and then linked to the old search link if so, or a normal search for objects with the person as the query if not.

@jamieu You might want to just check and add any roles you can think of that count as a maker in this file here: https://github.com/TheScienceMuseum/collectionsonline/blob/master/templates/helpers/ifcreator.js#L5
