### ISSUE TITLE
Suggestion: break down objects/docs on people&company page by type.

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#665]
This still needs some thought/discussion, don't start on it yet.

Maybe we only do this if more than X results.

- documents (archive document as opposed to objects)
- designer: (as per logic on object page)
- inventor: (as per logic on object page)
- *others*: (as per logic on object page)
- related: everything else

@emilyfildes do you have any thoughts here?

<img width="996" alt="screen shot 2016-12-02 at 12 53 38" src="https://cloud.githubusercontent.com/assets/91365/20834651/5df1f356-b88e-11e6-9064-fa6de11a9eb6.png">

**Comment by emilyfildes** [comment]
Yes, I definitely agree that we should breakdown: 

- objects (where there is a primary relationship)
- documents (where there is a primary relationship)
- objects (where there is a secondary relationship via 'Linked People' tab)

Maker / designer / inventor etc - maybe we need to think where we should or shouldn't be explicit about these relationships

**Comment by iteles** [comment]
A little bit of further work required on this from @jamieu before it can be worked on.

**Comment by Danwhy** [comment]
Decided that we'll include the relationship between the person and the related object (maker, user, designer etc.) in the data being sent through to the frontend, then decide exactly how to display them later.

**Comment by Danwhy** [comment]
The data now comes through to the front end and is available in the "role" field:
<img width="1188" alt="Screen Shot 2019-03-26 at 15 03 41" src="https://user-images.githubusercontent.com/8939909/55096455-d9802c00-50b1-11e9-97b5-cfeaa6a6d052.png">
(screenshot just for illustration purposes, the role isn't actually shown)
