### ISSUE TITLE
Revisit mapping /rest/style/paths to query string style paths  

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#668]
One for post launch, but would like to formulate a plan for this.

ie. `/search/documents?filter[archive]=The%20Babbage%20Papers` becomes `/search/archive/The%20Babbage%20Papers`

and `/search?q=computers&filter%5Bcategories%5D=Computing%20%26%20Data%20Processing&page%5Bsize%5D=50&page%5Btype%5D=search` becomes `/search/categories/Computing%20%26%20Data%20Processing`

etc.

Similar for other filters such as images, categories, locations etc.

**Comment by Danwhy** [comment]
How would this work if more than one pillbox filter (category, museum) was selected?

**Comment by jamieu** [comment]
My thinking would be something like:

/category/art+railways
/category/art,railways

or

/category/art/museum/scm

Does that make sense?

Happy to work out the list of paths/routes - but would love your input on
that. Do you want me to make up some examples (and you can tell me if you
think it won't work or suggest alternatives).

I think it's just the key filters, mainly so that we can i) cut/paste
'tidy' urls ii) create 'hackable' / readable urls for the key filters iii)
allow us to put them in the sitemap as 'landing pages' that Google can then
pickup.

**Comment by Danwhy** [comment]
Ok, yeah that makes sense. I'll just have to have a think about how to parse the urls on the backend, but I should be able to make it work

**Comment by jamieu** [comment]
Cool,

Thinking about it the hierarchy is probably something like:

- museum
- gallery
- category

and maybe an image flag ie. /images (at the end of the path)

**Comment by Danwhy** [comment]
I've managed to parse the urls on the backend, and for now I'm taking the values and plugging them into the query we're currently working with. This means that typing in/linking from the restful style url works, but it still shows in the url bar as the old style with the querystring.

Actually making the restful style urls the canonical urls would require quite a lot of refactoring on both the front and back end, so is this ok for now?

**Comment by jamieu** [comment]
Sounds good, lets tackle this one in stages!!

What you've done so far sound like it's a step in the right direction,
doesn't break any existing functionality and will be easy to build upon.

Also gives us a chance to test the URL's before we make them the default
url's used on the site & appearing in the browser bar.

Do update a page in the Wiki the paths/format you went with.





Jamie

**Comment by jamieu** [comment]
Looking good, just a reminder that the paths/url should all be lowercased.

(_hope that doesn't cause issues_)

**Comment by Danwhy** [comment]
@jamieu Having the url all lowercase is causing some issues. As the index is not analyzed to be case insensitive, using a lowercase term in the url will look for a case sensitive version of that term in the index. This isn't a problem for some filters, as they have a `summary_title_lower` which we can use, but for others, there's no way to search for the exact right case in the index.

**Comment by jamieu** [comment]
If we got the index updated for the other fields in a similar way
(_lowercase version) assume that would work?

If so, what additional fields would we need?

**Comment by Danwhy** [comment]
That should work. Category is the main one we need, I think most of the other filters have a lowercase field. I'm not sure about archive, maker or place though

**Comment by jamieu** [comment]
Thanks @Danwhy -  that was it, seeing the new url structure now - looking good 👍 

I'm getting the index updated (this week) to include case-insensitive values for the key facets. So would be good to get a change for that (lowercase urls) rolled in, at the same time as you update the tests. Will chat will Ines to work out when best to get that all wrapped up, so we can finally deploy this code.

Did @SimonLab  manage to also update the sitemap.xml to include the new routes - as will need to deploy that code at the same time.

Finally, wondering if we should make the old paths redirect to the new path structure - one to think about. Maybe it's not a big issue and Google will respect the urls it gets from the sitemap.xml over the old style query string based one. But would be good to migrate to just one single path structure at some point, just for cleanliness/clarity's sake.

**Comment by Cleop** [comment]
Relates to #867
