### ISSUE TITLE
Page loading spinner

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#68]
_When the user searches and then re-searches, or toggles filters we should display a loading spinner in the results area whilst the request is performed. We’ll also need something for when the user navigates to the object/person/document page whilst the data is retrieved._

Have to think about how we can do this elegantly, not a fan of big loading spinners overlaying the the whole screen (or at least it constantly appearing after every interaction). Prefer to have the relevant navigation//links/checkboxes grey'd out (un-clickable) and a minimal progress spinner appear. Will try to find some examples of where I think this is done well; likewise if you can think of nice examples of this functionaility.

**Comment by tobystokes** [comment]
I think in most situations, it would make sense to leave the existing search results on the page, but have the filters panel in an 'updating' state, then replace search results instantaneously once ready.

I hope that the initial enter search text shouldn't need a loading state before results are returned?

**Comment by tobystokes** [comment]
nice example - change tab on github ;)

**Comment by tobystokes** [comment]
![loading gif](https://cl.ly/2A2U0r3q0T0H/Screen%20Recording%202016-07-06%20at%2004.18%20pm.gif)
That's a crappy gif, 
but experiment with adding class of 'loading' to .searchbar section during progresses?

**Comment by jamieu** [comment]
Subtle (I almost missed it) at first, but I like it :-)

Be interesting to see it on a real page, but beats a spinner any day. Gets my vote.

**Comment by jamieu** [comment]
The pages seem to be loading fine and I'm not seeing the spinner (or need for it).

But be good to double check this is still implemented if needed.

**Comment by iteles** [comment]
@Danwhy @SimonLab Hopefully this should be a quick thing to test?

**Comment by jamieu** [comment]
love the loading bar 👍
