### ISSUE TITLE
Limit Google analytics to production environment

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#680]
[realise this may make GA testing tricky - but maybe we can add a flag (that enables GA tracking) that is only set when in production or if we need to test the analytics in staging].

Can we limit GA tracking to the production environment, otherwise we are in danger of counting a lot of false traffic. Ditto, if we're going any load testing we need to ensure those hits aren't counted.

http://stackoverflow.com/questions/1251922/is-there-a-way-to-stop-google-analytics-counting-development-work-as-hits

We're current excluding the SMG and DWYL networks by IP, but assume we also need to exclude Travis and CodeCov if we are going down the route of excluding by IP.

**Comment by SimonLab** [comment]
To define which application is in production or test you will need to add a new environment variable in .corc file and on ESB: ```NODE_ENV="production"```. If this environment variable is not defined or if the value is different to "production" it will automatically defined to "test" and the GA won't be added to the pages.

**Comment by jamieu** [comment]
Perfect..!

NODE_ENV or co_ NODE_ENV ?

**Comment by SimonLab** [comment]
I think NODE_ENV should work

**Comment by jamieu** [comment]
OK have added to prod. so lets give it a go when we next deploy
(I might need to manually deploy the .zip to prod.).
https://collection.sciencemuseum.org.uk/

**Comment by jamieu** [comment]
Probably unrelated but - https://github.com/TheScienceMuseum/collectionsonline/issues/692
