### ISSUE TITLE
Lightly boost records with 'approved web description'

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#683]
Not sure if we're already doing this, but in the absence of a free-text/query-string could we add a host to any record with an 'approved web description' much as we do with images and on_display.

This will ensure that a site wide search for 'has image' will display objects that have had the most attention (someone went to the effort of adding an 'approved web description' ) and also act as a impetus for the documentation team to add more 'approved web description's' going forward.

**Comment by Danwhy** [comment]
We're currently giving a weight of 1.2 to objects that have options.options1 (which according to #176 is the approved web description).

**Comment by jamieu** [comment]
Yep, that good/correct!

Feel free to close.
