### ISSUE TITLE
Remove magnifying glass from links

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#69]
<img width="459" alt="screen shot 2016-06-21 at 12 34 20" src="https://cloud.githubusercontent.com/assets/91365/16228054/8c6f3b34-37ac-11e6-87fe-57e489eaf3b7.png">

I think that we might be better of removing it completely, otherwise we risk using it inconsistently.

(also the preliminary feedback from users was it wasn't quite clear why it was there or when it appeared)

**Comment by tobystokes** [comment]
add class of `searchlink` if you want them back ever.
