### ISSUE TITLE
Styling of single taxonomy term

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#693]
Not sure if something just hasn't loaded for me / but if we only have a single term it should probably left align. So that it lines up with 'Loan' on the line below (see screenshot) and the Taxonomy label.

<img width="522" alt="screen shot 2016-12-05 at 20 23 17" src="https://cloud.githubusercontent.com/assets/91365/20901055/b420c1ac-bb28-11e6-8427-0be5babc3622.png">

**Comment by tobystokes** [comment]
fixed in #935
