### ISSUE TITLE
Decide what to do about descriptions with URL's

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#695]
Seem like most of these area mis-use of the description field.

Should we suppress these or make them links?

@emilyfildes any thoughts?

(although a reminder to @jamieu that we should be extracting these and those from the notes field as part of the extraction, so that we can nicely link to known sites ie. wikipedia, companies house, Oxford DnB and maybe even pull back data form those sources for display on the page)

- http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/people/cp38841/erwin-schrodinger
- http://collection.sciencemuseum.org.uk/people/cp138574/vladimir-shukhov

<img width="763" alt="screen shot 2016-12-05 at 20 33 59" src="https://cloud.githubusercontent.com/assets/91365/20901394/42ab60d4-bb2a-11e6-9cd4-cf04b64a68d6.png">

**Comment by emilyfildes** [comment]
Hello - my feeling is that they are a nice resource, so would be good to make them links. Would we be able to have way of tracking when they break (potentially)?

**Comment by jamieu** [comment]
Good point!

Yes, I think we should (check them) and do this properly (with some new
design elements).

Not this week, but a high'ish priority one post launch / next steps?

**Comment by emilyfildes** [comment]
@jamieu agree - fairly high-ish as a next things to work on I think as it would be a nice enhancement

**Comment by jamieu** [comment]
Have opened a separate issue re. dealing with the internal ones nicely https://github.com/TheScienceMuseum/collectionsonline/issues/696

But do you think we should suppress actual biographies with urls?

The problem is we can't do it nicely / selectively - well I guess we could try and work out if >50% of the biography text is made of of url(s) - but it's a bit brittle (that is an option though).

Or we can just suppress any biography with a URL.

Or we could embrace them and make them linkable (although if all we have is a linked URL it will look horrible - so it gets a thumbs down from me!).

Or we could leave them as they are, not ideal but maybe more useful than no blog at all?

**Comment by emilyfildes** [comment]
I guess it is whether it is better to have something though ugly (i.e. URLs) vs nothing at all (thin records). 

The risk of suppressing is whether it creates a discord with what people are seeing in MIMSY - and presumably we want to keep those as similar as possible. I'm leaning towards the latter - but that is without seeing how bad it could be!

**Comment by jamieu** [comment]
Closing this issue; let's leave the URL unlinked if they are the the proper biog.

But keeping the other one (https://github.com/TheScienceMuseum/collectionsonline/issues/696) open for a second phase.
