### ISSUE TITLE
Fade out title text rather than use eclipses

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#697]
No entirely sure about this (till I see it), but wonder if it would be nicer to fade the text out with CSS rather than use eclipses.

ie. http://jsfiddle.net/330gjo53/

(_http://stackoverflow.com/questions/12222028/fadeout-last-character-of-text-using-jquery-css3_) 

@emilyfildes do you have any thoughts here?

Also has the bonus, if your not already dealing with it, that the full title remains for accessibility reasons. At least can we ensure that any ALT test uses the full title.

<img width="306" alt="screen shot 2016-12-05 at 21 11 52" src="https://cloud.githubusercontent.com/assets/91365/20902559/8c12b1a0-bb2f-11e6-8a60-9ba00ce06241.png">

**Comment by emilyfildes** [comment]
@jamieu Looks interesting, let's have a look tomorrow - think accessibility is a really good point!!

**Comment by jamieu** [comment]
I think let's do this, although need to work out the char limit so it fades it at end of block/line (_one or two more horas than the example below_). 

http://jsfiddle.net/9mmextsv/

<img width="290" alt="screen shot 2016-12-06 at 12 06 40" src="https://cloud.githubusercontent.com/assets/91365/20925063/810c7ef8-bbac-11e6-83a3-8dc3de5a27c9.png">

**Comment by jamieu** [comment]
@emilyfildes what do you think?

I guess the only danger is if the text size changes then the fade-out starts before the end of the line/RH margin.

**Comment by jamieu** [comment]
Closing for now
