### ISSUE TITLE
Add key SERP results pages / filters to sitemap.xml

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#698]
One to look at once we have tacked the REST'full paths (  https://github.com/TheScienceMuseum/collectionsonline/issues/668 ).

But be good to add the initial SERPS pages for the museums, galleries and categories to the sitemap.xml 

ie. 

- /musuem/sciencemuseum
- /musuem/sciencemuseum/gallery/making+the_modern+world
- /category/railway+posters
- /category/art

We should also look at how we can give those pages nice <titles> that just show the name of the main filter ie. /category/art would be "Art | Science Museum Group Collection" (have opened an issue here https://github.com/TheScienceMuseum/collectionsonline/issues/699)

**Comment by SimonLab** [comment]
@jamieu do we want to collect **all** the possible values for the filters before adding the url to the sitemap or do we want to only add the main values of the url?

For example the category filter will have at least these values (we only display the top 10 most used values):
![category-values](https://cloud.githubusercontent.com/assets/6057298/22791119/40307c4c-eee0-11e6-8da5-b6714dfb813c.png)

We will need to write a new script/lambda for each type of filters to collect all the possible values.

**Comment by jamieu** [comment]
These should be redirects but routes

ie. category/photographs should be equivalent to ?category=photographs

In other words we should use a reg-ex for the route so what follows
/museum/ or /category/ (or museum/scm/category/photographs) becomes the
value?

Jamie

**Comment by jamieu** [comment]
Sorry, should not simply be redirects (based on a pre compiled list) but
routes that match patterns in the URL and use the values as paeans/values.

**Comment by jamieu** [comment]
Apologies, just realised your question is related to the sitemap specifically..

These are the four we need, last one might be slightly more tricky 

- Museums `/museum/X` ("On display at X museum")
- Galleries in museum `/museum/X/gallery/X` ("On display in X gallery at X museum")
- Categories `/category/X' ("X")
- Categories on display at X [of the four] museums `/museum/X/category/X'  ("X display on display at X museum")

(I think @Danwhy already has the paths/titles working pretty similar to below, so let's keep those as they are - happy with what Dan has done there even if they differ slightly to my text above).

**Comment by jamieu** [comment]
LGTM 👍
