### ISSUE TITLE
Tool tips on icons

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#71]
I know we discussed this yesterday, need to ensure correct hover-over tool tips are incorporated in the final templates. 

If we think this is better handled as part of final handlebars.js template integration need to re-assign this ticket.

<img width="308" alt="screen shot 2016-06-21 at 12 58 31" src="https://cloud.githubusercontent.com/assets/91365/16228949/e0503eec-37b1-11e6-91b9-cb210596a831.png">

<img width="217" alt="screen shot 2016-06-21 at 13 13 46" src="https://cloud.githubusercontent.com/assets/91365/16228963/02c5992c-37b2-11e6-8f01-963bfee3e055.png">

**Comment by tobystokes** [comment]
I'm not sure they can be tooltipped (as title attributes) unless that title is added to a link - and the icons are generally not linked, or as on the resultcards, nested in a larger link area....
