### ISSUE TITLE
Investigate carousel touch/scroll on mobile

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#710]
I expect there isn't much we can do about this - certainly not this week / low priority for now.

But would be good to have a look / think at how we could reduce the touch area on the carousel so that a downward scroll with your thumb doesn't get mis-interpreted as a sideways scroll.

<img width="750" alt="screen shot 2016-12-07 at 16 18 26" src="https://cloud.githubusercontent.com/assets/91365/20975912/ce900626-bc98-11e6-9ea1-6cdeff08d9d4.png">

**Comment by tobystokes** [comment]
they may not be even needed on mobile if swipe is obvious.

**Comment by jamieu** [comment]
@tobystokes that's a good (and so obvious I missed it) point.

If we can just drop the arrows on mobile - and in doing so widen the area for down scrolling - we should do that.

_Need to ensure that removing the arrows does 'widen the area for down scrolling' otherwise we'd be back where we started but with no indicator as to why the down scrolling only works in the very middle of the screen._
