### ISSUE TITLE
Text/pop-up for non-cc images 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#714]
In these cases we should drop the CC license block but keep the SSPL links (see second screenshot).

http://collection.sciencemuseum.org.uk/objects/co61049/ready-reckoner-ready-reckoner-magazine-periodical

<img width="360" alt="screen shot 2016-12-07 at 19 04 24" src="https://cloud.githubusercontent.com/assets/91365/20982356/146d8706-bcb0-11e6-9adb-27e425abf3d8.png">

<img width="382" alt="screen shot 2016-12-07 at 19 06 25" src="https://cloud.githubusercontent.com/assets/91365/20982403/470996fa-bcb0-11e6-8d34-c9d59609c015.png">

**Comment by Danwhy** [comment]
We're currently only displaying the SSPL links if The Science Museum is the copyright holder (https://github.com/TheScienceMuseum/collectionsonline/issues/414), is that still what we want to do?

If so, if an image has no licence and SMG isn't the copyright holder, should we just lose the 'use this image' button?

**Comment by jamieu** [comment]
- only displaying the SSPL links if The Science Museum is the copyright
holder : YES (keep that logic)
- if an image has no licence and SMG isn't the copyright holder : YES (lose
the links)
