### ISSUE TITLE
Images being squashed on mobile

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#716]
Assume the image/carousel height is too high on mobile viewports?

![img_1369](https://cloud.githubusercontent.com/assets/91365/21044152/5c0eba6a-bdf2-11e6-8244-f32fc73bd39d.PNG)

**Comment by jamieu** [comment]
btw. if this is an easy fix then it's very high priority.

**Comment by tobystokes** [comment]
Assuming you still want images to fit the avaialble space (because if not, we'll end up with a gap somewhere) these naturally more landscape images will end up being cropped slightly to fill the space.  
if this is amenable (and i think it's generally the best fix, then add)
```
.carousel__image {
	object-fit: cover;
}
```

n.b. not supported on IE, but at this screen size, its all iOS or android.

**Comment by Danwhy** [comment]
That seems to work quite nicely. I think if we also reduce the height of the carousel on mobile screens, that should reduce the amount of the image that gets cropped out (and will also help with #710 by making it easier to scroll)

**Comment by tobystokes** [comment]
Yes, maybe the carousel images  should have a `max-height: 75vh`
i.e. never more than 75% of the viewport. (that's an untested suggestion though)

**Comment by jamieu** [comment]
This is working great on pages with multiple images. But not those pages with a singing images.

i.e.
http://collection.sciencemuseum.org.uk/objects/co163555/carbolic-steam-spray-used-by-joseph-lister-england-1866-1870-carbolic-spray

**Comment by tobystokes** [comment]
For a single image, where you probably don't want to crop, i'd suggest replacing
`height: 36rem`with `max-height: 36rem`

**Comment by jamieu** [comment]
Thanks Toby!

Your design is looking - even more - fantastic now the images are stating
to load :-)
