### ISSUE TITLE
Back/Home button

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#722]
[@danwhy / @simonlab - first, and I think only step here for you, is to set a url & maybe a `class` we can use to go back to the SERP page when appropriate. Will pick up the design side with @tobystokes separately]

This is primarily for the record pages (obj/doc/person) so that when a user runs a search and clicks though to a single record they have a means (other than the browser back button) of going back to the results set they were on.

I guess the simplest would be to set a cookie/session var on the SERPs page, so that:

- a user arriving from a SERP page would see a back button that took them back to the SERP page.
- a user arriving from Google or direct link would get a HOME button (back to home page) _or nothing_.
- the SERP page itself would always show the home button (back to home page) _or nothing_.

One gotcha might be to ensure that a user **ONLY sees the back button if coming directly from a SERP page**. We wouldn't want the back button to appear if a user goes off to another page and sees a back button which then leads them to an old/stale result set.

**1) User does a search**
<img width="860" alt="screen shot 2017-02-09 at 18 27 04" src="https://cloud.githubusercontent.com/assets/91365/22797372/de4ddc52-eef5-11e6-8d69-23a5427f46e1.png">

**2) User clicks on a results and sees a back button**
![back](https://cloud.githubusercontent.com/assets/91365/22797417/0bcb9368-eef6-11e6-9359-1a98a19123f4.jpg)

**3) A user arriving to the object page **via any other means** doesn't see the back button (_maybe they see a home button instead, that just goes to the home page - TBD?_)**
![home](https://cloud.githubusercontent.com/assets/91365/22797437/1e09fe7a-eef6-11e6-94fd-3b7f8c3abcb8.jpg)

**Comment by tobystokes** [comment]
One approach might be 'the crumb'
![image](https://user-images.githubusercontent.com/109024/27428195-3c456a5e-5739-11e7-9f87-5b2f9e007c3c.png)

I'm not sure whether the 'Home' link is useful though, and without an accompanying 'back' link, may look a little lost. 

As back button:
![image](https://user-images.githubusercontent.com/109024/27428124-0379841c-5739-11e7-93db-ec3bba788a84.png)
Could expand to 
![image](https://user-images.githubusercontent.com/109024/27428141-0ec86d60-5739-11e7-95a4-da83f7b6a9df.png)
on hover
(trying to visually associate it with the filters, though that may not be obvious)

**Comment by jamieu** [comment]
- I like the crumb, but agree that it would look odd with just the 'home' link its own. I guess we could use 'Home -> 656 results found' on the SERP page and 'Home -> Your search results' on object pages?
- The button with '<- Your results' seems a little too heavy/takes up too much space (although agree that without a label it may be a little cryptic).
- Could we alternate the square icon between [<-] on object ages and [H] (house) on the SERP page? Not sure if the branding/design allows it but might be better as an outline rather than a filled in button? Guess we could add in a 'tool tip' to explain what it does?

The crumb gives us more flexibility & is self describing. If we also used  'Home -> 656 results found' on the SERP page it gets around the floating 'home' and does mean you can get both (home and SERPs) from an object page.

The square icon is possible more compact/neater and only has one clear action in each context. TBH it's more what I was imagining, but do like the idea of the crumb and visually looks very clean.

Will see what @emilyfildes thinks, do you have a strong preference for either?

**Comment by tobystokes** [comment]
Crumb - you could get away with not being there on SERPS because we do have the big 'SEARCH OUR COLLECTION' in that place already.

No clear winner for me - button version should win _if_ its obvious what it does...

**Comment by emilyfildes** [comment]
Hello @tobystokes and @jamieu 

I agree that a button would be good for space etc.

Just to add complexity - presumably if you came directly into a canned search / object / person / archive page, it would need to be a little house (to get home, because you haven't started a journey); and then a back arrow if you have come from a search results page?

If we went for the breadcrumb, could it be Home ---> Search on an object where if you've come from results selecting results would take you there; and if you entered on an object page it would take to you to the search page with no search entered?

However, I don't know whether adding a breadcrumb might have tricky implications for handling the archive (e.g. do we show the levels here?). So maybe a button also wins to steer away from that?

**Comment by jamieu** [comment]
@emilyfildes your correct re. having to know if a user had arrived at an object page via a CO results page or via Google. I forgot about that, we had discussed that previously, but that does mean the "Home -> Back to your search results" wouldn't work in the Google case and would result in a floating home link/crumb (which I dislike).

In light of that the button seems to be the clear winner, still a question re. do we need two icons (home and back) or can we have a 'home' icon that serves both purposes and if so should it be a house or back arrow? A house icon feels cleaner/clearer to me if we only have one icon serving both purpose if we only had one icon (particularly for the the case that a user arrives from Google).

**Comment by tobystokes** [comment]
If you came to an object page via a SERP (canned or self-filtered), I think the button should take you back to that (even if you have gone through a number of related records perhaps).

If you come direct to a record, then either no button at all, or a home icon - I can see that it might be useful to recover to there if you are cold to the site.

(No reason to share an icon I think, am hoping for something like 
```
if referringSERP
    backbutton
else
    otherbutton

**Comment by jamieu** [comment]
> If you came to an object page via a SERP (canned or self-filtered), I think the button should take you back to that (even if you have gone through a number of related records perhaps).

yes

> If you come direct to a record, then either no button at all, or a home icon - I can see that it might be useful to recover to there if you are cold to the site.

OK two icons, 'back' if you've come from the SERP, and let's use the home icon if your coming direct to a page (either via google or a bookmark).

**Comment by Danwhy** [comment]
@tobystokes So I will add a button to the searchbox with a class of either "searchbox__back" or "searchbox__home" depending on where the user has come from, and leave the styling to you. Does that work for you?

**Comment by tobystokes** [comment]
that's fine, assuming you are also giving it the appropriate href too.

Actually I will probably need to do something like `{{>icon="back|home"}}` within that, and we might also need a title/alt="Some text" that differs for both.

**Comment by Danwhy** [comment]
Ok, I'll do that. I'll let you know when the PR is ready, so you can have a look over it when I'm done.

**Comment by Danwhy** [comment]
@tobystokes I've added the button in [here](https://github.com/TheScienceMuseum/collectionsonline/pull/898/files#diff-ac27c2a29024e638b89737055a9547b8R3) leading to the relevant places, and showing the relevant icon, you'll just need to style the class "searchbox__back" and add the "home" and "back" icons

**Comment by jamieu** [comment]
@tobystokes did you get to do this bit?

> @tobystokes I've added the button in here leading to the relevant places, and showing the relevant icon, you'll just need to style the class "searchbox__back" and add the "home" and "back" icons

**Comment by tobystokes** [comment]
It's all in PR #898 - but ready to go afai concerned

**Comment by jamieu** [comment]
Seems to work well, good job everyone on this 👍
