### ISSUE TITLE
Set default image for open graph (if no main image)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#726]
### Images 
Set default image for open graph (if no specific image)
Otherwise Facebook grabs the first image on the page, which tends to be a related object.

https://dev.twitter.com/cards/types/summary (_* I guess this is the one we want @ 1:1_)
https://dev.twitter.com/cards/types/summary-large-image

For now let's just use the image below and call it 'smg-collection-social.png' (@tobystokes is going to make a nicer / on brand version to replace this). 

### Descriptions 
Be good to also check we have good 'description text' for the various cards/metadata ie. (schema/facebook/twitter https://github.com/TheScienceMuseum/collectionsonline/issues/509) when linking to a search results page.

- When we have editorial 'descriptions' for results page (see https://github.com/TheScienceMuseum/collectionsonline/issues/779) we should use those.
- On Museum SERP pages:  "Explore items on display at `[museum(s)]`"
- On Gallery SERP pages:  "Explore items on display in the `[gallery]` gallery at the `[museum]`"
- On Category SERP pages:  "Explore our collection of `[category(s)]`"
- On Category/Museum SERP pages:  "Explore our collection of `[category(s)]` on display at `[museum]`, `[gallery]` gallery"
- **Default**: "_Explore over 250,000 objects and archives from the Science Museum, Museum of Science and Industry, National Science and Media Museum and National Railway Museum._"

(This is very similar to what we do for "Page Title" and so should possible be centralised in the same lib/block of code?) 

Can test cards here:
https://cards-dev.twitter.com/validator

**Comment by jamieu** [comment]
Could just use this for now, but lets rename it SMG_default_social.png (then I can wait it out later) 
https://collection.sciencemuseum.org.uk/assets/img/home/feature/1600/switches.jpg

**Comment by tobystokes** [comment]
Was thinking of a grid of objects, but if people are linking to a particular object, don't want anything too specific. How about a mini representation of the home page, i.e roughly 
![image](https://user-images.githubusercontent.com/109024/27548591-4af3d2e2-5a91-11e7-8035-65dfacde7cb7.png)

**Comment by jamieu** [comment]
Yes, they're (at least) three places it could be used:

- An object/person/document page with no photograph (the gradient would possible better here; as per the  SERP results without images)
- A search results page for a query, "on display at museum X" or "category Y".
- The home page

Emily's not keen on using the home page i) it will be hard to discerned what it is at small resolutions ii) could be confusing for an object page and I tend to agree with her.

Maybe simply a gradient block with "Science Museum Group Collection" with the new font/fade out? Not overly exciting but won't cause issues for anyone.

https://cards-dev.twitter.com/validator

**Comment by jamieu** [comment]
Something as simple as this? But obviously 'on brand' :-)

![smg-collection-social](https://user-images.githubusercontent.com/91365/27584759-1d8d80d2-5b31-11e7-8cb7-f6fe607704ee.png)

**Comment by jamieu** [comment]
@tobystokes I think we talked about you making a grid-like image with a bunch objects as tiny thumbs overlaid with "Science Museum Group". But happy with anything nice and generic I can use.

**Comment by tobystokes** [comment]
Suggesting
![image](https://user-images.githubusercontent.com/109024/28025256-d3008ad2-658a-11e7-9c40-c7d6d0fcd23e.png)
or the more homogenous but less recognisable
![image](https://user-images.githubusercontent.com/109024/28025282-e412df1e-658a-11e7-9ed6-0e5571d438a4.png)

(they're square, but if use for the 2:1 large crop, you'll still get the SMG logo and complete objects, hopefully.)

**Comment by jamieu** [comment]
Nice 👍
