### ISSUE TITLE
Errors finding assets 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#733]
Might be nothing to worry about, but noticing a number of broken paths in the logs - although these assets exist so not sure what is causing it.

plublic.js: no file found here:  assets/img/global/logo-scm.svg
plublic.js: no file found here:  assets/img/global/logo-smg.svg
plublic.js: no file found here:  assets/icons/symbol/svg/sprite.symbol.svg
plublic.js: no file found here:  assets/fonts/sm-din-black.woff2
plublic.js: no file found here:  assets/fonts/sm-din-regular.woff2

Seems be be [getting output here](https://github.com/TheScienceMuseum/collectionsonline/blob/master/routes/public.js) (typos come in useful sometimes!).

```
module.exports = () => ({
  method: 'GET',
  path: '/{path*}',
  config: {
    handler: function (req, reply) {
      console.log('plublic.js: no file found here: ', req.params.path);
      reply.file(Path.resolve(__dirname, '..', 'public', req.params.path));
    }
  }
});
```

**Comment by SimonLab** [comment]
@jamieu you're right the consle.log will display the message even when there is a file, I think this console.log is an old debug tool that we forgot to delete. Thanks for spotting that.
