### ISSUE TITLE
Look at better handling of records with numerous images

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#741]
Could of possible solution here:

- ~lazy load the images (tech)~
- indicate how many thumbnails/images attached to record (design)
- alternative means ie. a dropdown of all image attached to the record (design)

http://collection.sciencemuseum.org.uk/objects/co205344/the-photographic-library-of-the-daily-herald-newspaper-1911-1965

http://collection.sciencemuseum.org.uk/objects/co8052657/flying-scotsman-steam-locomotive

**Comment by tobystokes** [comment]
Allowing the row of thumbs to wrap for more rows works without much change - is this edge case or are there lots more of these?

![image](https://user-images.githubusercontent.com/109024/27427520-35b265ea-5737-11e7-8701-e56c9515cbc7.png)

**Comment by jamieu** [comment]
The issue occurs when we have a record/page that is effectively a "umbrella" record for a large number of scans or images (rather than multiple shots of a single object). 

This occurs when we have i) photographic archives that haven't been broken down into individual records/pages (these could have 1000+ images attached) or ii) we have document records/pages that have possible hundreds of (scans of) pages attached to a single record/page.

Off hand I don't know how many cases we have like this, but there will be at least several dozen object pages that are effectively "umbrella" records for large photo colelctions and possible hundred of document pages where we have more than 50 pages (which people need to scroll though).

There both slight different cases, the documents are more about finding a single page (and as they are now in order, users can scroll through them to find the page they want). The "umbrella" records for collections could possibly have 1000 of images and users may want to see the thumbnails to pick an individual images. I wonder if we should separate out the two use case? Particular as we can live (for now) with users having to scroll though a documents pages.

Sorry, that's not really getting any closer to a solution!

Could we have a toggle on records with 50+ images (and maybe documents as well) where all the thumbnails (as you have above) expand/close? 

We would have to have a cut off at say ~200 images, if we took he above approach. But maybe that is the sensible halfway house **for now**. We could then revisit how users could view the thumbnails post the ~200 mark for the few pages/records that require it.

@emilyfildes thoughts?

**Comment by tobystokes** [comment]
I think the wrapping solution helps (and doesn't hurt in any case) up to about 100 images = 4 rows.

For greater than that, I could shrink the thumb size slightly? Daily Herald has 321 images FYI.

Beyond that size we probably have a bunch of other problems with loading etc, but (if the records can't be 'fixed' - we'd probably be looking at ways of ajax-loading in more pages of thumbnails.

**Comment by jamieu** [comment]
If we do that (wrap) I think we only want to go to multiple lines if we have a large number of images, say 50+ images at least, so we don't end up with a small number of 'orphaned' thumbnails on a second line. 

Is the screenshot above all 321 Daily Herald images? If so that would work at that size.

Would be really good to have a toggle open/close though, not sure how wacky that would be, I guess the last or first timbal could be an up or down arrow.

Agree over 400 images and we probably need to rethink completely how we handle large collections of images and scans attached to a single record. Both technical and visually and now is probably not the time to embark on that.

**Comment by tobystokes** [comment]
24@3rem per row - at biggest size
but the issue for balancing rows, and determining where toggle is - this is flexible for other screen sizes. i.e. only ~8 per row on mobile. I think i had suggested before to just hide thumbnails on mobile? given the hit target is small, and the main carousel is nice and swipey...
Yep, that is the full 321 for Daily Herald above

**Comment by jamieu** [comment]
I'm fine with hiding the thumbnails on mobile.

**Comment by emilyfildes** [comment]
Hello,

I agree with you both here.

There is a chance that these photographic collections will also moved into the same model as the Daily Herald: http://www.nrm.org.uk/ourcollection/photos (however we've got to pick up the conversation with Collection Services about this). A couple of ones with big numbers..

Thanks,
Emily
