### ISSUE TITLE
Rotate zooms (in full screen)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#742]
Not sure if OSD has a rotate feature, but a number of the Babbage docs are rotated 90 degrees, be good if we could allow uses to rotate the image when in full screen/zoom mode.

http://collection.sciencemuseum.org.uk/documents/aa110000194/plan-16-arrangement-several-partial-arrangements-numerous-notes

**Comment by Danwhy** [comment]
@jamieu Got this working, just need icons for rotate-left and rotate-right

**Comment by tobystokes** [comment]
@dan i've added a couple of icon files, but not added to any classes, will leave you to you?

**Comment by Danwhy** [comment]
@tobystokes Just seen them, sounds good, thanks!

**Comment by jamieu** [comment]
Fantastic, thanks so much @tobystokes !!

(@tobystokes need to catch up with you with some design wider changes, will
drop them in a single email and we can discuss).
