### ISSUE TITLE
Jump down (V) arrow at the end of "Part of Archive Name" 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#75]
To jump down to the Archive browser (or some kind of visual indicator), or did we decide that was a bad idea? 

<img width="531" alt="screen shot 2016-06-21 at 12 55 31" src="https://cloud.githubusercontent.com/assets/91365/16234662/f62107de-37c9-11e6-9fc8-47d7667b2bbb.png">

**Comment by tobystokes** [comment]
I did link one of the templates as a straightforward jump down to #archive
Not sure it needs a visual indicator if the others don't, as long as you end up somewhere?
