### ISSUE TITLE
Odd indentation on single taxonomy terms

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#753]
http://collection.sciencemuseum.org.uk/objects/co8179412

<img width="538" alt="screen shot 2017-01-12 at 17 54 23" src="https://cloud.githubusercontent.com/assets/91365/21901589/457642e6-d8f0-11e6-905f-cfb580bbf6e9.png">

**Comment by tobystokes** [comment]
fixed in https://github.com/TheScienceMuseum/collectionsonline/commit/a52cf652f1be53f5e34ae1bc56694932f2647c63
