### ISSUE TITLE
New API route/method to convert a OBJECT NUMBER to it's path

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#757]
Given `OBJECT NUMBER `-> return the path to it's page

ie. 1998-599 would return /objects/co467174/hypothermia-advice-card-england-1994-1995-card

Additional, if we could add a flag `redirect=true` to automatically perform a `301 redirect` to the page that would be super useful. 

- /search?oid=1998-599  ---> return page path for this object as JSON _(as per other API calls)_
-  /search?oid=1998-599&redirect=true  ---> simply return a 301 redirect to the page `(with a full url/path).`

_(feel free to adjust params as makes sense)_

**Comment by SimonLab** [comment]
@jamieu instead of adding another query parameter (oid) to the search endpoint /search, could we instead create a new endpoint, for example: ```/oid/{idObject}?redirect=true``` ? This will avoid to add more complexity to the search feature.

**Comment by jamieu** [comment]
Sounds like a good idea!

**Comment by jamieu** [comment]
@SimonLab could it be possible to get the redirect to the version of the url with the slug?

Also make it a 301 redirect (if it's not already)
