### ISSUE TITLE
Zooms / complete integration

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#762]
We now have zooms in the index / S3 - be good to get this tied up (the fronted OSD code should all be there ready to go, might just need some tweaking).

Might need to update the IP address of the zoom server to the one below.

`http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/1972_36_Neg_102.ptif.dzi
`

Also:
- See if we can update the carousel code so that clicking an image opens it in zoom mode https://github.com/TheScienceMuseum/collectionsonline/issues/763
- Be good to check the status of this zoom/osd issue Daniel spotted previously: https://github.com/TheScienceMuseum/collectionsonline/issues/479
- Can we add a rotate icon in full screen mode  (let me know if we need an icon) https://github.com/TheScienceMuseum/collectionsonline/issues/742

```
            "zoom": {
              "format": "pyramid tiff",
              "location": "http://54.229.248.172/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/zoom/S/O/O/1993_8049.ptif",
              "location_is_relative": true,
              "measurements": {
                "dimensions": [
                  {
                    "dimension": "height",
                    "units": "pixels",
                    "value": 3622
                  },
                  {
                    "dimension": "width",
                    "units": "pixels",
                    "value": 4930
                  }
                ]
              },
```

**Comment by SimonLab** [comment]
@jamieu I'm currently trying to access the zoom images for "Babbage's Analytical Engine" (http://collection.sciencemuseum.org.uk/objects/co62245/babbages-analytical-engine-1834-1871-trial-model-analytical-engines).
The index has the zoom properties for this document:
```
"zoom": {
"format": "pyramid tiff",
"location": "W/P/A/1878_0003__0005_.ptif",
"location_is_relative": true,
...
```
But when I try to access the image with the new IP address:
```
http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/W/P/A/1878_0003__0005_.ptif
```

I have the following message error: ```Asked for non-existent tile: 1881```

So I was wondering if the way I built the url for the zoom is right
http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/ + {location zoom defined in Elasticsearch}

or did I miss something on the path of the url?

**Comment by jamieu** [comment]
Ah does this one work better?
http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/1972_36_Neg_102.ptif.dzi

**Comment by SimonLab** [comment]
http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/1972_36_Neg_102.ptif.dzi return a xml file which describe a tile so I think it works but it is for a specific image do you know from which document or object?

I think the root path for the zoom is http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/ but I'm not sure as I couldn't get a tile for the "Babbage's Analytical Engine". So either the root url is not right or do you think some zoom images are still in process? I'm going to continue to try to find an object where I manage to get the tile for a zoom

**Comment by jamieu** [comment]
Hi Simon,

You should be able to find them via `multimedia.processed.zoom.location`

<img width="439" alt="screen shot 2017-01-30 at 12 37 47" src="https://cloud.githubusercontent.com/assets/91365/22423318/f0f3665c-e6e8-11e6-8beb-f50ac5dd97da.png">

**Comment by jamieu** [comment]
Ah I see the issue now, OSD is returning http://54.171.226.99/iipsrv/iipsrv.fcgi_files/9/2_4.jpg ( given ttp://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/2016_0424__0003_.ptif.dzi ) which is a non-resistant path/jpg.

Is this the issue @Danwhy was looking at ( https://github.com/openseadragon/openseadragon/issues/1017
 ) and the reason we were using a fork of OSD? Although this issue now looks like it should be fixed, yet I am still seeing the issue with the latest build (on my desktop).

Trying to get back up to speed with OSD myself, re. what was working / what we expect to happen / what needs investigating further.

...

**Comment by jamieu** [comment]
I can confirm that we need to update the regex as per https://github.com/openseadragon/openseadragon/issues/1017#issuecomment-243417998 and then it works.

(@Danwhy did you fork the copy of OSD we were using for this very reason?)

Once I make that change to the OSD / openseadragon.js this works for me :-)

```
<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="osd/openseadragon.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "osd/images/",
        tileSources: "http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/I/A/A/2016_0424__0003_.ptif.dzi"
    });
</script>

```

**Comment by Danwhy** [comment]
@jamieu I think the url for the zooms on aws may need to be changed to `http://54.171.226.99/iipsrv/iipsrv.fcgi?DEEPZOOM=/s3-zooms/`

**Comment by jamieu** [comment]
Yes, I'll update it now

**Comment by jamieu** [comment]
Do we have [+] and [-] link buttons, so indicate users can zoom in/out?

Also the buttons/top bar is looking a bit odd in Safari, see screenshot below

<img width="680" alt="screen shot 2017-02-07 at 14 57 58" src="https://cloud.githubusercontent.com/assets/91365/22696452/f3437196-ed45-11e6-8410-51ebab6c9231.png">

**Comment by jamieu** [comment]
Not sure if they are handled differently on different pages, but the zoom button doesn't seem to be working on the Archive pages?
https://collection.sciencemuseum.org.uk/documents/aa110014920

**Comment by Danwhy** [comment]
No, it's not working for single images at the moment. Will be fixed in [this PR](https://github.com/TheScienceMuseum/collectionsonline/pull/785)

**Comment by jamieu** [comment]
Ah good 👍 

My guess is you already know about this / it's related to https://github.com/TheScienceMuseum/collectionsonline/pull/785, but it also seems to fail on any image other than the first.

Good to see them working though, albeit slowly, but that's not your fault! I'm going to switch over to using [Loris](https://github.com/loris-imageserver/loris) at some point in the not to distant future (it should be a near drop in replacement for IIPImage which were using currently, but using IIIF rather than the DeppZoom mode). I have a fork of Loris working locally on my laptop _with a native S3 connector_ and it's much, much faster. Just need to get my fork to the point that I can package it up and deploy it nicely/easily to AWS.

**Comment by jamieu** [comment]
Looking much better now 👍  and can already see how nice this will be once we can speed up the backend zoom serving.

One issue I spotted on iOS is that after you exit the full screen/zoom mode and go back to the normal page you get the OSD controls, see below:

![unnamed](https://cloud.githubusercontent.com/assets/91365/22754634/21e12dc0-ee38-11e6-809b-162c24623143.png)

**Comment by jamieu** [comment]
Got some more info on the Safari crashing bug.

(if this looks like a nightmare to debug/resolution isn't obvious, get on with the issues we discussed today first).

---

If I go "Fullscreen -> Escape" it is fine.

If I go “Fullscreen -> click the fullscreen control in the top right (does nothing) then -> Escape” it takes the browser down.

See here in this nice film I have made for you:
https://dl.dropboxusercontent.com/u/5499412/Zoom-Crash-Boom.mov

**Comment by jamieu** [comment]
@Danwhy Still noticing that selecting the 'close zoom' button in full screen mode crashes Safari (happened to me just now on live site).

Are you still waiting to deploy a change?

**Comment by Danwhy** [comment]
@jamieu Yeah, it looks like the deploy for this pr failed, I'll rerun it

**Comment by jamieu** [comment]
Thanks Dan,

Just FYI the S3 bucket has come unmourned from the zoom sever (hence the
missing tiles message).

**Comment by jamieu** [comment]
Closing for now, not entirely sure why it was still open
