### ISSUE TITLE
Boost fonds records on result page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#772]
For this query we'd expect the fonds record (`Archive of Williamson Kinematograph Company Limited`) to appear first.
http://collection.sciencemuseum.org.uk/search/documents?q=williamson&page%5Bsize%5D=50&page%5Btype%5D=search

Realise there might be a precision vs recall issue here, but fonds should take a huge precedence.

The initial plan was to **only** show fonds records at this level. But for that to work we'd need to be able to effectively show the top level/fonds (archive) record if _any_ documents within that archive match (which might need some careful thought/coding). You'd then only search within an archive from the search box on the archive browser. @emilyfildes can you remember our discussions here?

**Comment by iteles** [comment]
The fonds record below should be much nearer the top (currently in 5th row of results):
<img width="295" alt="screen shot 2017-02-06 at 10 37 28" src="https://cloud.githubusercontent.com/assets/4185328/22643920/69d120c2-ec58-11e6-813a-e98e446ebf01.png">

We need to take care for this not to become a big issue for now. Documenting our solution is key.

**Comment by Danwhy** [comment]
Should be the same as #771
