### ISSUE TITLE
Missing all but first occupation (people)

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#773]
We seem to have lost the 

- ES Index (cp36993):
```
"occupation": [
"computer pioneer", "mathematician"
],
```
vs

- JSON / Page (we're only showing the first value / we are also only showing one value in the JSON?)
http://collection.sciencemuseum.org.uk/people/cp36993

```
      "occupation": [
        "computer pioneer"
      ],

```

**Comment by SimonLab** [comment]
link to #532
