### ISSUE TITLE
Node security vs Unicode package

### ISSUE THREAD

**Issue by SimonLab** [TheScienceMuseum/collectionsonline#775]
At the moment node security tests are not passing due to the Unicode package used by the package slug. Some unicode data are downloaded via Http which is insecure see https://github.com/TheScienceMuseum/collectionsonline/pull/758#issuecomment-273769773

This issue is high priority has all our PRs are failing due to node security

I'm going to see what are the possible solutions:

- [ ] fork the slug package to not use Unicode or download the unicode data necessary before?
- [ ] create or own slug package?

**Comment by SimonLab** [comment]
[This package](https://github.com/simov/slugify) is a fork of the slug current package used at the moment. It seems maintained (last updated 20 days ago) and it has build and coverage badges passing. And not dependencies to unicode or any other packages!

**Comment by SimonLab** [comment]
At the end I went for the slugg package as the previous on didn't convert some characters (', ", (, ), ...) to -.

**Comment by nelsonic** [comment]
@SimonLab sounds good. thanks for including an explanation. 👍
