### ISSUE TITLE
Description boxes for key result pages

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#779]
This builds on the work around nice urls and titles for key result pages (https://github.com/TheScienceMuseum/collectionsonline/issues/668)

Obviously we need some design (below is simply a rough mockup of idea) and some wider thought around what goes within that block.

But the basic idea is that for each Category, Museum and Gallery SERP 'landing' page we allow a short chunk of rich test to be displayed at the top of the first page or results. 

Initially this will just be the title and a description paragraph and some links, but would be good to allow room for linking to related articles (within the group sites) and/or show sub-catergories for large categories based on date or materials (ie. pre-internet / post-internet for communications or metal vs plastic medical instruments).

Need to decide what to show if we are filtering by both a category and gallery (which description block do we show (for now lets go with the category taking priority). 

This will also help with SEO as it creates nice results summaries for each category, museum and gallery within google.

The Thumbnail and Description fields (where available) should also be passed to the existing/relevant Twitter/OpenGraph/Schema.org metadata fields (I think we already pass the machine generated page title which we should keep as is) --> see this old ticket: https://github.com/TheScienceMuseum/collectionsonline/issues/570. 

![category-boxes](https://cloud.githubusercontent.com/assets/91365/22547898/db6b6b7c-e93b-11e6-9df9-7929dfb09b19.jpg)

![galley-summary](https://cloud.githubusercontent.com/assets/91365/24252756/4dcf72ec-0fd6-11e7-8b32-abf882347e46.png)

**Comment by iteles** [comment]
#699 and #698 lead up to _this_ issue.

**Comment by tobystokes** [comment]
did you have a spec doc for this, or was it my imagination?
The pics above will service, if that indicates all possible contents. Would be good to know what might be optional

**Comment by jamieu** [comment]
The above will suffice for now (in giving an idea of content).

But @emilyfildes and I have had various conversations re. **exactly** what it should include, will have a read though my notes and update this issue.

**Comment by jamieu** [comment]
Here goes, feel free to make suggestions!

But these are the ones we know we can produce content for / would like feature.
We won't have content for every field in every case; have marked these fields as _optional_

## Category 

- Title  
- Short description (1 or 2 lines max)
- Sub categories / queries (ie. all object of type 'transistor radio' in the 'telecommunications' category) [_optional / up to 4 or 5?]
- Related articles on main sites (_optional_) [_optional / up to 4 or 5?]

## Gallery 

- Title  
- Thumbnail of gallery (optional)
- Short description (1 or 2 lines max)
- Link to gallery page (on main museum sites

- **drop** 'map' or 'map link' (we don't have enough to do this)
- **drop** the object thumbs, hopefully these will surface in the SERP's anyway

**Comment by shouston3** [comment]
@jamieu In regards to display box preference for when multiple filters are selected.

When a user selects both Gallery and Museum we should show information on the gallery in the description box and not about the Museum (could you clarify this).

When a user selects both a Museum and a Category which one should take preference and be shown in the description box?

The same question for when a user selects both Gallery and Category.

**Comment by jamieu** [comment]
I think Category should take priority over Gallery/Museum when we have both.

**Comment by jamieu** [comment]
And Gallery over museum, when we have both:

So in this order of priority:

Category
Gallery
Museum

**Comment by shouston3** [comment]
Great thanks @jamieu

**Comment by shouston3** [comment]
@tobystokes see #902 

I've added a description box based on each of the `json` files in the `description-boxes` directory.

The description box should appear when you select a search filter for which we have inputted data for in a file in the `description-boxes` directory

The template file to work from can be found here: https://github.com/TheScienceMuseum/collectionsonline/pull/902/files#diff-ba85b27e1227349b4197e0b205136bfd

**Comment by jamieu** [comment]
Looking good 👍  I'll start to add some entries to the description-boxes/*.json files.

btw. its correct in the config file `"sub-categories": [, But in the HTML is should be titled `Popular Categories`(not `Popular Objects`). I'm sure @tobystokes will fix this while tweaking the CSS anyway, so just flagging it up.

**Comment by jamieu** [comment]
@shouston3 looks great so far 👍 

I have added in some **real** text for all three description-boxes .json files.

In most cases the `title` will be the same as the name of the `category` or `gallery` we are matching on. In those cases it's pointless us explicitly adding a `title` element in the JSON. But would be good to have consistency on display re. titles, so could we make the 'title' fall back to the category` or `gallery` name in those cases? 

Also "Who am I?" gallery isn't displaying, despite having an entry in JSON (due to?)
http://localhost:8000/search/museum/science%20museum/gallery/who%20am%20i?%20gallery?page[size]=50

**Comment by tobystokes** [comment]
I've just moved it to where we expect it to be output.
I see @jamieu hasn't added titles because they == the category name (always?)
 - but I can't work how to output that object {{@key}} ? into the template, so maybe thats a reason for them...

**Comment by shouston3** [comment]
@jamieu If you rename `"Making the Modern World"` to `"Making The Modern World Gallery"` it should work.

Also, if the description box does not come through for a filter which you've added, there should be a message for what the key in the `json` file should be. You can see this in the developer tools of your bowser.

For instance when `"Making the Modern World"` didn't show I got the following logs in the console of my developer tools:

```
Gallery didn't match, ensure the exact gallery title was used
gallery title should match:  Making The Modern World Gallery
```

Which is telling me that the key in the `json` file it is looking for is `"Making The Modern World Gallery"`

**Comment by shouston3** [comment]
@jamieu I couldn't find `TV Heaven Gallery` in the `On Display` filters. I have the following:
<img width="224" alt="screen shot 2017-07-05 at 15 33 20" src="https://user-images.githubusercontent.com/15983736/27869443-e3c03d6e-6197-11e7-93a5-da8e454dd7cf.png">

**Comment by shouston3** [comment]
The key for the `json` file is something that isn't used (shown on the page) and that is only a reference for fetching the rest of the data.

The `"title"` key is what you want to show on the page which can freely be changed (without affecting the fetched data).

**Comment by jamieu** [comment]
Ah yes, well spotted re. `"Making The Modern World Gallery"` (I did check se fi they were the same and completely missed that). 
http://localhost:8000/search/museum/national%20media%20museum?page[size]=50

Good, forward thinking re. the 'debug output' will check that from now on.

btw. the `TV Heaven Gallery` is on the right here under NSMM
https://collection.sciencemuseum.org.uk/search/museum/national%20media%20museum?page[size]=50

**Comment by jamieu** [comment]
Looking good to me so far, @tobystokes let me know who you think you've finished your design bits.

**Comment by tobystokes** [comment]
done - though if you put in a load of new category images, i'd like to review.
(or if you need me to make/format/ category images, to be hosted in repo, then send me pics. ( @emilyfildes ?)

**Comment by jamieu** [comment]
This might just be me but when I go direct to the page (via a bookmark) I don't see the boxes?

Although if I de-select and reselect the filter (or another one) on an already loaded search results 
page I do see it? Initial load vs AJAX?

- http://localhost:8000/search/museum/science%20museum/gallery/information%20age%20gallery:%20broadcast
- http://localhost:8000/search/museum/science%20museum/gallery/making%20the%20modern%20world%20gallery

--

**Comment by emilyfildes** [comment]
Hello @tobystokes 

We were planning on getting gallery images (and will be collating these this week) - but probably no images for the categories at the moment.

Happy to share the gallery images when we have them.

Thanks!

**Comment by jamieu** [comment]
Looks good 👍 

I can add the images as we get them (may talk to you @tobystokes if they look like we could run some kind of grading/filter across them).

**Comment by tobystokes** [comment]
yeah, if you stick to standard aspect ratio of 4:3 for them all, they shouldn't need any further treatment.
