### ISSUE TITLE
Simple (example) API client

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#781]
To help bootstrap users on the API HackDay, doesn't need to be complex - in fact the simpler it is to read/follow the better.

Maybe a little client side piece of JS that lets you programatically set some params and returns you a result set, displays some key values from it (as a starter/example) and a method for pulling back an individual page that does the same. Formally using JSON-API would be nice, particularly if you can think of a lightweight JSON-API lib, but keen to keep the examples simple.

Something like this, but in JS and _a little bit more complete_
https://gist.github.com/jamieu/b0834813e715c4d1c4f5a03349535ba2

**Note: We shouldn't spend more than half a day on this for now.** It's simply to get people up and running without having to read pages of docs, we can revisit to make it more complete in a subsequent sprint if need be.

**Comment by iteles** [comment]
Including documentation, ahead of hack day.

**Comment by jamieu** [comment]
All looks good to me, great job 👍
