### ISSUE TITLE
Incorrect AdLib date

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#793]
A curious start date for the date made here
 
http://collection.sciencemuseum.org.uk/documents/aa110000009
 
MADE: 1000-1849
 
 
It is correct on Adlib 
 
http://adlib.sciencemuseum.ac.uk/AIS5/Details/archivescience/110000009
 
·   Date  ‪1834-09 - 1849-03-06‬

**Comment by Danwhy** [comment]
Looks like this is an odd/inconsistent value in the index 

<img width="314" alt="screen shot 2017-02-08 at 10 35 26" src="https://cloud.githubusercontent.com/assets/8939909/22733595/55d52b5c-edea-11e6-8479-3e5c211f54b3.png">

**Comment by jamieu** [comment]
Thanks Dan, and yes almost certainly an index issue (sorry I added this on
the tube and didn't tag it as an index issue)
