### ISSUE TITLE
Promotional block on home page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#796]
Needs more thought, but leaving this here while I kick of the thought processes.

Possible a promo-block ala the Media Museum site - but ideally with some kind of thumbnail feature/carousel to highlight or surface objects under that promo / area / theme.

ideally we'd be able to reuse and/or rotate the promos ie. "History of photography" or "Objects from this day" or "100 inventions that change the world" etc.

**Comment by tobystokes** [comment]
"large promotional block (see https://www.scienceandmediamuseum.org.uk/objects-and-stories) that also includes a carousel of related objects"

**Comment by jamieu** [comment]
- Create new large promo to sit between "on display"and "themes" - darker in colour and bigger focus on one gallery or theme (ie.Robots or Maths).
- To launch let's use "Mathematics: The Winton Gallery //---// Explore the objects from our new gallery at the Science Museum" and the current Maths Galley image from the promo block.

Once we have a new promo block:
- Swap existing Maths/Winton gallery image from main carousel
- Swap existing Maths/Winton gallery promo block to a different theme
