### ISSUE TITLE
Couple of outstanding Zoom/OSD UI bugs

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#807]
- Still seeing the zoom controls after exiting full screen / OSD mode on mobile (iOS)
- The black background doesn't cover the full screen in full screen / OSD mode (iOS)

![img_3506](https://cloud.githubusercontent.com/assets/91365/23256737/b2ba9db4-f9b8-11e6-8b9e-65bc16f14bc9.PNG)
![img_3507](https://cloud.githubusercontent.com/assets/91365/23256738/b2d44854-f9b8-11e6-8732-cb1f0f4e9fe8.PNG)

**Comment by Cleop** [comment]
2hour time capped estimate for investigation

**Comment by shouston3** [comment]
It seems that openseadragon [doesn't play well with ios and is quite buggy](https://github.com/openseadragon/openseadragon/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Abug%20ios)

['pre-full-page' and 'full-page' fire on desktop browsers and other device browsers but not on ios](https://github.com/TheScienceMuseum/collectionsonline/commit/e8d4a53e1c73eba7574f0284692c648abbff2acd#diff-d90d166a94c061094a974de2b884081dR49) which gives us nothing to react to in terms of running javascript when going to full screen mode.

It seems that osd somehow hands over the full screen functionality to ios browser which we don't have control over.

### The black background doesn't cover the full screen in full screen / OSD mode (iOS)

I noticed that with the [toolbar](https://openseadragon.github.io/examples/ui-toolbar/) had `position: relative` and the gap at the bottom of the screen was the same size as the the toolbar.

Adding `position: absolute` to this element got rid of this gap, but this messed with osd's tracking of click events and the buttons didn't work. Having a toolbar with position relative at the top of the full screen causes a gap at the bottom of the view, but it is needed for osd to ensure the correct positioning of the button click events.

### Still seeing the zoom controls after exiting full screen / OSD mode on mobile (iOS)

The toolbar are being correctly created when clicking to go full screen, but as toggling of full screen after going full screen does not fire any events our logic which removes these elements also can't run.

We could look to raise an issue on `osd` about this as I couldn't find one for the `full-page` events not firing (although I found quite a few similar issues).

**Comment by jamieu** [comment]
Thanks @shouston3 

The background (on iOS) isn't a major an issue, so let's park that one for now and I'll keep an eye on the updates to OSD.

In terms of seeing the zoom controls after exiting full screen (iOS) this one would be good to fix. But wary of us (you) spending too much time further on this one issue esp. without a clear solution is sight. Maybe open an issue with OSD and leave it at that.

I agree let's park this for now and treat it as a 'won't fix'. It may be that I have to re-look at where we continue to use OSD. But if you think you know what to ask in an OSD issue, that would be good, but lets not use up any more time in this sprint unless they come back immediately with a fix (unlikely).

(but thanks for investigating as much as you did).

**Comment by tobystokes** [comment]
fwiw, this relates to previous discussions about whether to use 'full-screen' feature, because it's behaviour does change a lot per platform. The alternative is to go 100% width/height - but still within the normal browser viewport. (we had a button for that too, but was swapped for full screen, as to have both was confusing)

**Comment by jamieu** [comment]
@tobystokes yes I remember that conversation, I think (partly because I can't remember the issues with having it within the browser window; maybe mobile?) I'd prefer to keep it fullscreen even if a bit buggy on iOS.

@shouston3 not sure if you deployed your latest change to master (that you though might be a fix). But noticed that on staging when I go fullscreen and then try to close it via the [X] icon Safari crashes/freezes. This is on Safari desktop (OSX) not iOS. 

Obviously a messed up layout is simply annoying (and we can live with it for now), crashing/freezing browser is v.bad :-)

**Comment by shouston3** [comment]
Crashing on safari desktop started happening for me too after the ios fix.

I've ensured that my changes only apply when on mobile in this pr: #947

**Comment by jamieu** [comment]
I'm still seeing issues with Safari (OSX Desktop) crashing...

(this is on master / live site)

**Comment by shouston3** [comment]
@jamieu After pulling down the current master, I am also experiencing this safari bug issue.
My previous fix no longer seemed to work. I've added another change here which should now work.

The safari crashing bug should be fixed when pr #955 gets merged in

**Comment by Cleop** [comment]
@shouston3 #955 has now been merged. Are you happy to remove the `in-progress` label and confirm this is ready for testing?

**Comment by shouston3** [comment]
@jamieu Ready for testing

**Comment by jamieu** [comment]
> Still seeing the zoom controls after exiting full screen / OSD mode on mobile (iOS)
> 
> The toolbar are being correctly created when clicking to go full screen, but as toggling of full screen after going full screen does not fire any events our logic which removes these elements also can't run.
> 
> We could look to raise an issue on osd about this as I couldn't find one for the full-page events not firing (although I found quite a few similar issues).

Leaving this issue open for this issue, in case OSD resolve or we have a brainwave.

**Comment by jamieu** [comment]
Finally!

Although be good to get to the bottom of what is causing the "Tile loaded before reset" issue (will open a septette issue of that as I doubt we'll get to it this week)
