### ISSUE TITLE
iOS : Switching orientation in fullscreen/OSD mode causing issue

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#847]
**Before**
![before](https://cloud.githubusercontent.com/assets/91365/24361401/cf5cf3d8-1301-11e7-8e5d-10435f226ca3.PNG)

**After**
![after](https://cloud.githubusercontent.com/assets/91365/24361405/d4793f34-1301-11e7-9376-d350a0ce6f26.PNG)

**Comment by Cleop** [comment]
2 hours time capped for investigation

**Comment by shouston3** [comment]
@Cleop Investigation was around 2h (iphone debugging setup and debugging) and implementation after finding out what was going wrong was around 45m.
