### ISSUE TITLE
Add Wikipedia biogs to people/org. pages

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#859]
Note at this stage, it would be good simply to have the 'hooks' in place to all pull-back some basic info such as a desc. or the wikimedia image for a person/org(ideally hidden on production and only appearing on staging for now) via a flag/if). 

_I can then extend on this over time or we can revisit in subsequent sprint. Could take some time to agree internally what can/can't appear etc. and how it should appear (design wise). But be good if I could demo 'basic functionality' on 'staging' to give internal stakeholders an idea of what we could do here, if we started to add in more urls and linked data resources to the backend records / if we expanded on this feature more in future._

---

I imagine this could work in a similar fashion to how we implemented the 'related links' to articles the main museum sites?

URL's will appear in notes fields on biography pages.

There a couple of nice looking NPM packages to help with retiring wiki data.
https://www.npmjs.com/package/node-wikipedia
https://www.npmjs.com/package/wikijs

----

Thoughts long term on design/display (leaving here as a reminder to self):

- need to identify wikipedia urls (and only use if a single url)
- need to be visually distinguishable from SMG biographies (shaded/coloured background)
- need to link back to Wikipedia with attribution / licence
- need to downgrade (ie.show closed) the Wikipedia entry if the SMG one is >200 words (TBA)
- ideally identify where SMG is the automotive or canonical source of a biography
- should only show the first paragraph (TBA) of a Wikipedia entry

**Comment by Danwhy** [comment]
@jamieu Do you know of any people records that definitely have a wikipedia url? I'm having trouble finding any.

**Comment by Danwhy** [comment]
@jamieu Not to worry, I've found a few now

**Comment by jamieu** [comment]
Would you expect this to work on other pages with wiki urls?

This page has a wiki url in the notes field...
http://localhost:8000/people/cp34099/the-associated-equipment-company-limited

```
      "description": [
        {
          "primary": true,
          "type": "note",
          "value": "WIKI: http://en.wikipedia.org/wiki/Associated_Equipment_Company"
        },
```

And there's an image at that wiki url..
https://en.wikipedia.org/wiki/Associated_Equipment_Company

But it's not being pulled though?

(Einstein is working fine http://localhost:8000/people/cp37054/albert-einstein)

---------------

Also can we look at getting i) the credit line and ii) the licence (ie. CC) pulled though and displayed under the image and iii) check and only display the image if the CC licence means it's OK for us to display/use the image? (ie. non commercial use).
