### ISSUE TITLE
Overview design for related articles

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#865]
See already implemented feature https://github.com/TheScienceMuseum/collectionsonline/issues/820

We've pretty much got the design for this already re. related people, but would be good to get your design eye to give it a look over / tie it into the design refresh.
https://collection.sciencemuseum.org.uk/objects/co8223264

<img width="502" alt="screen shot 2017-04-20 at 13 49 09" src="https://cloud.githubusercontent.com/assets/91365/25231558/32e0e78a-25d0-11e7-9197-196ef765ced2.png">

**Comment by tobystokes** [comment]
So to confirm - this is a list of other pages on SMG sites that link to this object, yes?

**Comment by jamieu** [comment]
Exactly
