### ISSUE TITLE
Change 'param paths' to lowercase and remove default page[size] from URL's

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#867]
See #668 for past context

1) Can we convert paths to lowercase within the site, they seem to work interchangeable?

Current: http://collection.sciencemuseum.org.uk/search/museum/National%20Railway%20Museum/gallery/Warehouse?page[size]=50

Converted to lowercase: http://collection.sciencemuseum.org.uk/search/museum/national%20railway%20museum/gallery/warehouse?page[size]=50

2) Also can we remove the `?page[size]=50` from the filters / urls, unless we actually need to specify the default page size. 

3) Would also be great if we could covert the spaces (%20) to underscores (_). 

I realise that if we convert spaces to underscores (_) in the urls/paths, we'll need to convert them back to spaces in order to match against the terms in the index - which would cause issues if a term/value in the index already has a underscore to start with, but looking at our existing values I can't see any that are currently using underscores and we probably could enforce that. 

I guess to be completely on the safe side we could also convert underscores (in the original terms) into a double underscore (or another char or sequence of chars we know will never be used in the index) when appearing in paths and then convert double underscores back into a single underscore for matching.

5) Need to ensure that the sitemap.xml reflect the above changes (https://github.com/TheScienceMuseum/collectionsonline/issues/698)

**Comment by Cleop** [comment]
4 hour time estimate for a 1/2 day spike

**Comment by jamieu** [comment]
@danwhy - not are if I need to check a specific branch but still seeing `page[size]=50` when clicking on any facets?

**Comment by jamieu** [comment]
Whoo, looks good 👍
