### ISSUE TITLE
Migrate / refactor to ES5

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#870]
Trying to think when the best point to schedule this in would be. We'll shortly have both an ES2.3 (as per now) and ES5 backed index available. But only one index will be getting updated nightly (ES2.3 for now).

I'm keen to get the migration to ES5 in the roadmap (sooner rather than later). Not least as it (hopefully) solves the pagination issue, is more efficient and post refactoring should make new queries easier. Also keen that we don't fall to far behind in major versions. But aware that mixing up up with a dev sprint might cause us headaches.

Thoughts?

**Comment by Cleop** [comment]
2 hour time estimate for investigation

**Comment by Danwhy** [comment]
Relevant ES5 changes:
### [search_type=scan removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed)
We're only using this in our `get-galleries` script, but we'll have to update it to a scroll request.

### [Deprecated queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_deprecated_queries_removed)
We need to change any of these we are using

### [Changes to queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_changes_to_queries)
Same here

### [Top level filter parameter deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_top_level_literal_filter_literal_parameter)
We're using this in a few places, will need to change it to use post_filter

### [Suggester changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_suggester.html#breaking_50_suggester)
We may need to check our autocomplete still works

We'll also need to upgrade our [elasticsearch node client](https://www.npmjs.com/package/elasticsearch) to 13.2.0
