### ISSUE TITLE
Head elements don't update when moving between result page

### ISSUE THREAD

**Issue by tobystokes** [TheScienceMuseum/collectionsonline#871]
When navigating record pages (ajax, not full page load), certain head elements like twitter/og meta elements remain as per the original loaded record, not the currently displayed one.

**Comment by jamieu** [comment]
@tobystokes do you have an example of the CSS colours not updating

(twitter/og meta elements not an issue as Twitter etc. will re-retive the page, and correct OG data, based on url/fresh request).

**Comment by tobystokes** [comment]
no, I updated the bits I need:
https://github.com/TheScienceMuseum/collectionsonline/commit/1157d92ec861807a879a559f6c7b12b717aeb2d8

just noticed other head things didn't update, but may not be isse

**Comment by jamieu** [comment]
Cool, will close.

(thanks for flagging up the other header bits; but I think we're probably OK as the page will always be re-requested by external sites via a fresh page request and hence pickup the new metadata; or at least I hope GoogleBot isn't so 'AJAX smart' that we get bent y this)
