### ISSUE TITLE
No results page should suppress all/people/object/document tabs

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#883]
http://collection.sciencemuseum.org.uk/search?q=zzzzzzzzzzzz

<img width="458" alt="screen shot 2017-06-15 at 11 34 26" src="https://user-images.githubusercontent.com/91365/27177581-c6ffba62-51be-11e7-9754-92d48798179c.png">

**Comment by Cleop** [comment]
When there are 0 results:
- [ ] Remove People/Objects/Docs tabs
When there are 0 results and 0 filters applied:
- [ ] Remove filter search/ clear filters section on the right

**Comment by jamieu** [comment]
Much better 🥇
