### ISSUE TITLE
Increase truncation length on SERP boxes

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#891]
New design handle the overflow better, therefore we can remove the tight (20 chars) truncation and simple set a max (safety) value of say 250 chars.

See https://github.com/TheScienceMuseum/collectionsonline/issues/728#issuecomment-309831758

note: this can't be deployed till 728 is merged.

**Comment by tobystokes** [comment]
I've removed the truncate filter on the SERP card titles as part of #728 but it looks like the title data on the results page is also shortened in another way - e.g. http://collection.sciencemuseum.org.uk/objects/co498436/distended-human-skull-labelled-ln-fowler-for-phr-human-remains-skull

**Comment by jamieu** [comment]
@tobystokes Let's pick this up tomorrow (5th July) with @Danwhy and @shouston3
