### ISSUE TITLE
Styling for images on biog pages

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#944]
Not sure the solution here, but the images feel a little overpowering for the (average) page?

Any thoughts? Feel free to make it a `won't fix` - but appreciate your thoughts first ;-)

_We will have a copyright / credit / licence line under the image._

Real examples on staging:
http://localhost:8000/people/cp37054/albert-einstein
http://localhost:8000/people/cp122102/daily-news

<img width="707" alt="screen shot 2017-07-12 at 17 59 16" src="https://user-images.githubusercontent.com/91365/28129638-f290d580-672b-11e7-8723-e2159b389f4b.png">
<img width="822" alt="screen shot 2017-07-12 at 17 59 03" src="https://user-images.githubusercontent.com/91365/28129637-f2898104-672b-11e7-895e-52acf4a2fa67.png">

It looks much better (of course) when we have a full biog. to balance out the image.
<img width="715" alt="screen shot 2017-07-12 at 18 05 04" src="https://user-images.githubusercontent.com/91365/28129816-affdd62c-672c-11e7-983a-7b4f0077cb4f.png">

**Comment by tobystokes** [comment]
'proper' fix would be to have sufficient primary text content to balance.
if you think that is never likely to happen, then i'm not sure it's worth adding a picture to it!

**Comment by jamieu** [comment]
Let me just put my biographers hat on and crank out some primer text ;-)

No, we won't ever have good blocks of text for all pages, but would be nice
to show a photo and esp. logos - even on thin records.

Not sure we can distinguish a logo from a photo.

Maybe your right and we shouldn't show an image (or at least a big one)
when the text is <100 words?

TBH it was a bit of an unfair request as I can't see a nice solution
either, but then your the genius designer :-)

**Comment by tobystokes** [comment]
we could do a smaller in-the-text-column version, but that would definitely need some logic to determine how long the main content is, and revert to right col if bigger.

**Comment by jamieu** [comment]
TBH the two issues are far more pressing 'design wise' :-)
https://github.com/TheScienceMuseum/collectionsonline/issues/940
https://github.com/TheScienceMuseum/collectionsonline/issues/942

**Comment by jamieu** [comment]
Closing for now, will re-visit once we have (more) real content and ready to go live.
