### ISSUE TITLE
Search box text on mobile

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#95]
Would be better to just have the world "Search" (in the box) on the smallest breakpoint and lose the (small) text above the search box. 

<img width="479" alt="screen shot 2016-06-24 at 12 18 39" src="https://cloud.githubusercontent.com/assets/91365/16336499/09866b96-3a06-11e6-9eea-da5553385d8f.png">

**Comment by tobystokes** [comment]
You shouldn't have that placeholder text on small breakpoints allready, will check.

**Comment by jamieu** [comment]
Thanks..

<img width="734" alt="screen shot 2016-06-24 at 12 51 58" src="https://cloud.githubusercontent.com/assets/91365/16337060/74879f10-3a0a-11e6-82fd-59d1b111544c.png">

**Comment by jamieu** [comment]
Think it might also be useful to take the point size of the "Export over 150,000 objects.." down a point or two (and it takes up a lot of space on mobile; distract from the Search box input). 

Happy for that reduction in font size to happen on the desktop version too if that's easier.
